/**
 * Auto-extracted from misc_matchesQQ.c during reorganization.
 */
#include "engine/scenegraph.h"
#include "game/tick.h"

/* @addr 0x004b8ec0 (92b)
 *   eax = arg0; g_dispatchSave1559 = eax;
 *   ecx = eax + 0x200; edx = eax + 0x400;
 *   g_dispatchSave1560 = ecx; g_dispatchSave1561 = edx;
 *   ecx = eax + 0x580; edx = eax + 0x680;
 *   g_dispatchSave1562 = ecx; g_dispatchSave1563 = edx;
 *   ecx = eax + 0x720; edx = eax + 0x780;
 *   eax += 0x7c0; g_dispatchSave1564=ecx; g_dispatchSave1565=edx;
 *   g_dispatchSave1566=eax; ret.
 */
extern unsigned int g_dispatchSave1559;
extern unsigned int g_dispatchSave1560;
extern unsigned int g_dispatchSave1561;
extern unsigned int g_dispatchSave1562;
extern unsigned int g_dispatchSave1563;
extern unsigned int g_dispatchSave1564;
extern unsigned int g_dispatchSave1565;
extern unsigned int g_dispatchSave1566;
extern void MStackBracket5_LinkedListUnlink(void);
extern void CountdownClampWalk(void);
extern void DownloadPlayerChar(void);
extern void DualWalkRange(void);
extern void BootDispatchSlotInit(void);
extern void CjInstallSelfRouter(void);
extern void ScaledChainCallPauseSetJmp(void);
extern void MStackBracket2_TreeWalkRecursive(void);
extern void DualCallPauseDirtyJmp_00490c30(void);
extern void CallPauseScaledStoreCopyJmp(void);
extern void ScaledArrStore_GuardedChainCmpDualBitXor_00429980(void);
extern void MStackPushComplexCallPop_MStackPush2ChainPrepend_00406430(void);
extern unsigned int g_counter_0053a51c;
extern unsigned int g_tickFlagF;
extern unsigned int g_hitPhase;
extern void StreamChainStringInstall(void);
extern void StorePauseImulShr16(void);
extern void Mul10TailPairMidChain(void);
extern void NotShrCmp1Store(void);
extern void Wrapper_ScaledChainPushCall_004ef8b0(void);
extern void Wrapper_ScaledChainPushCall_004ef858(void);
extern void PendingMatch_StoreTwoCall_0042b930(void);
extern void FpuSqrtMul(void);
extern unsigned int g_dualB_00538038;
extern unsigned int g_dualB_0053803c;
extern unsigned int g_bootInitSaveSlot;
extern void TripleSubVec3(void);
extern void Mul10SumSqrt(void);
extern void MStackPushTableWalk(void);
extern void LoadCmpAddrJmp(void);
extern void ScaledInitOrSelfPtrSetType_0046a5e0(void);
extern void ScaledStoreCSet58Jmp(void);
extern void CjTableThresholdDispatch(void);
extern void GateDispatch6c(void);
extern void TwoEntryWrapperGuarded(void);
extern void DualGatedStateYield(void);
extern void DualScaledInitCmp_0046dbd0(void);
extern void FlagCascadeStateSet(void);
extern void MoveDispatch4StateFsm(void);
extern void IdCascadeBitSet(void);
extern void Scaled3StorePushCallJmp(void);
extern void Thunk_InstallSelfChainSet2011(void);
extern void StateDispatchYield(void);
extern unsigned int g_dispatchState;
extern unsigned int g_stateFlag;
extern void PushPopState70Mask(void);
extern void Thunk_LinkedListBitMaskSearch(void);
extern void CopyJmp_ScaledSubStore_g_currentNodeIdx(void);
extern void ScaledChain3c74(void);
extern void ScaledChain3c7c(void);
extern void MStackCall_MStackPush2ChainPrepend_00406340(void);
extern void PendingMatch_0046cd30(void);
extern void Phase3InstallPackedSelf(void);
extern void ZeroSlotsGatedDispatch(void);
extern void GuardedSeq_GuardedChainCmpDualBitXor_then_ScaledIncCmpJmp(void);
extern void ScaledInitOrSelfPtr_CallPauseDirty1JmpDirty4StackPush(void);
extern void MStackPush2ChainSwap(void);
extern void CopyJmp_GuardedChainPushSetCallPop_g_currentNodeIdx(void);
extern void DivLongPushCall(void);
extern void ScaledDecPop_00404c40(void);
extern void ScaledDecPop_00404bd0(void);
extern void TripleMul10VecJmpFpu(void);
extern void DownloadPlayerChar_Variant(void);
extern void TripleStateSwapCall(void);
extern void Atan2QuadrantLookup(void);
extern void InstallSelfChainSet2011(void);
extern void GuardedChainPushSetCallPop(void);
extern void MStackPushSet0001(void);
extern void ScaledInit_GuardedDirtyXformFromTable_g_scaledInit(void);
extern void ScaledZero44(void);
extern void ScaledChainNegStore(void);
extern void DualCallPauseDirtyJmp_00490c30(void);
extern void CallPauseScaledDecJmp(void);
extern void PushPop84TripleCall(void);
extern void Vec3DeltaDualMul10(void);
extern void FiveCallGuardSetTail(void);
extern void ScaledLitLoadCall_ScaledChainCallPauseSetJmp_then_Wrapper_IterLoad_0048fd30_00480fe0(void);
extern void Thunk_InstallSelfChainSetB333v2(void);
extern void HitReactionDispatcher(void);
extern void Cmp2DirtyToggle(void);
extern void ScaledClear1cTestWalkCall(void);
extern void MStackBracket4_ListInsertZeroFill(void);
extern void MStackPush3LinkedListWalk(void);
extern void MStackScopedSlotSetupPair(void);
extern void ChainSetupBitToggle(void);
extern void MstackPopScaledChainPlusThunks(void);
extern void InstallSelfCmdStreamInterp(void);
extern void DirtyDoubleDeref(void);
extern void DispatchSwitchWalkCmp(void);
extern void Wrapper_CmpDualPatchScaledRangeJmp_004e4850(void);
extern void ScaledAndCheckJmp(void);
extern void AudioVolumeRescale(void);
extern void CallPauseConstStoreJmp_MultiThunkDispatcher_then_InstallSelfPair(void);
extern void InstallSelfPair(void);
extern void MStackPushSet6Jmp(void);
extern void MStackPushSet0Jmp(void);
extern void GuardedSeq_DualSetShiftCall_then_DoubleStackPushAndJmp7b(void);
extern void GuardedSeq_DualSetShiftCall_then_DoubleStackPushAndJmp7d(void);
extern void Push70CallScaleArith(void);
extern void StateGateMStackOverlap(void);
extern void ChainDecCondStoreCallJmp(void);
extern void ScaledAddDeref(void);
extern void MStackPush2ChainLLInsert(void);
extern void ScaledLitAddJmp(void);
extern void MStackPushDispatchBitGate(void);
extern void PushDualDerefClearPop(void);
extern void MStackPushTwoEntryChainCall(void);
extern void PushPopScaled18(void);
extern void PushCallSet2147Jmp(void);
extern void TableLookupCall_g_table_004efa00(void);
extern void CmpEqInitCallElseJmp(void);
extern void MStackAngleRatioSubchain(void);
extern void PushStackAllocCall(void);
extern void DualScaledInitClear(void);
extern void ScaledShrAnd(void);
extern void DualEntryBitFlagDispatch(void);
extern void SlotPhaseResetInstallChain(void);
extern void RoundEndDifferenceFsmCluster(void);
extern void ClampNegPair(void);
extern void Vec2SumMul10ChainCompute(void);
extern void GuardedSeq_MStackCall_then_CallSetPause_0049a650(void);
extern void AtanDualDeltaThreshold(void);
extern void Set43DualCallJmp(void);
extern unsigned int g_scaledArgChain;
extern unsigned int g_load_0052ab04;
extern unsigned int g_load_0052ab08;
extern unsigned int g_load_0052ab10;
extern s32 g_dlNalt1;
extern s32 g_dlNalt2;
extern unsigned int g_dataArr_00535cfc;
extern unsigned int g_dataArr_0053a1d0;
void Helper_TickInit(unsigned int base) {
    g_dispatchSave1559 = base;
    g_dispatchSave1560 = base + 0x200;
    g_dispatchSave1561 = base + 0x400;
    g_dispatchSave1562 = base + 0x580;
    g_dispatchSave1563 = base + 0x680;
    g_dispatchSave1564 = base + 0x720;
    g_dispatchSave1565 = base + 0x780;
    g_dispatchSave1566 = base + 0x7c0;
}

