/**
 * Auto-extracted from misc_matchesQQ.c during reorganization.
 */
#include "engine/scenegraph.h"
#include "game/tick.h"

/* @addr 0x004b8ec0 (92b)
 *   eax = arg0; g_dispatchSave1559_00ab4d9c = eax;
 *   ecx = eax + 0x200; edx = eax + 0x400;
 *   g_dispatchSave1560_00ab4da0 = ecx; g_dispatchSave1561_00ab4da4 = edx;
 *   ecx = eax + 0x580; edx = eax + 0x680;
 *   g_dispatchSave1562_00ab4da8 = ecx; g_dispatchSave1563_00ab4dac = edx;
 *   ecx = eax + 0x720; edx = eax + 0x780;
 *   eax += 0x7c0; g_dispatchSave1564_00ab4db0=ecx; g_dispatchSave1565_00ab4db4=edx;
 *   g_dispatchSave1566_00ab4db8=eax; ret.
 */
extern unsigned int g_dispatchSave1559_00ab4d9c;
extern unsigned int g_dispatchSave1560_00ab4da0;
extern unsigned int g_dispatchSave1561_00ab4da4;
extern unsigned int g_dispatchSave1562_00ab4da8;
extern unsigned int g_dispatchSave1563_00ab4dac;
extern unsigned int g_dispatchSave1564_00ab4db0;
extern unsigned int g_dispatchSave1565_00ab4db4;
extern unsigned int g_dispatchSave1566_00ab4db8;
extern void MStackBracket5_LinkedListUnlink(void);
extern void CountdownClampWalk(void);
extern void DownloadPlayerChar(void);
extern void DualWalkRange(void);
extern void BootDispatchSlotInit(void);
extern void CjInstallSelfRouter(void);
extern void ScaledChainCallPauseSetJmp(void);
extern void MStackBracket2_TreeWalkRecursive(void);
extern void DualCallPauseDirtyJmp_00490c30(void);
extern void CallPauseScaledStoreCopyJmp(void);
extern void ScaledArrStore_00429980(void);
extern void MStackPushComplexCallPop_00406430(void);
extern unsigned int g_counter_0053a51c;
extern unsigned int g_tickFlagF;
extern unsigned int g_hitPhase;
extern void StreamChainStringInstall(void);
extern void StorePauseImulShr16(void);
extern void Mul10TailPairMidChain(void);
extern void NotShrCmp1Store(void);
extern void Wrapper_0048a3a0(void);
extern void Wrapper_0048a350(void);
extern void PendingMatch_0042b930(void);
extern void FpuSqrtMul(void);
extern unsigned int g_dualB_00538038;
extern unsigned int g_dualB_0053803c;
extern unsigned int g_bootInitSaveSlot;
extern void TripleSubVec3(void);
extern void Mul10SumSqrt(void);
extern void MStackPushTableWalk(void);
extern void LoadCmpAddrJmp(void);
extern void ScaledInitOrSelfPtrSetType_0046a5e0(void);
extern void ScaledStoreCSet58Jmp(void);
extern void CjTableThresholdDispatch(void);
extern void GateDispatch6c(void);
extern void TwoEntryWrapperGuarded(void);
extern void DualGatedStateYield(void);
extern void DualScaledInitCmp_0046dbd0(void);
extern void FlagCascadeStateSet(void);
extern void MoveDispatch4StateFsm(void);
extern void IdCascadeBitSet(void);
extern void Scaled3StorePushCallJmp(void);
extern void Thunk_00439e30(void);
extern void StateDispatchYield(void);
extern unsigned int g_dispatchState;
extern unsigned int g_stateFlag;
extern void PushPopState70Mask(void);
extern void Thunk_0049cba0(void);
extern void CopyJmp_0048ee80(void);
extern void ScaledChain3c74(void);
extern void ScaledChain3c7c(void);
extern void MStackCall_00406340(void);
extern void PendingMatch_0046cd30(void);
extern void Phase3InstallPackedSelf(void);
extern void ZeroSlotsGatedDispatch(void);
extern void GuardedSeq_004297b0(void);
extern void ScaledInitOrSelfPtr_00428950(void);
extern void MStackPush2ChainSwap(void);
extern void CopyJmp_00406ba0(void);
extern void DivLongPushCall(void);
extern void ScaledDecPop_00404c40(void);
extern void ScaledDecPop_00404bd0(void);
extern void TripleMul10VecJmpFpu(void);
extern void DownloadPlayerChar_Variant(void);
extern void TripleStateSwapCall(void);
extern void Atan2QuadrantLookup(void);
extern void InstallSelfChainSet2011(void);
extern void GuardedChainPushSetCallPop(void);
extern void MStackPushSet0001(void);
extern void ScaledInit_0048f720(void);
extern void ScaledZero44(void);
extern void ScaledChainNegStore(void);
extern void DualCallPauseDirtyJmp_00490c30(void);
extern void CallPauseScaledDecJmp(void);
extern void PushPop84TripleCall(void);
extern void Vec3DeltaDualMul10(void);
extern void FiveCallGuardSetTail(void);
extern void ScaledLitLoadCall_00480fe0(void);
extern void Thunk_0043a540(void);
extern void HitReactionDispatcher(void);
extern void Cmp2DirtyToggle(void);
extern void ScaledClear1cTestWalkCall(void);
extern void MStackBracket4_ListInsertZeroFill(void);
extern void MStackPush3LinkedListWalk(void);
extern void MStackScopedSlotSetupPair(void);
extern void ChainSetupBitToggle(void);
extern void MstackPopScaledChainPlusThunks(void);
extern void InstallSelfCmdStreamInterp(void);
extern void DirtyDoubleDeref(void);
extern void DispatchSwitchWalkCmp(void);
extern void Wrapper_00438c40(void);
extern void ScaledAndCheckJmp(void);
extern void AudioVolumeRescale(void);
extern void CallPauseConstStoreJmp_004350f0(void);
extern void InstallSelfPair(void);
extern void MStackPushSet6Jmp(void);
extern void MStackPushSet0Jmp(void);
extern void GuardedSeq_00473ef0(void);
extern void GuardedSeq_00473f10(void);
extern void Push70CallScaleArith(void);
extern void StateGateMStackOverlap(void);
extern void ChainDecCondStoreCallJmp(void);
extern void ScaledAddDeref(void);
extern void MStackPush2ChainLLInsert(void);
extern void ScaledLitAddJmp(void);
extern void MStackPushDispatchBitGate(void);
extern void PushDualDerefClearPop(void);
extern void MStackPushTwoEntryChainCall(void);
extern void PushPopScaled18(void);
extern void PushCallSet2147Jmp(void);
extern void TableLookupCall_00489ff0(void);
extern void CmpEqInitCallElseJmp(void);
extern void MStackAngleRatioSubchain(void);
extern void PushStackAllocCall(void);
extern void DualScaledInitClear(void);
extern void ScaledShrAnd(void);
extern void DualEntryBitFlagDispatch(void);
extern void SlotPhaseResetInstallChain(void);
extern void RoundEndDifferenceFsmCluster(void);
extern void ClampNegPair(void);
extern void Vec2SumMul10ChainCompute(void);
extern void GuardedSeq_0049a650(void);
extern void AtanDualDeltaThreshold(void);
extern void Set43DualCallJmp(void);
extern unsigned int g_scaledArgChain;
extern unsigned int g_load_0052ab04;
extern unsigned int g_load_0052ab08;
extern unsigned int g_load_0052ab10;
extern s32 g_dlNalt1;
extern s32 g_dlNalt2;
extern unsigned int g_dataArr_00535cfc;
extern unsigned int g_dataArr_0053a1d0;
void Helper_TickInit(unsigned int base) {
    g_dispatchSave1559_00ab4d9c = base;
    g_dispatchSave1560_00ab4da0 = base + 0x200;
    g_dispatchSave1561_00ab4da4 = base + 0x400;
    g_dispatchSave1562_00ab4da8 = base + 0x580;
    g_dispatchSave1563_00ab4dac = base + 0x680;
    g_dispatchSave1564_00ab4db0 = base + 0x720;
    g_dispatchSave1565_00ab4db4 = base + 0x780;
    g_dispatchSave1566_00ab4db8 = base + 0x7c0;
}

