/* GENERATED (grow_native.py frontier). Weak stub frontier for native-full:
 * functions return 0; globals not covered by native_globals.h are 4-byte
 * placeholders. All weak, gated by MK4_NATIVE_FULL. The native-port work-list. */

#ifdef MK4_NATIVE_FULL
__attribute__((weak)) unsigned int g_dispatchSave1161;
__attribute__((weak)) unsigned int g_audioPreState;
__attribute__((weak)) unsigned int g_audioRestoreSlot3;
__attribute__((weak)) unsigned int g_audioState00;
__attribute__((weak)) unsigned int g_audioState08;
__attribute__((weak)) unsigned int g_audioStreamState;
__attribute__((weak)) unsigned int g_auxChannels;
__attribute__((weak)) unsigned int g_auxCount;
__attribute__((weak)) unsigned int g_bootInitSaveSlot;
__attribute__((weak)) unsigned int g_clampedRendererMode;
__attribute__((weak)) unsigned int g_comptr_0058c7c0;
__attribute__((weak)) unsigned int g_comptr_0058c860;
__attribute__((weak)) unsigned int g_comptr_0058c864;
__attribute__((weak)) unsigned int g_comptr_0058c868;
__attribute__((weak)) unsigned int g_comptr_0058c870;
__attribute__((weak)) unsigned int g_comptr_0058c8e0;
__attribute__((weak)) unsigned int g_comptr_0058c8e4;
__attribute__((weak)) unsigned int g_comptr_0058c8e8;
__attribute__((weak)) unsigned int g_comptr_0058c8f0;
__attribute__((weak)) unsigned int g_currentNodeFlags;
__attribute__((weak)) unsigned int g_currentRendererMode;
__attribute__((weak)) unsigned int g_dispatchSave1163;
__attribute__((weak)) unsigned int g_dispatchSave1164;
__attribute__((weak)) unsigned int g_dispatchSave1314;
__attribute__((weak)) unsigned int g_drawSceneTimeMs;
__attribute__((weak)) unsigned int g_dsoundContext;
__attribute__((weak)) unsigned int g_ecmReserved;
__attribute__((weak)) unsigned int g_eq;
__attribute__((weak)) unsigned int g_eventQueueActive;
__attribute__((weak)) unsigned int g_eventQueueChild;
__attribute__((weak)) unsigned int g_eventQueueCurrent;
__attribute__((weak)) unsigned int g_eventQueueDrainBase;
__attribute__((weak)) unsigned int g_eventQueueEnd;
__attribute__((weak)) unsigned int g_eventQueueHead;
__attribute__((weak)) unsigned int g_eventQueueIdx;
__attribute__((weak)) unsigned int g_eventQueueNotMask;
__attribute__((weak)) unsigned int g_eventQueuePending;
__attribute__((weak)) unsigned int g_eventQueueTotal;
__attribute__((weak)) unsigned int g_eventQueueWorkType;
__attribute__((weak)) unsigned int g_fightGroupHead;
__attribute__((weak)) unsigned int g_fightGroupHeads;
__attribute__((weak)) unsigned int g_fightTableA0;
__attribute__((weak)) unsigned int g_fightTableA1;
__attribute__((weak)) unsigned int g_fightTableA2;
__attribute__((weak)) unsigned int g_fightTableB0;
__attribute__((weak)) unsigned int g_fightTableB1;
__attribute__((weak)) unsigned int g_fightTableB2;
__attribute__((weak)) unsigned int g_fightTableC0;
__attribute__((weak)) unsigned int g_fightTableC1;
__attribute__((weak)) unsigned int g_fightTableC2;
__attribute__((weak)) unsigned int g_frameCounter;
__attribute__((weak)) unsigned int g_framePauseFlag;
__attribute__((weak)) unsigned int g_fsys_archive;
__attribute__((weak)) unsigned int g_gameMode;
__attribute__((weak)) unsigned int g_gameStateResult;
__attribute__((weak)) unsigned int g_gtAxisX;
__attribute__((weak)) unsigned int g_gtAxisY;
__attribute__((weak)) unsigned int g_gtAxisZ;
__attribute__((weak)) unsigned int g_gtConfig4f;
__attribute__((weak)) unsigned int g_gtFightTickCounter;
__attribute__((weak)) unsigned int g_gtModeFlag;
__attribute__((weak)) unsigned int g_gtOtherFlag;
__attribute__((weak)) unsigned int g_gtPauseMode;
__attribute__((weak)) unsigned int g_gtPlayerEnabled;
__attribute__((weak)) unsigned int g_gtPlayerProbe1;
__attribute__((weak)) unsigned int g_gtPlayerProbe2;
__attribute__((weak)) unsigned int g_gtState438;
__attribute__((weak)) unsigned int g_hAppMutex;
__attribute__((weak)) unsigned int g_hInstance;
__attribute__((weak)) unsigned int g_hMainWindow;
__attribute__((weak)) unsigned int g_iatCritSecTable;
__attribute__((weak)) unsigned int g_iatPtr;
__attribute__((weak)) unsigned int g_iat_mciSendCommandA;
__attribute__((weak)) unsigned int g_iat_timeEndPeriod;
__attribute__((weak)) unsigned int g_litEightFlag;
__attribute__((weak)) unsigned int g_litNineFlag;
__attribute__((weak)) unsigned int g_litScaledArg4d;
__attribute__((weak)) unsigned int g_litScaledArgd8;
__attribute__((weak)) unsigned int g_lock_0058c874;
__attribute__((weak)) unsigned int g_lock_0058c8f4;
__attribute__((weak)) unsigned int g_logicFrameCounter;
__attribute__((weak)) unsigned int g_logicStepFlag;
__attribute__((weak)) unsigned int g_matrixStackTop;
__attribute__((weak)) unsigned int g_mode4PauseGate;
__attribute__((weak)) unsigned int g_nodeSlotsArea;
__attribute__((weak)) unsigned int g_pendingMatchVar;
__attribute__((weak)) unsigned int g_pendingNodeType;
__attribute__((weak)) unsigned int g_player3NodeIdx;
__attribute__((weak)) unsigned int g_player4NodeIdx;
__attribute__((weak)) unsigned int g_renderer3_surface_active;
__attribute__((weak)) unsigned int g_renderer4_active;
__attribute__((weak)) unsigned int g_renderer5_surface_active;
__attribute__((weak)) unsigned int g_siblingTable;
__attribute__((weak)) unsigned int g_tickFlagF;
__attribute__((weak)) unsigned int g_timerActive;
__attribute__((weak)) unsigned int g_timerEndSec;
__attribute__((weak)) unsigned int g_timerFlag;
__attribute__((weak)) unsigned int g_timerHandle;
__attribute__((weak)) unsigned int g_timerInitedSkip;
__attribute__((weak)) unsigned int g_timerLastNow;
__attribute__((weak)) unsigned int g_timerStartSec;
__attribute__((weak)) unsigned int g_walkCallback;
__attribute__((weak)) unsigned int g_xformDirtyFlags;
__attribute__((weak)) unsigned int g_xformScratch2088;

__attribute__((weak)) int AlarmCountdownInstall(){return 0;}
__attribute__((weak)) int AllocNode(){return 0;}
__attribute__((weak)) int AppInit_Misc2(){return 0;}
__attribute__((weak)) int AudioBridgeMStackChainCopy(){return 0;}
__attribute__((weak)) int AudioMixerStep(){return 0;}
__attribute__((weak)) int AudioShutdownSequence(){return 0;}
__attribute__((weak)) int AudioVolumeRescale(){return 0;}
__attribute__((weak)) int Audio_TimerTick(){return 0;}
__attribute__((weak)) int Audio_UpdateChannels(){return 0;}
__attribute__((weak)) int BitmapBlitRunLength(){return 0;}
__attribute__((weak)) int BootDispatchSlotInit(){return 0;}
__attribute__((weak)) int BootMStackBracket3SubdispatchPair(){return 0;}
__attribute__((weak)) int BootMod6487eClampAndChainMul10(){return 0;}
__attribute__((weak)) int BootScheduledNodeTimerWalk(){return 0;}
__attribute__((weak)) int BootStateInitLongChain(){return 0;}
__attribute__((weak)) int BootStateTriple(){return 0;}
__attribute__((weak)) int ByteWordTableTaggedDispatch(){return 0;}
__attribute__((weak)) int CallPauseDirty1JmpDirty4StackPush_GuardedSeq_GuardedChainCmpDualBitXor_then_ScaledIncCmpJmp(){return 0;}
__attribute__((weak)) int CameraAimSplineDriver(){return 0;}
__attribute__((weak)) int Cascade5StageInit(){return 0;}
__attribute__((weak)) int ChainDirtyBitWalker(){return 0;}
__attribute__((weak)) int ChainNodeInit(){return 0;}
__attribute__((weak)) int ChainSetupBitToggle(){return 0;}
__attribute__((weak)) int ChainSlotSetupInstallSelf(){return 0;}
__attribute__((weak)) int ChainTableWalkStore(){return 0;}
__attribute__((weak)) int CharSelectFsmCluster(){return 0;}
__attribute__((weak)) int CjTableThresholdDispatch(){return 0;}
__attribute__((weak)) int CloseHandle(){return 0;}
__attribute__((weak)) int Config_SaveToRegistry(){return 0;}
__attribute__((weak)) int CountdownClampWalk(){return 0;}
__attribute__((weak)) int CrtHeapCommitFreeCluster(){return 0;}
__attribute__((weak)) int DDraw3_CreateSurface(){return 0;}
__attribute__((weak)) int DDraw5_CreateSurface(){return 0;}
__attribute__((weak)) int DSoundBufferInit146_a60(){return 0;}
__attribute__((weak)) int DSoundBufferInit146_b290(){return 0;}
__attribute__((weak)) int Dirty4Branch_MStackPushDual_StackPop_00428390(){return 0;}
__attribute__((weak)) int DirtyDoubleDeref(){return 0;}
__attribute__((weak)) int DirtyToggleByGate(){return 0;}
__attribute__((weak)) int Distance3DMul10Chain(){return 0;}
__attribute__((weak)) int DualMul10Tail(){return 0;}
__attribute__((weak)) int DualPushCmp12Dispatch(){return 0;}
__attribute__((weak)) int DualPushCmp12Dispatch68(){return 0;}
__attribute__((weak)) int DualSeqLoopDispatch(){return 0;}
__attribute__((weak)) int DualSetShiftCall(){return 0;}
__attribute__((weak)) int EsiInstallChainCallIndirect(){return 0;}
__attribute__((weak)) int FCloseImpl(){return 0;}
__attribute__((weak)) int FightFrameStep_Inner(){return 0;}
__attribute__((weak)) int FiveTableInitChainBracketed(){return 0;}
__attribute__((weak)) int FlushDrawQueue(){return 0;}
__attribute__((weak)) int GameModeHandlerCluster(){return 0;}
__attribute__((weak)) int GameStateMachine(){return 0;}
__attribute__((weak)) int GuardedChainCmpDualBitXor(){return 0;}
__attribute__((weak)) int GuardedChainPushSetCallPop(){return 0;}
__attribute__((weak)) int GuardedDualAndFlagToggle(){return 0;}
__attribute__((weak)) int GuardedLoopWithCallback_Callback_004284c0(){return 0;}
__attribute__((weak)) int HalveChainTriplePop2(){return 0;}
__attribute__((weak)) int HeapRegionLookup(){return 0;}
__attribute__((weak)) int Helper_ECM_PostCleanup(){return 0;}
__attribute__((weak)) int Helper_GSM_PlayMusic(){return 0;}
__attribute__((weak)) int Helper_PerPlayerTick(){return 0;}
__attribute__((weak)) int Helper_TickFrame_Misc(){return 0;}
__attribute__((weak)) int HitReactionDispatcher(){return 0;}
__attribute__((weak)) int Input_TickPlayers(){return 0;}
__attribute__((weak)) int LinkedListInsert(){return 0;}
__attribute__((weak)) int InstallSelfChainSet2011(){return 0;}
__attribute__((weak)) int InstallSelfChainSetB333(){return 0;}
__attribute__((weak)) int InstallSelfMStackIndirect(){return 0;}
__attribute__((weak)) int InstallSelfThreeStateDispatch(){return 0;}
__attribute__((weak)) int InstallSelfTwoTailJmp(){return 0;}
__attribute__((weak)) int LinkedListBitMaskSearch(){return 0;}
__attribute__((weak)) int LoadGeoAsset_Default(){return 0;}
__attribute__((weak)) int Lock(){return 0;}
__attribute__((weak)) int MStackBracket7_DispatchAndChain(){return 0;}
__attribute__((weak)) int MStackPushZeroCallPop(){return 0;}
__attribute__((weak)) int PendingMatch_00407d50(){return 0;}
__attribute__((weak)) int MStackBracket5_LinkedListUnlink(){return 0;}
__attribute__((weak)) int PvsMergeDriver(){return 0;}
__attribute__((weak)) int MStackChainInstallDispatch(){return 0;}
__attribute__((weak)) int MStackNegAwareMul10Pair(){return 0;}
__attribute__((weak)) int MStackPush2ChainLLInsert(){return 0;}
__attribute__((weak)) int MStackPush2ChainPrepend(){return 0;}
__attribute__((weak)) int MStackPush2CjMul10Triple(){return 0;}
__attribute__((weak)) int MStackPush2DirtyCall(){return 0;}
__attribute__((weak)) int MStackPush2RunCountdown(){return 0;}
__attribute__((weak)) int MStackPush3CmpCall(){return 0;}
__attribute__((weak)) int MStackPush4IndirectCall(){return 0;}
__attribute__((weak)) int MStackPushTwoEntryChainCall(){return 0;}
__attribute__((weak)) int MStackPushVec3Mul10(){return 0;}
__attribute__((weak)) int MoveSelectorCluster(){return 0;}
__attribute__((weak)) int MstackPopScaledChainPlusThunks(){return 0;}
__attribute__((weak)) int Mul10ThresholdQuad(){return 0;}
__attribute__((weak)) int NodeUnlink(){return 0;}
__attribute__((weak)) int PackedListVisitor(){return 0;}
__attribute__((weak)) int PendingMatch_00459510(){return 0;}
__attribute__((weak)) int PendingMatch_CallPauseScaledStoreCopyJmp(){return 0;}
__attribute__((weak)) int PendingMatch_LeaPlus22StoreSelf(){return 0;}
__attribute__((weak)) int PendingMatch_MStackPush2RunCountdown_0044baa0(){return 0;}
__attribute__((weak)) int Phase3InstallTableCheck(){return 0;}
__attribute__((weak)) int Phase4SevenPackedDispatch(){return 0;}
__attribute__((weak)) int PhaseInstall2DInterpDispatch(){return 0;}
__attribute__((weak)) int PoseCopyIdleCluster(){return 0;}
__attribute__((weak)) int PreFightInstallCluster(){return 0;}
__attribute__((weak)) int PrefixThunkInstallSelf3State(){return 0;}
__attribute__((weak)) int PushSetCallCleanup(){return 0;}
__attribute__((weak)) int QuadMul10TailFpuChain(){return 0;}
__attribute__((weak)) int R2_Cleanup(){return 0;}
__attribute__((weak)) int RangePathIATDispatch_Lock(){return 0;}
__attribute__((weak)) int RangePathIATDispatch_TableLookupIatCall(){return 0;}
__attribute__((weak)) int Renderer1_EndScene_Glide(){return 0;}
__attribute__((weak)) int Renderer2_EndScene_D3D(){return 0;}
__attribute__((weak)) int Renderer3_EndScene_SW_FS(){return 0;}
__attribute__((weak)) int Renderer4_EndScene_SW_Win(){return 0;}
__attribute__((weak)) int Renderer5_EndScene_SW_FS_Hi(){return 0;}
__attribute__((weak)) int RoundTextMenuEventCluster(){return 0;}
__attribute__((weak)) int ScaledSubStore(){return 0;}
__attribute__((weak)) int SelfInstallPhaseDispatch_StackPopDispatchTagged(){return 0;}
__attribute__((weak)) int SendNotifyMessageA(){return 0;}
__attribute__((weak)) int SixSubdispatchSpan(){return 0;}
__attribute__((weak)) int SlotCmp3way(){return 0;}
__attribute__((weak)) int StateDispatchTable(){return 0;}
__attribute__((weak)) int StateDispatchYield(){return 0;}
__attribute__((weak)) int StateGateMStackOverlap(){return 0;}
__attribute__((weak)) int StructArrayWalkCondCall(){return 0;}
__attribute__((weak)) int TaggedSceneDispatch(){return 0;}
__attribute__((weak)) int TickAllEntities(){return 0;}
__attribute__((weak)) int TripleBlockChainScaledInits(){return 0;}
__attribute__((weak)) int TryInitRenderer(){return 0;}
__attribute__((weak)) int TwoStageSetupTripleCopy(){return 0;}
__attribute__((weak)) int WalkCallbackSetClearDirty(){return 0;}
__attribute__((weak)) int func_00409970_ii(){return 0;}
__attribute__((weak)) int func_0041f780_z(){return 0;}
__attribute__((weak)) int func_004602b0_pp(){return 0;}
__attribute__((weak)) int func_004740d0_z(){return 0;}
__attribute__((weak)) int func_004740d0_zz(){return 0;}
__attribute__((weak)) int func_00476e90(){return 0;}
__attribute__((weak)) int func_0x00474b10(){return 0;}
__attribute__((weak)) int ExitGame(){return 0;}
__attribute__((weak)) int FpuSqrtMul(){return 0;}
__attribute__((weak)) int DualInstallCallSwap_CjChainResetThreshold_then_CjChainResetThreshold(){return 0;}
__attribute__((weak)) int DualInstallCallSwap_SqDistThresholdRevertAdvance_then_SqDistThresholdRevertAdvance(){return 0;}
__attribute__((weak)) int FixedDiv16(){return 0;}
__attribute__((weak)) int GatedScaledSubSat(){return 0;}
__attribute__((weak)) int GeoTransformDispatchAndApply(){return 0;}
__attribute__((weak)) int MStackFrameCdeclDouble(){return 0;}
__attribute__((weak)) int NineEntryFlagDispatch(){return 0;}
__attribute__((weak)) int ScaledStateNegCallPauseLoad(){return 0;}
__attribute__((weak)) int StateSnapshotDispatch(){return 0;}
__attribute__((weak)) unsigned int g_eventQueueSeed;
__attribute__((weak)) int DualScaledStore(){return 0;}
__attribute__((weak)) int ECM_DecodeFrame_Huffman(){return 0;}
__attribute__((weak)) int Helper_PreTick(){return 0;}
__attribute__((weak)) int Helper_TickReinit(){return 0;}
__attribute__((weak)) int RenderSceneGraphIterate(){return 0;}
__attribute__((weak)) int Audio_PlaySoundId(){return 0;}
__attribute__((weak)) int DrawMenu(){return 0;}
__attribute__((weak)) int Helper_AudioRelease(){return 0;}
__attribute__((weak)) int Helper_GSM_Config(){return 0;}
__attribute__((weak)) int Helper_GSM_HandleEvent(){return 0;}
__attribute__((weak)) int Helper_GSM_Options(){return 0;}
__attribute__((weak)) int Helper_GSM_Practice(){return 0;}
__attribute__((weak)) int Helper_GSM_Tournament(){return 0;}
__attribute__((weak)) int Helper_GSM_VS(){return 0;}
__attribute__((weak)) int Helper_TitleAudioReset(){return 0;}
__attribute__((weak)) int Menu_ColorDepthErrorDialog(){return 0;}
__attribute__((weak)) int Menu_Direct3DUnavailableDialog(){return 0;}
__attribute__((weak)) int Menu_DirectDrawUnavailableDialog(){return 0;}
__attribute__((weak)) int Menu_GlideUnavailableDialog(){return 0;}
__attribute__((weak)) int Menu_HelpScreen(){return 0;}
__attribute__((weak)) int Menu_InsertCDDialog(){return 0;}
__attribute__((weak)) int GDispatch4(){return 0;}
__attribute__((weak)) int DispatcherComplex260_FramePauseScaledStore(){return 0;}
__attribute__((weak)) int Loop16Init(){return 0;}
__attribute__((weak)) int TwinRecordIter(){return 0;}
__attribute__((weak)) int TableSearch(){return 0;}
__attribute__((weak)) int StoreTwoCall(){return 0;}
__attribute__((weak)) int SixDoublePushCall(){return 0;}
__attribute__((weak)) int Audio_TimerSet(){return 0;}
__attribute__((weak)) int SunbeamSpriteEmit(){return 0;}
__attribute__((weak)) int GamepadSeqRecord(){return 0;}
__attribute__((weak)) int Menu_PauseMenu(){return 0;}
__attribute__((weak)) int Helper_DrawMenu_PostRender(){return 0;}
__attribute__((weak)) int AppInit_Misc8(){return 0;}
__attribute__((weak)) int GlobalsResetInit(){return 0;}
__attribute__((weak)) int PendingMatch_004c9df0(){return 0;}
__attribute__((weak)) int SentinelInitTripleCall(){return 0;}
__attribute__((weak)) int Anim_LoadPackFile(){return 0;}
__attribute__((weak)) int Init0AndMax(){return 0;}
__attribute__((weak)) int CameraSetupAndCullFan(){return 0;}
__attribute__((weak)) int ChainStreamMatMulVecAdd(){return 0;}
__attribute__((weak)) int ChainWalkCleanup(){return 0;}
__attribute__((weak)) int ScaledNegThreeWords(){return 0;}
__attribute__((weak)) int RenderSceneNode(){return 0;}
__attribute__((weak)) int MatrixTransform3x3Q12(){return 0;}
__attribute__((weak)) int BboxProjectAndStash(){return 0;}
__attribute__((weak)) int BillboardChainRender(){return 0;}
__attribute__((weak)) int BillboardSheetDualEmit(){return 0;}
__attribute__((weak)) int DirtyBitTripleWriteOrCall(){return 0;}
__attribute__((weak)) int DirtyTestScaledCopy(){return 0;}
__attribute__((weak)) int LeaScaledCall(){return 0;}
__attribute__((weak)) int MStackPushCallCallPop_func_00405dd0(){return 0;}
__attribute__((weak)) int MovesPanelEmit(){return 0;}
__attribute__((weak)) int TransformAccumulate(){return 0;}
__attribute__((weak)) int TristripBatchEmit2(){return 0;}
__attribute__((weak)) int VertexQuadBuilder(){return 0;}
__attribute__((weak)) int VibrationFrameUpdate(){return 0;}
__attribute__((weak)) int VtableDispatchSetDirty(){return 0;}
__attribute__((weak)) int WtSnapshotPushCall(){return 0;}
__attribute__((weak)) int ZBucketClampStore(){return 0;}
__attribute__((weak)) int BootChainBidirRecurseWalk(){return 0;}
__attribute__((weak)) int CleanupCallTwice(){return 0;}
__attribute__((weak)) int MStackBracket2_TreeWalkRecursive(){return 0;}
__attribute__((weak)) int func_00405A40(){return 0;}
__attribute__((weak)) int VertexSlotInitFlagWalk(){return 0;}
__attribute__((weak)) int MStackPushCallCallPop_func_00405e20(){return 0;}
__attribute__((weak)) int PushPopScaled1cDoubleCall(){return 0;}
__attribute__((weak)) int ScaledTestPauseStore(){return 0;}
__attribute__((weak)) int ScaledLoadCallSet1c(){return 0;}
__attribute__((weak)) int MStackBracket2InitChainSplitInsert(){return 0;}
#endif /* MK4_NATIVE_FULL */
