/* GENERATED (grow_native.py frontier). Weak stub frontier for native-full:
 * functions return 0; globals not covered by native_globals.h are 4-byte
 * placeholders. All weak, gated by MK4_NATIVE_FULL. The native-port work-list. */

#ifdef MK4_NATIVE_FULL
extern void MK4_StubHit(const char *);
__attribute__((weak)) unsigned int g_dispatchSave1161;
__attribute__((weak)) unsigned int g_audioPreState;
__attribute__((weak)) unsigned int g_audioRestoreSlot3;
__attribute__((weak)) unsigned int g_audioState00;
__attribute__((weak)) unsigned int g_audioState08;
__attribute__((weak)) unsigned int g_audioStreamState;
__attribute__((weak)) unsigned int g_auxChannels;
__attribute__((weak)) unsigned int g_auxCount;
__attribute__((weak)) unsigned int g_bootInitSaveSlot;
__attribute__((weak)) unsigned int g_clampedRendererMode;
__attribute__((weak)) unsigned int g_comptr_0058c7c0;
__attribute__((weak)) unsigned int g_comptr_0058c860;
__attribute__((weak)) unsigned int g_comptr_0058c864;
__attribute__((weak)) unsigned int g_comptr_0058c868;
__attribute__((weak)) unsigned int g_comptr_0058c870;
__attribute__((weak)) unsigned int g_comptr_0058c8e0;
__attribute__((weak)) unsigned int g_comptr_0058c8e4;
__attribute__((weak)) unsigned int g_comptr_0058c8e8;
__attribute__((weak)) unsigned int g_comptr_0058c8f0;
__attribute__((weak)) unsigned int g_currentNodeFlags;
__attribute__((weak)) unsigned int g_currentRendererMode;
__attribute__((weak)) unsigned int g_dispatchSave1163;
__attribute__((weak)) unsigned int g_dispatchSave1164;
__attribute__((weak)) unsigned int g_dispatchSave1314;
__attribute__((weak)) unsigned int g_drawSceneTimeMs;
__attribute__((weak)) unsigned int g_dsoundContext;
__attribute__((weak)) unsigned int g_ecmReserved;
__attribute__((weak)) unsigned int g_eq;
__attribute__((weak)) unsigned int g_eventQueueActive;
__attribute__((weak)) unsigned int g_eventQueueChild;
__attribute__((weak)) unsigned int g_eventQueueCurrent;
__attribute__((weak)) unsigned int g_eventQueueDrainBase;
__attribute__((weak)) unsigned int g_eventQueueEnd;
__attribute__((weak)) unsigned int g_eventQueueHead;
__attribute__((weak)) unsigned int g_eventQueueIdx;
__attribute__((weak)) unsigned int g_eventQueueNotMask;
__attribute__((weak)) unsigned int g_eventQueuePending;
__attribute__((weak)) unsigned int g_eventQueueTotal;
__attribute__((weak)) unsigned int g_eventQueueWorkType;
__attribute__((weak)) unsigned int g_fightGroupHead;
__attribute__((weak)) unsigned int g_fightGroupHeads;
__attribute__((weak)) unsigned int g_fightTableA0;
__attribute__((weak)) unsigned int g_fightTableA1;
__attribute__((weak)) unsigned int g_fightTableA2;
__attribute__((weak)) unsigned int g_fightTableB0;
__attribute__((weak)) unsigned int g_fightTableB1;
__attribute__((weak)) unsigned int g_fightTableB2;
__attribute__((weak)) unsigned int g_fightTableC0;
__attribute__((weak)) unsigned int g_fightTableC1;
__attribute__((weak)) unsigned int g_fightTableC2;
__attribute__((weak)) unsigned int g_frameCounter;
__attribute__((weak)) unsigned int g_framePauseFlag;
__attribute__((weak)) unsigned int g_fsys_archive;
__attribute__((weak)) unsigned int g_gameMode;
__attribute__((weak)) unsigned int g_gameStateResult;
__attribute__((weak)) unsigned int g_gtAxisX;
__attribute__((weak)) unsigned int g_gtAxisY;
__attribute__((weak)) unsigned int g_gtAxisZ;
__attribute__((weak)) unsigned int g_gtConfig4f;
__attribute__((weak)) unsigned int g_gtFightTickCounter;
__attribute__((weak)) unsigned int g_gtModeFlag;
__attribute__((weak)) unsigned int g_gtOtherFlag;
__attribute__((weak)) unsigned int g_gtPauseMode;
__attribute__((weak)) unsigned int g_gtPlayerEnabled;
__attribute__((weak)) unsigned int g_gtPlayerProbe1;
__attribute__((weak)) unsigned int g_gtPlayerProbe2;
__attribute__((weak)) unsigned int g_gtState438;
__attribute__((weak)) unsigned int g_hAppMutex;
__attribute__((weak)) unsigned int g_hInstance;
__attribute__((weak)) unsigned int g_hMainWindow;
__attribute__((weak)) unsigned int g_iatCritSecTable;
__attribute__((weak)) unsigned int g_iatPtr;
__attribute__((weak)) unsigned int g_iat_mciSendCommandA;
__attribute__((weak)) unsigned int g_iat_timeEndPeriod;
__attribute__((weak)) unsigned int g_litEightFlag;
__attribute__((weak)) unsigned int g_litNineFlag;
__attribute__((weak)) unsigned int g_litScaledArg4d;
__attribute__((weak)) unsigned int g_litScaledArgd8;
__attribute__((weak)) unsigned int g_lock_0058c874;
__attribute__((weak)) unsigned int g_lock_0058c8f4;
__attribute__((weak)) unsigned int g_logicFrameCounter;
__attribute__((weak)) unsigned int g_logicStepFlag;
__attribute__((weak)) unsigned int g_matrixStackTop;
__attribute__((weak)) unsigned int g_mode4PauseGate;
__attribute__((weak)) unsigned int g_nodeSlotsArea;
__attribute__((weak)) unsigned int g_pendingMatchVar;
__attribute__((weak)) unsigned int g_pendingNodeType;
__attribute__((weak)) unsigned int g_player3NodeIdx;
__attribute__((weak)) unsigned int g_player4NodeIdx;
__attribute__((weak)) unsigned int g_renderer3_surface_active;
__attribute__((weak)) unsigned int g_renderer4_active;
__attribute__((weak)) unsigned int g_renderer5_surface_active;
__attribute__((weak)) unsigned int g_siblingTable;
__attribute__((weak)) unsigned int g_tickFlagF;
__attribute__((weak)) unsigned int g_timerActive;
__attribute__((weak)) unsigned int g_timerEndSec;
__attribute__((weak)) unsigned int g_timerFlag;
__attribute__((weak)) unsigned int g_timerHandle;
__attribute__((weak)) unsigned int g_timerInitedSkip;
__attribute__((weak)) unsigned int g_timerLastNow;
__attribute__((weak)) unsigned int g_timerStartSec;
__attribute__((weak)) unsigned int g_walkCallback;
__attribute__((weak)) unsigned int g_xformDirtyFlags;
__attribute__((weak)) unsigned int g_xformScratch2088;

__attribute__((weak)) int AlarmCountdownInstall(){MK4_StubHit("AlarmCountdownInstall");return 0;}
__attribute__((weak)) int AllocNode(){MK4_StubHit("AllocNode");return 0;}
__attribute__((weak)) int AppInit_Misc2(){MK4_StubHit("AppInit_Misc2");return 0;}
__attribute__((weak)) int AudioBridgeMStackChainCopy(){MK4_StubHit("AudioBridgeMStackChainCopy");return 0;}
__attribute__((weak)) int AudioMixerStep(){MK4_StubHit("AudioMixerStep");return 0;}
__attribute__((weak)) int AudioShutdownSequence(){MK4_StubHit("AudioShutdownSequence");return 0;}
__attribute__((weak)) int AudioVolumeRescale(){MK4_StubHit("AudioVolumeRescale");return 0;}
__attribute__((weak)) int Audio_TimerTick(){MK4_StubHit("Audio_TimerTick");return 0;}
__attribute__((weak)) int Audio_UpdateChannels(){MK4_StubHit("Audio_UpdateChannels");return 0;}
__attribute__((weak)) int BitmapBlitRunLength(){MK4_StubHit("BitmapBlitRunLength");return 0;}
__attribute__((weak)) int BootDispatchSlotInit(){MK4_StubHit("BootDispatchSlotInit");return 0;}
__attribute__((weak)) int BootMod6487eClampAndChainMul10(){MK4_StubHit("BootMod6487eClampAndChainMul10");return 0;}
__attribute__((weak)) int BootScheduledNodeTimerWalk(){MK4_StubHit("BootScheduledNodeTimerWalk");return 0;}
__attribute__((weak)) int BootStateInitLongChain(){MK4_StubHit("BootStateInitLongChain");return 0;}
__attribute__((weak)) int BootStateTriple(){MK4_StubHit("BootStateTriple");return 0;}
__attribute__((weak)) int ByteWordTableTaggedDispatch(){MK4_StubHit("ByteWordTableTaggedDispatch");return 0;}
__attribute__((weak)) int CallPauseDirty1JmpDirty4StackPush_GuardedSeq_GuardedChainCmpDualBitXor_then_ScaledIncCmpJmp(){MK4_StubHit("CallPauseDirty1JmpDirty4StackPush_GuardedSeq_GuardedChainCmpDualBitXor_then_ScaledIncCmpJmp");return 0;}
__attribute__((weak)) int CameraAimSplineDriver(){MK4_StubHit("CameraAimSplineDriver");return 0;}
__attribute__((weak)) int Cascade5StageInit(){MK4_StubHit("Cascade5StageInit");return 0;}
__attribute__((weak)) int ChainNodeInit(){MK4_StubHit("ChainNodeInit");return 0;}
__attribute__((weak)) int ChainSlotSetupInstallSelf(){MK4_StubHit("ChainSlotSetupInstallSelf");return 0;}
__attribute__((weak)) int ChainTableWalkStore(){MK4_StubHit("ChainTableWalkStore");return 0;}
__attribute__((weak)) int CharSelectFsmCluster(){MK4_StubHit("CharSelectFsmCluster");return 0;}
__attribute__((weak)) int CjTableThresholdDispatch(){MK4_StubHit("CjTableThresholdDispatch");return 0;}
__attribute__((weak)) int CloseHandle(){MK4_StubHit("CloseHandle");return 0;}
__attribute__((weak)) int Config_SaveToRegistry(){MK4_StubHit("Config_SaveToRegistry");return 0;}
__attribute__((weak)) int CountdownClampWalk(){MK4_StubHit("CountdownClampWalk");return 0;}
__attribute__((weak)) int CrtHeapCommitFreeCluster(){MK4_StubHit("CrtHeapCommitFreeCluster");return 0;}
__attribute__((weak)) int DDraw3_CreateSurface(){MK4_StubHit("DDraw3_CreateSurface");return 0;}
__attribute__((weak)) int DDraw5_CreateSurface(){MK4_StubHit("DDraw5_CreateSurface");return 0;}
__attribute__((weak)) int DSoundBufferInit146_a60(){MK4_StubHit("DSoundBufferInit146_a60");return 0;}
__attribute__((weak)) int DSoundBufferInit146_b290(){MK4_StubHit("DSoundBufferInit146_b290");return 0;}
__attribute__((weak)) int Dirty4Branch_MStackPushDual_StackPop_00428390(){MK4_StubHit("Dirty4Branch_MStackPushDual_StackPop_00428390");return 0;}
__attribute__((weak)) int DirtyDoubleDeref(){MK4_StubHit("DirtyDoubleDeref");return 0;}
__attribute__((weak)) int DirtyToggleByGate(){MK4_StubHit("DirtyToggleByGate");return 0;}
__attribute__((weak)) int Distance3DMul10Chain(){MK4_StubHit("Distance3DMul10Chain");return 0;}
__attribute__((weak)) int DualMul10Tail(){MK4_StubHit("DualMul10Tail");return 0;}
__attribute__((weak)) int DualPushCmp12Dispatch(){MK4_StubHit("DualPushCmp12Dispatch");return 0;}
__attribute__((weak)) int DualPushCmp12Dispatch68(){MK4_StubHit("DualPushCmp12Dispatch68");return 0;}
__attribute__((weak)) int DualSeqLoopDispatch(){MK4_StubHit("DualSeqLoopDispatch");return 0;}
__attribute__((weak)) int DualSetShiftCall(){MK4_StubHit("DualSetShiftCall");return 0;}
__attribute__((weak)) int EsiInstallChainCallIndirect(){MK4_StubHit("EsiInstallChainCallIndirect");return 0;}
__attribute__((weak)) int FCloseImpl(){MK4_StubHit("FCloseImpl");return 0;}
__attribute__((weak)) int FightFrameStep_Inner(){MK4_StubHit("FightFrameStep_Inner");return 0;}
__attribute__((weak)) int FiveTableInitChainBracketed(){MK4_StubHit("FiveTableInitChainBracketed");return 0;}
__attribute__((weak)) int FlushDrawQueue(){MK4_StubHit("FlushDrawQueue");return 0;}
__attribute__((weak)) int GameModeHandlerCluster(){MK4_StubHit("GameModeHandlerCluster");return 0;}
__attribute__((weak)) int GameStateMachine(){MK4_StubHit("GameStateMachine");return 0;}
__attribute__((weak)) int GuardedChainPushSetCallPop(){MK4_StubHit("GuardedChainPushSetCallPop");return 0;}
__attribute__((weak)) int GuardedLoopWithCallback_Callback_004284c0(){MK4_StubHit("GuardedLoopWithCallback_Callback_004284c0");return 0;}
__attribute__((weak)) int HalveChainTriplePop2(){MK4_StubHit("HalveChainTriplePop2");return 0;}
__attribute__((weak)) int HeapRegionLookup(){MK4_StubHit("HeapRegionLookup");return 0;}
__attribute__((weak)) int Helper_ECM_PostCleanup(){MK4_StubHit("Helper_ECM_PostCleanup");return 0;}
__attribute__((weak)) int Helper_GSM_PlayMusic(){MK4_StubHit("Helper_GSM_PlayMusic");return 0;}
__attribute__((weak)) int Helper_PerPlayerTick(){MK4_StubHit("Helper_PerPlayerTick");return 0;}
__attribute__((weak)) int Helper_TickFrame_Misc(){MK4_StubHit("Helper_TickFrame_Misc");return 0;}
__attribute__((weak)) int HitReactionDispatcher(){MK4_StubHit("HitReactionDispatcher");return 0;}
__attribute__((weak)) int LinkedListInsert(){MK4_StubHit("LinkedListInsert");return 0;}
__attribute__((weak)) int InstallSelfChainSet2011(){MK4_StubHit("InstallSelfChainSet2011");return 0;}
__attribute__((weak)) int InstallSelfChainSetB333(){MK4_StubHit("InstallSelfChainSetB333");return 0;}
__attribute__((weak)) int InstallSelfMStackIndirect(){MK4_StubHit("InstallSelfMStackIndirect");return 0;}
__attribute__((weak)) int InstallSelfThreeStateDispatch(){MK4_StubHit("InstallSelfThreeStateDispatch");return 0;}
__attribute__((weak)) int InstallSelfTwoTailJmp(){MK4_StubHit("InstallSelfTwoTailJmp");return 0;}
__attribute__((weak)) int LinkedListBitMaskSearch(){MK4_StubHit("LinkedListBitMaskSearch");return 0;}
__attribute__((weak)) int LoadGeoAsset_Default(){MK4_StubHit("LoadGeoAsset_Default");return 0;}
__attribute__((weak)) int Lock(){MK4_StubHit("Lock");return 0;}
__attribute__((weak)) int MStackBracket7_DispatchAndChain(){MK4_StubHit("MStackBracket7_DispatchAndChain");return 0;}
__attribute__((weak)) int MStackPushZeroCallPop(){MK4_StubHit("MStackPushZeroCallPop");return 0;}
__attribute__((weak)) int PendingMatch_00407d50(){MK4_StubHit("PendingMatch_00407d50");return 0;}
__attribute__((weak)) int MStackBracket5_LinkedListUnlink(){MK4_StubHit("MStackBracket5_LinkedListUnlink");return 0;}
__attribute__((weak)) int PvsMergeDriver(){MK4_StubHit("PvsMergeDriver");return 0;}
__attribute__((weak)) int MStackChainInstallDispatch(){MK4_StubHit("MStackChainInstallDispatch");return 0;}
__attribute__((weak)) int MStackNegAwareMul10Pair(){MK4_StubHit("MStackNegAwareMul10Pair");return 0;}
__attribute__((weak)) int MStackPush2ChainLLInsert(){MK4_StubHit("MStackPush2ChainLLInsert");return 0;}
__attribute__((weak)) int MStackPush2ChainPrepend(){MK4_StubHit("MStackPush2ChainPrepend");return 0;}
__attribute__((weak)) int MStackPush2CjMul10Triple(){MK4_StubHit("MStackPush2CjMul10Triple");return 0;}
__attribute__((weak)) int MStackPush2RunCountdown(){MK4_StubHit("MStackPush2RunCountdown");return 0;}
__attribute__((weak)) int MStackPush3CmpCall(){MK4_StubHit("MStackPush3CmpCall");return 0;}
__attribute__((weak)) int MStackPush4IndirectCall(){MK4_StubHit("MStackPush4IndirectCall");return 0;}
__attribute__((weak)) int MStackPushVec3Mul10(){MK4_StubHit("MStackPushVec3Mul10");return 0;}
__attribute__((weak)) int MoveSelectorCluster(){MK4_StubHit("MoveSelectorCluster");return 0;}
__attribute__((weak)) int MstackPopScaledChainPlusThunks(){MK4_StubHit("MstackPopScaledChainPlusThunks");return 0;}
__attribute__((weak)) int Mul10ThresholdQuad(){MK4_StubHit("Mul10ThresholdQuad");return 0;}
__attribute__((weak)) int NodeUnlink(){MK4_StubHit("NodeUnlink");return 0;}
__attribute__((weak)) int PackedListVisitor(){MK4_StubHit("PackedListVisitor");return 0;}
__attribute__((weak)) int PendingMatch_CallPauseScaledStoreCopyJmp(){MK4_StubHit("PendingMatch_CallPauseScaledStoreCopyJmp");return 0;}
__attribute__((weak)) int PendingMatch_LeaPlus22StoreSelf(){MK4_StubHit("PendingMatch_LeaPlus22StoreSelf");return 0;}
__attribute__((weak)) int PendingMatch_MStackPush2RunCountdown_0044baa0(){MK4_StubHit("PendingMatch_MStackPush2RunCountdown_0044baa0");return 0;}
__attribute__((weak)) int Phase3InstallTableCheck(){MK4_StubHit("Phase3InstallTableCheck");return 0;}
__attribute__((weak)) int Phase4SevenPackedDispatch(){MK4_StubHit("Phase4SevenPackedDispatch");return 0;}
__attribute__((weak)) int PoseCopyIdleCluster(){MK4_StubHit("PoseCopyIdleCluster");return 0;}
__attribute__((weak)) int PreFightInstallCluster(){MK4_StubHit("PreFightInstallCluster");return 0;}
__attribute__((weak)) int PrefixThunkInstallSelf3State(){MK4_StubHit("PrefixThunkInstallSelf3State");return 0;}
__attribute__((weak)) int PushSetCallCleanup(){MK4_StubHit("PushSetCallCleanup");return 0;}
__attribute__((weak)) int QuadMul10TailFpuChain(){MK4_StubHit("QuadMul10TailFpuChain");return 0;}
__attribute__((weak)) int R2_Cleanup(){MK4_StubHit("R2_Cleanup");return 0;}
__attribute__((weak)) int RangePathIATDispatch_Lock(){MK4_StubHit("RangePathIATDispatch_Lock");return 0;}
__attribute__((weak)) int RangePathIATDispatch_TableLookupIatCall(){MK4_StubHit("RangePathIATDispatch_TableLookupIatCall");return 0;}
__attribute__((weak)) int Renderer1_EndScene_Glide(){MK4_StubHit("Renderer1_EndScene_Glide");return 0;}
__attribute__((weak)) int Renderer2_EndScene_D3D(){MK4_StubHit("Renderer2_EndScene_D3D");return 0;}
__attribute__((weak)) int Renderer3_EndScene_SW_FS(){MK4_StubHit("Renderer3_EndScene_SW_FS");return 0;}
__attribute__((weak)) int Renderer4_EndScene_SW_Win(){MK4_StubHit("Renderer4_EndScene_SW_Win");return 0;}
__attribute__((weak)) int Renderer5_EndScene_SW_FS_Hi(){MK4_StubHit("Renderer5_EndScene_SW_FS_Hi");return 0;}
__attribute__((weak)) int RoundTextMenuEventCluster(){MK4_StubHit("RoundTextMenuEventCluster");return 0;}
__attribute__((weak)) int ScaledSubStore(){MK4_StubHit("ScaledSubStore");return 0;}
__attribute__((weak)) int SelfInstallPhaseDispatch_StackPopDispatchTagged(){MK4_StubHit("SelfInstallPhaseDispatch_StackPopDispatchTagged");return 0;}
__attribute__((weak)) int SendNotifyMessageA(){MK4_StubHit("SendNotifyMessageA");return 0;}
__attribute__((weak)) int SixSubdispatchSpan(){MK4_StubHit("SixSubdispatchSpan");return 0;}
__attribute__((weak)) int SlotCmp3way(){MK4_StubHit("SlotCmp3way");return 0;}
__attribute__((weak)) int StateDispatchYield(){MK4_StubHit("StateDispatchYield");return 0;}
__attribute__((weak)) int StateGateMStackOverlap(){MK4_StubHit("StateGateMStackOverlap");return 0;}
__attribute__((weak)) int StructArrayWalkCondCall(){MK4_StubHit("StructArrayWalkCondCall");return 0;}
__attribute__((weak)) int TaggedSceneDispatch(){MK4_StubHit("TaggedSceneDispatch");return 0;}
__attribute__((weak)) int TickAllEntities(){MK4_StubHit("TickAllEntities");return 0;}
__attribute__((weak)) int TripleBlockChainScaledInits(){MK4_StubHit("TripleBlockChainScaledInits");return 0;}
__attribute__((weak)) int TryInitRenderer(){MK4_StubHit("TryInitRenderer");return 0;}
__attribute__((weak)) int TwoStageSetupTripleCopy(){MK4_StubHit("TwoStageSetupTripleCopy");return 0;}
__attribute__((weak)) int WalkCallbackSetClearDirty(){MK4_StubHit("WalkCallbackSetClearDirty");return 0;}
__attribute__((weak)) int func_00409970_ii(){MK4_StubHit("func_00409970_ii");return 0;}
__attribute__((weak)) int func_0041f780_z(){MK4_StubHit("func_0041f780_z");return 0;}
__attribute__((weak)) int func_004602b0_pp(){MK4_StubHit("func_004602b0_pp");return 0;}
__attribute__((weak)) int func_004740d0_z(){MK4_StubHit("func_004740d0_z");return 0;}
__attribute__((weak)) int func_004740d0_zz(){MK4_StubHit("func_004740d0_zz");return 0;}
__attribute__((weak)) int func_00476e90(){MK4_StubHit("func_00476e90");return 0;}
__attribute__((weak)) int func_0x00474b10(){MK4_StubHit("func_0x00474b10");return 0;}
__attribute__((weak)) int ExitGame(){MK4_StubHit("ExitGame");return 0;}
__attribute__((weak)) int FpuSqrtMul(){MK4_StubHit("FpuSqrtMul");return 0;}
__attribute__((weak)) int DualInstallCallSwap_CjChainResetThreshold_then_CjChainResetThreshold(){MK4_StubHit("DualInstallCallSwap_CjChainResetThreshold_then_CjChainResetThreshold");return 0;}
__attribute__((weak)) int DualInstallCallSwap_SqDistThresholdRevertAdvance_then_SqDistThresholdRevertAdvance(){MK4_StubHit("DualInstallCallSwap_SqDistThresholdRevertAdvance_then_SqDistThresholdRevertAdvance");return 0;}
__attribute__((weak)) int FixedDiv16(){MK4_StubHit("FixedDiv16");return 0;}
__attribute__((weak)) int GatedScaledSubSat(){MK4_StubHit("GatedScaledSubSat");return 0;}
__attribute__((weak)) int GeoTransformDispatchAndApply(){MK4_StubHit("GeoTransformDispatchAndApply");return 0;}
__attribute__((weak)) int MStackFrameCdeclDouble(){MK4_StubHit("MStackFrameCdeclDouble");return 0;}
__attribute__((weak)) int NineEntryFlagDispatch(){MK4_StubHit("NineEntryFlagDispatch");return 0;}
__attribute__((weak)) int ScaledStateNegCallPauseLoad(){MK4_StubHit("ScaledStateNegCallPauseLoad");return 0;}
__attribute__((weak)) int StateSnapshotDispatch(){MK4_StubHit("StateSnapshotDispatch");return 0;}
__attribute__((weak)) unsigned int g_eventQueueSeed;
__attribute__((weak)) int DualScaledStore(){MK4_StubHit("DualScaledStore");return 0;}
__attribute__((weak)) int ECM_DecodeFrame_Huffman(){MK4_StubHit("ECM_DecodeFrame_Huffman");return 0;}
__attribute__((weak)) int Helper_PreTick(){MK4_StubHit("Helper_PreTick");return 0;}
__attribute__((weak)) int Helper_TickReinit(){MK4_StubHit("Helper_TickReinit");return 0;}
__attribute__((weak)) int RenderSceneGraphIterate(){MK4_StubHit("RenderSceneGraphIterate");return 0;}
__attribute__((weak)) int Audio_PlaySoundId(){MK4_StubHit("Audio_PlaySoundId");return 0;}
__attribute__((weak)) int DrawMenu(){MK4_StubHit("DrawMenu");return 0;}
__attribute__((weak)) int Helper_AudioRelease(){MK4_StubHit("Helper_AudioRelease");return 0;}
__attribute__((weak)) int Helper_GSM_Config(){MK4_StubHit("Helper_GSM_Config");return 0;}
__attribute__((weak)) int Helper_GSM_HandleEvent(){MK4_StubHit("Helper_GSM_HandleEvent");return 0;}
__attribute__((weak)) int Helper_GSM_Options(){MK4_StubHit("Helper_GSM_Options");return 0;}
__attribute__((weak)) int Helper_GSM_Practice(){MK4_StubHit("Helper_GSM_Practice");return 0;}
__attribute__((weak)) int Helper_GSM_Tournament(){MK4_StubHit("Helper_GSM_Tournament");return 0;}
__attribute__((weak)) int Helper_GSM_VS(){MK4_StubHit("Helper_GSM_VS");return 0;}
__attribute__((weak)) int Helper_TitleAudioReset(){MK4_StubHit("Helper_TitleAudioReset");return 0;}
__attribute__((weak)) int Menu_ColorDepthErrorDialog(){MK4_StubHit("Menu_ColorDepthErrorDialog");return 0;}
__attribute__((weak)) int Menu_Direct3DUnavailableDialog(){MK4_StubHit("Menu_Direct3DUnavailableDialog");return 0;}
__attribute__((weak)) int Menu_DirectDrawUnavailableDialog(){MK4_StubHit("Menu_DirectDrawUnavailableDialog");return 0;}
__attribute__((weak)) int Menu_GlideUnavailableDialog(){MK4_StubHit("Menu_GlideUnavailableDialog");return 0;}
__attribute__((weak)) int Menu_HelpScreen(){MK4_StubHit("Menu_HelpScreen");return 0;}
__attribute__((weak)) int Menu_InsertCDDialog(){MK4_StubHit("Menu_InsertCDDialog");return 0;}
__attribute__((weak)) int GDispatch4(){MK4_StubHit("GDispatch4");return 0;}
__attribute__((weak)) int DispatcherComplex260_FramePauseScaledStore(){MK4_StubHit("DispatcherComplex260_FramePauseScaledStore");return 0;}
__attribute__((weak)) int Loop16Init(){MK4_StubHit("Loop16Init");return 0;}
__attribute__((weak)) int StoreTwoCall(){MK4_StubHit("StoreTwoCall");return 0;}
__attribute__((weak)) int Audio_TimerSet(){MK4_StubHit("Audio_TimerSet");return 0;}
__attribute__((weak)) int SunbeamSpriteEmit(){MK4_StubHit("SunbeamSpriteEmit");return 0;}
__attribute__((weak)) int GamepadSeqRecord(){MK4_StubHit("GamepadSeqRecord");return 0;}
__attribute__((weak)) int Menu_PauseMenu(){MK4_StubHit("Menu_PauseMenu");return 0;}
__attribute__((weak)) int Helper_DrawMenu_PostRender(){MK4_StubHit("Helper_DrawMenu_PostRender");return 0;}
__attribute__((weak)) int AppInit_Misc8(){MK4_StubHit("AppInit_Misc8");return 0;}
__attribute__((weak)) int GlobalsResetInit(){MK4_StubHit("GlobalsResetInit");return 0;}
__attribute__((weak)) int PendingMatch_004c9df0(){MK4_StubHit("PendingMatch_004c9df0");return 0;}
__attribute__((weak)) int Anim_LoadPackFile(){MK4_StubHit("Anim_LoadPackFile");return 0;}
__attribute__((weak)) int Init0AndMax(){MK4_StubHit("Init0AndMax");return 0;}
__attribute__((weak)) int CameraSetupAndCullFan(){MK4_StubHit("CameraSetupAndCullFan");return 0;}
__attribute__((weak)) int ChainStreamMatMulVecAdd(){MK4_StubHit("ChainStreamMatMulVecAdd");return 0;}
__attribute__((weak)) int ChainWalkCleanup(){MK4_StubHit("ChainWalkCleanup");return 0;}
__attribute__((weak)) int ScaledNegThreeWords(){MK4_StubHit("ScaledNegThreeWords");return 0;}
__attribute__((weak)) int RenderSceneNode(){MK4_StubHit("RenderSceneNode");return 0;}
__attribute__((weak)) int MatrixTransform3x3Q12(){MK4_StubHit("MatrixTransform3x3Q12");return 0;}
__attribute__((weak)) int BboxProjectAndStash(){MK4_StubHit("BboxProjectAndStash");return 0;}
__attribute__((weak)) int BillboardChainRender(){MK4_StubHit("BillboardChainRender");return 0;}
__attribute__((weak)) int BillboardSheetDualEmit(){MK4_StubHit("BillboardSheetDualEmit");return 0;}
__attribute__((weak)) int DirtyBitTripleWriteOrCall(){MK4_StubHit("DirtyBitTripleWriteOrCall");return 0;}
__attribute__((weak)) int DirtyTestScaledCopy(){MK4_StubHit("DirtyTestScaledCopy");return 0;}
__attribute__((weak)) int LeaScaledCall(){MK4_StubHit("LeaScaledCall");return 0;}
__attribute__((weak)) int MStackPushCallCallPop_func_00405dd0(){MK4_StubHit("MStackPushCallCallPop_func_00405dd0");return 0;}
__attribute__((weak)) int MovesPanelEmit(){MK4_StubHit("MovesPanelEmit");return 0;}
__attribute__((weak)) int TransformAccumulate(){MK4_StubHit("TransformAccumulate");return 0;}
__attribute__((weak)) int TristripBatchEmit2(){MK4_StubHit("TristripBatchEmit2");return 0;}
__attribute__((weak)) int VertexQuadBuilder(){MK4_StubHit("VertexQuadBuilder");return 0;}
__attribute__((weak)) int VibrationFrameUpdate(){MK4_StubHit("VibrationFrameUpdate");return 0;}
__attribute__((weak)) int VtableDispatchSetDirty(){MK4_StubHit("VtableDispatchSetDirty");return 0;}
__attribute__((weak)) int WtSnapshotPushCall(){MK4_StubHit("WtSnapshotPushCall");return 0;}
__attribute__((weak)) int ZBucketClampStore(){MK4_StubHit("ZBucketClampStore");return 0;}
__attribute__((weak)) int BootChainBidirRecurseWalk(){MK4_StubHit("BootChainBidirRecurseWalk");return 0;}
__attribute__((weak)) int CleanupCallTwice(){MK4_StubHit("CleanupCallTwice");return 0;}
__attribute__((weak)) int MStackBracket2_TreeWalkRecursive(){MK4_StubHit("MStackBracket2_TreeWalkRecursive");return 0;}
__attribute__((weak)) int func_00405A40(){MK4_StubHit("func_00405A40");return 0;}
__attribute__((weak)) int MStackPushCallCallPop_func_00405e20(){MK4_StubHit("MStackPushCallCallPop_func_00405e20");return 0;}
__attribute__((weak)) int PushPopScaled1cDoubleCall(){MK4_StubHit("PushPopScaled1cDoubleCall");return 0;}
__attribute__((weak)) int AudioInitSequence(){MK4_StubHit("AudioInitSequence");return 0;}
__attribute__((weak)) int AudioInstallSelfStatePush(){MK4_StubHit("AudioInstallSelfStatePush");return 0;}
__attribute__((weak)) int BootInitGuardedCallChain(){MK4_StubHit("BootInitGuardedCallChain");return 0;}
__attribute__((weak)) int EffectTableWalker(){MK4_StubHit("EffectTableWalker");return 0;}
__attribute__((weak)) int GuardedSetupCallTailJmp(){MK4_StubHit("GuardedSetupCallTailJmp");return 0;}
__attribute__((weak)) int Helper_AudioStop(){MK4_StubHit("Helper_AudioStop");return 0;}
__attribute__((weak)) int InitDispatchersJmp(){MK4_StubHit("InitDispatchersJmp");return 0;}
__attribute__((weak)) int IterFnPtrs(){MK4_StubHit("IterFnPtrs");return 0;}
__attribute__((weak)) int PushPopScaledInit343c(){MK4_StubHit("PushPopScaledInit343c");return 0;}
__attribute__((weak)) int RecordIter170(){MK4_StubHit("RecordIter170");return 0;}
__attribute__((weak)) int TableLookupCall_g_eventTbl_65(){MK4_StubHit("TableLookupCall_g_eventTbl_65");return 0;}
__attribute__((weak)) unsigned int g_dispatchSave547;
__attribute__((weak)) unsigned int g_dispatchSave548;
__attribute__((weak)) unsigned int g_dispatchSave549;
__attribute__((weak)) unsigned int g_dispatchSave550;
__attribute__((weak)) unsigned int g_fnptr_0051ffd8;
__attribute__((weak)) unsigned int g_texAssetIds_ee;
__attribute__((weak)) int PushSetCallPop(){MK4_StubHit("PushSetCallPop");return 0;}
__attribute__((weak)) int Screen_ArcadeEnding(){MK4_StubHit("Screen_ArcadeEnding");return 0;}
__attribute__((weak)) int Input_PollPlayerJoystick(){MK4_StubHit("Input_PollPlayerJoystick");return 0;}
__attribute__((weak)) int BootGatedInitInstallPair(){MK4_StubHit("BootGatedInitInstallPair");return 0;}
__attribute__((weak)) int SlotInitAndChainLink(){MK4_StubHit("SlotInitAndChainLink");return 0;}
__attribute__((weak)) int SetDirty4XorScaledLoad(){MK4_StubHit("SetDirty4XorScaledLoad");return 0;}
__attribute__((weak)) int Snd3DSourceCleanup(){MK4_StubHit("Snd3DSourceCleanup");return 0;}
__attribute__((weak)) int BitFlagEffectDispatch(){MK4_StubHit("BitFlagEffectDispatch");return 0;}
__attribute__((weak)) int DualEntryInstallSelfScaled(){MK4_StubHit("DualEntryInstallSelfScaled");return 0;}
__attribute__((weak)) int PvpAngleDistSeed(){MK4_StubHit("PvpAngleDistSeed");return 0;}
__attribute__((weak)) int QuadGuardedCjSet_00422fc0(){MK4_StubHit("QuadGuardedCjSet_00422fc0");return 0;}
__attribute__((weak)) int QuadGuardedCjSet_004230b0(){MK4_StubHit("QuadGuardedCjSet_004230b0");return 0;}
__attribute__((weak)) int StageParticleEmitterInit(){MK4_StubHit("StageParticleEmitterInit");return 0;}
__attribute__((weak)) int DownloadPlayerChar_Variant(){MK4_StubHit("DownloadPlayerChar_Variant");return 0;}
__attribute__((weak)) int TripleStateSwapCall(){MK4_StubHit("TripleStateSwapCall");return 0;}
__attribute__((weak)) int Phase3InstallSelf(){MK4_StubHit("Phase3InstallSelf");return 0;}
__attribute__((weak)) int ScaledLoadCmp0fJmp(){MK4_StubHit("ScaledLoadCmp0fJmp");return 0;}
__attribute__((weak)) int PendingMatch_ZeroNDwords(){MK4_StubHit("PendingMatch_ZeroNDwords");return 0;}
__attribute__((weak)) int PendingMatch_BootStateTriple(){MK4_StubHit("PendingMatch_BootStateTriple");return 0;}
__attribute__((weak)) int ScaledChainAccumLoop(){MK4_StubHit("ScaledChainAccumLoop");return 0;}
__attribute__((weak)) int BootMStackBracketedScaledStores(){MK4_StubHit("BootMStackBracketedScaledStores");return 0;}
__attribute__((weak)) int Copy3Fields38(){MK4_StubHit("Copy3Fields38");return 0;}
__attribute__((weak)) int CopyThreeFields(){MK4_StubHit("CopyThreeFields");return 0;}
__attribute__((weak)) int ThreeChanPackClamp(){MK4_StubHit("ThreeChanPackClamp");return 0;}
__attribute__((weak)) int func_00405420_ii(){MK4_StubHit("func_00405420_ii");return 0;}
__attribute__((weak)) int AnimEventUpdateCluster(){MK4_StubHit("AnimEventUpdateCluster");return 0;}
/* camera-phase band (SlotPhaseDispatcherBigSwitch callees) - work-list */
__attribute__((weak)) int CallPauseCallTestStackPushJmp(){MK4_StubHit("CallPauseCallTestStackPushJmp");return 0;}
__attribute__((weak)) int CallPauseMStackPushSet0Jmp(){MK4_StubHit("CallPauseMStackPushSet0Jmp");return 0;}
__attribute__((weak)) int CallPauseTriCmpJmp(){MK4_StubHit("CallPauseTriCmpJmp");return 0;}
__attribute__((weak)) int CjInstallSelfRouter(){MK4_StubHit("CjInstallSelfRouter");return 0;}
__attribute__((weak)) int CjMaskedFlagProbe(){MK4_StubHit("CjMaskedFlagProbe");return 0;}
__attribute__((weak)) int DualGatedStateYield(){MK4_StubHit("DualGatedStateYield");return 0;}
__attribute__((weak)) int GuardedDispatch_CallPauseMStackPushSet3Jmp(){MK4_StubHit("GuardedDispatch_CallPauseMStackPushSet3Jmp");return 0;}
__attribute__((weak)) int GuardedDispatch_CallPauseMStackPushSet4Jmp(){MK4_StubHit("GuardedDispatch_CallPauseMStackPushSet4Jmp");return 0;}
__attribute__((weak)) int PerSlotPhaseRouter_DualGatedStateYield_004605d0(){MK4_StubHit("PerSlotPhaseRouter_DualGatedStateYield_004605d0");return 0;}
__attribute__((weak)) int PerSlotPhaseRouter_DualGatedStateYield_00460770(){MK4_StubHit("PerSlotPhaseRouter_DualGatedStateYield_00460770");return 0;}
__attribute__((weak)) int UnlinkChainInstall_00460dd0(){MK4_StubHit("UnlinkChainInstall_00460dd0");return 0;}
__attribute__((weak)) int FiveCallGuardSetTail(){MK4_StubHit("FiveCallGuardSetTail");return 0;}
__attribute__((weak)) int SoundSetupLoop(){MK4_StubHit("SoundSetupLoop");return 0;}
__attribute__((weak)) int CmpCondIdxArrLookup(){MK4_StubHit("CmpCondIdxArrLookup");return 0;}
__attribute__((weak)) int ScaledInitOrSelfPtrSetType_0046a5e0(){MK4_StubHit("ScaledInitOrSelfPtrSetType_0046a5e0");return 0;}
__attribute__((weak)) int GuardedPushCall_CopyJmp_then_ArgSarStoreJmp_0046a560(){MK4_StubHit("GuardedPushCall_CopyJmp_then_ArgSarStoreJmp_0046a560");return 0;}
__attribute__((weak)) int Install3StateRouterTail(){MK4_StubHit("Install3StateRouterTail");return 0;}
__attribute__((weak)) int Phase4ThreePackedInstallSelf(){MK4_StubHit("Phase4ThreePackedInstallSelf");return 0;}
__attribute__((weak)) int SetupVecFsmCluster(){MK4_StubHit("SetupVecFsmCluster");return 0;}
__attribute__((weak)) int PollThenInit(){MK4_StubHit("PollThenInit");return 0;}
__attribute__((weak)) int MultiGateDispatchCallJmp(){MK4_StubHit("MultiGateDispatchCallJmp");return 0;}
__attribute__((weak)) int EnduranceStateInitWalk(){MK4_StubHit("EnduranceStateInitWalk");return 0;}
__attribute__((weak)) int BulletVolleySpawner(){MK4_StubHit("BulletVolleySpawner");return 0;}

__attribute__((weak)) int PushCallPauseScaledJmpInd(){MK4_StubHit("PushCallPauseScaledJmpInd");return 0;}

__attribute__((weak)) int ScaledLoadJmp_00428d20(){MK4_StubHit("ScaledLoadJmp_00428d20");return 0;}
__attribute__((weak)) int ScaledLoadJmp_00429390(){MK4_StubHit("ScaledLoadJmp_00429390");return 0;}
__attribute__((weak)) int EsiInstallDecGlobalJmp(){MK4_StubHit("EsiInstallDecGlobalJmp");return 0;}
__attribute__((weak)) int EntryThunkBodyStateMachine(){MK4_StubHit("EntryThunkBodyStateMachine");return 0;}
__attribute__((weak)) int DualBranchWordLookup(){MK4_StubHit("DualBranchWordLookup");return 0;}
__attribute__((weak)) int TableLookupCall_g_eventTbl_112(){MK4_StubHit("TableLookupCall_g_eventTbl_112");return 0;}
__attribute__((weak)) int TableLookupCall_g_eventTbl_19(){MK4_StubHit("TableLookupCall_g_eventTbl_19");return 0;}
__attribute__((weak)) int State208cBit0Flag(){MK4_StubHit("State208cBit0Flag");return 0;}
__attribute__((weak)) int CallDirty4DualJmp(){MK4_StubHit("CallDirty4DualJmp");return 0;}
__attribute__((weak)) int HitReactionCluster(){MK4_StubHit("HitReactionCluster");return 0;}

__attribute__((weak)) int InstallSelfBitGated(){MK4_StubHit("InstallSelfBitGated");return 0;}
__attribute__((weak)) int ScaledClearJmp_InstallSelfBitGated(){MK4_StubHit("ScaledClearJmp_InstallSelfBitGated");return 0;}
__attribute__((weak)) int InstallSelfDualCountdown(){MK4_StubHit("InstallSelfDualCountdown");return 0;}
__attribute__((weak)) int ScaledClearJmp_InstallSelf3WayChainCmp(){MK4_StubHit("ScaledClearJmp_InstallSelf3WayChainCmp");return 0;}
__attribute__((weak)) int EsiInstallChainCmpDualCall(){MK4_StubHit("EsiInstallChainCmpDualCall");return 0;}

__attribute__((weak)) int GuardedDualConst2AndToggle(){MK4_StubHit("GuardedDualConst2AndToggle");return 0;}

__attribute__((weak)) int Anim_DecodeBitstream(){MK4_StubHit("Anim_DecodeBitstream");return 0;}

__attribute__((weak)) int MStackBootPush4Init(){MK4_StubHit("MStackBootPush4Init");return 0;}

#endif /* MK4_NATIVE_FULL */
