/* GENERATED by tools/decomp/gen_codeptr_table.py - VA->native-fn trampoline. */
#ifdef MK4_NATIVE_FULL
#include <SDL2/SDL.h>

extern int OnceCall();
extern int MStackPackedInit();
extern int SaveCallRestore();
extern int Mul10Tail();
extern int Helper_TickFrameTail();
extern int FrameFinalize();
extern int SetJmp_ZeroAndDirty4();
extern int ZeroAndDirty4();
extern int DirtyPushCallPop();
extern int PushPopScaled18();
extern int ScaledAndMaskInitJmp();
extern int Thunk_MStackPush2ChainPrepend();
extern int PushPopScaled14();
extern int MStackPushCallCallPop_func_00405b30();
extern int MStackPushCallCallPop_func_00405dd0();
extern int MStackPushCallCallPop_func_00405e20();
extern int MStackCall_MStackPush2ChainInsert_00406250();
extern int MStackCall_MStackPush2ChainInsert_004062a0();
extern int MStackCall_MStackPush2ChainPrepend_004062f0();
extern int MStackCall_MStackPush2ChainPrepend_00406340();
extern int MStackCall_MStackPush2ChainPrepend_00406390();
extern int MStackCall_MStackPush2ChainPrepend_004063e0();
extern int MStackCall_MStackPush2ChainInsert_004065b0();
extern int MStackCall_MStackPush2ChainPrepend_00406600();
extern int ScaledLoadGuardedJmp();
extern int MStackPushZeroCallPop();
extern int MStackCall_MStackPush2ChainLLInsert();
extern int MStackPush2ChainLLInsert();
extern int ScaledLoadOrSetJmp();
extern int MStackCall_MStackPush2ChainInsert_00406b50();
extern int CopyJmp_GuardedChainPushSetCallPop_g_currentNodeIdx();
extern int GuardedChainPushSetCallPop();
extern int ScaledStoreIdx24();
extern int PushSetXfmMaskCallPop();
extern int BootChainPushAddSignFlag();
extern int SetJmp_CallPauseScaledStoreAdd();
extern int CallPauseScaledStoreAdd();
extern int MStackPushZeroCallPop_PendingMatch();
extern int PushPopScaled1cDoubleCall();
extern int SetJmp_BootStateTriple();
extern int MStackPush2ChainInsert();
extern int MStackBracket5_LinkedListUnlink();
extern int ScaledInit_Phase4SevenPackedDispatch_g_eventQueueTotal();
extern int GuardedSeq_BootStateInitLongChain_then_StackPopDispatchTagged();
extern int ZeroLargeBlock();
extern int AllocateNode();
extern int BootScheduledNodeTimerWalk();
extern int NodeUnlink();
extern int StackPopDispatchTagged();
extern int LoadShlDerefCallSkip();
extern int CallSetPause();
extern int ScaledNeg1SetPause();
extern int NodeChainMaskMatch();
extern int StructArrayWalkCondCall();
extern int OrListLoop();
extern int Wrapper_OrListLoop_004de3f8();
extern int Wrapper_OrListLoop_004d8e80();
extern int Set2FiveCallPauseJmp();
extern int GameTick();
extern int GuardedSeq_ZeroTriple_then_PendingMatch();
extern int ZeroTriple();
extern int ScaledInitOrSelfPtr_InstallSelfStackReset();
extern int InstallSelfStackReset();
extern int Helper_PostPlayerTick();
extern int CountdownClampWalk();
extern int PvsMergeDriver();
extern int PvsMerge_MatchEnd_00425f90();
extern int PvsMerge_MatchNode_00425fd0();
extern int Thunk_BootMod6487eClampAndChainMul10();
extern int ScaledArrStore_GuardedSeq_CopyJmp_then_MStackPushDualJmp();
extern int GuardedSeq_CopyJmp_then_MStackPushDualJmp();
extern int MStackPushDualJmp();
extern int GuardedSeq_CopyJmp_then_GuardedLoopWithCallback();
extern int GuardedLoopWithCallback();
extern int ScaledArrStore_CallDualStoreXorBit();
extern int CallDualStoreXorBit();
extern int ScaledInitOrSelfPtr_CallPauseDirty1JmpDirty4StackPush();
extern int SetJmp_EsiInstallDecCallChain();
extern int ScaledArrStore_EsiInstallBitCallChain_00428e70();
extern int SetJmp_EsiInstallBitCallChain();
extern int ScaledArrStore_EsiInstallBitCallChain_004293b0();
extern int EsiInstallDecCallChain_StackPopDispatchTagged_004293d0();
extern int ScaledArrStore_ScaledChainJmp_00429450();
extern int ScaledChainJmp_00429470();
extern int EsiInstallDecCallChain_StackPopDispatchTagged_004294a0();
extern int EsiInstallBitCallChain_CopyJmp_GuardedChainPushSetCallPop_g_currentNodeIdx_00429530();
extern int EsiInstallBitCallChain_CopyJmp_GuardedChainPushSetCallPop_g_currentNodeIdx_004295a0();
extern int EsiInstallBitCallChain_CopyJmp_GuardedChainPushSetCallPop_g_currentNodeIdx_00429610();
extern int ScaledInitOrSelfPtr_StackPopDispatchTagged();
extern int DirtyOrJmp();
extern int Thunk_StackPopDispatchTagged_004296e0();
extern int ScaledStoreCurDirtyClear();
extern int ScaledLoadDecJmp();
extern int ScaledStoreCurDirtyOr1();
extern int CallPauseScaledDecJmp();
extern int GuardedSeq_GuardedChainCmpDualBitXor_then_ScaledIncCmpJmp();
extern int ScaledIncCmpJmp();
extern int GuardedDoubleIncCmpJmp();
extern int ScaledArrStore_ScaledChainJmp_004298c0();
extern int ScaledChainJmp_004298e0();
extern int ScaledArrStore_ScaledArrStore();
extern int ScaledArrStore_SetJmp_ScaledArrStore();
extern int SetJmp_ScaledArrStore();
extern int ScaledArrStore_GuardedChainCmpDualBitXor_00429960();
extern int ScaledArrStore_GuardedChainCmpDualBitXor_00429980();
extern int SetJmp_Distance3DMul10Chain_0042d070();
extern int SetJmp_Distance3DMul10Chain_0042d080();
extern int Distance3DMul10Chain();
extern int GuardedSeq_DualMulScaleStore_then_PhaseInstall2DInterpDispatch_0042fb80();
extern int GuardedSeq_DualMulScaleStore_then_PhaseInstall2DInterpDispatch_0042fba0();
extern int DualMulScaleStore();
extern int GuardedSeq_BitmapBlitRunLength_then_FiveTableInitChainBracketed();
extern int Wrapper_PackedAdvanceCallTailJmp_004e44f0();
extern int Thunk_ScaledLoadInstallOrCall();
extern int ScaledLoadInstallOrCall_00433960();
extern int ScaledLoadInstallOrCall_00433990();
extern int GuardedSeq_PackedSelectLoad6_then_GuardedSeq();
extern int GuardedSeq_CmpP1DualInitStore_then_ScaledIndirectJmp();
extern int ScaledIndirectJmp_00433bf0();
extern int PackedSelectLoad6();
extern int CmpP1DualInitStore_00433d30();
extern int Thunk_InstallSelfChainSetB333();
extern int Thunk_PrefixThunkInstallSelf3State();
extern int Thunk_InstallSelfThreeStateDispatch();
extern int Thunk_InstallSelfPacked0x2005();
extern int Thunk_Wrapper_00438ee0_00435de0();
extern int DualCallPauseDirtyJmp_00435f20();
extern int Wrapper_PackedAdvanceCallTailJmp_004e46d0();
extern int Wrapper_PackedAdvanceCallTailJmp_004e4708();
extern int Wrapper_PackedAdvanceCallTailJmp_004e4718();
extern int Thunk_Wrapper_00438ee0_004368d0();
extern int Thunk_ScaledAddrInit();
extern int ScaledAddrInit_InstallSelfMStackPushDispatch();
extern int InstallSelfMStackPushDispatch();
extern int Wrapper_CmpDualPatchScaledRangeJmp_004e4810();
extern int InstallSelfPacked0x2005();
extern int InstallSelfChainSetB333v2();
extern int GuardedSeq_ScaledZeroFour_then_StackPopDispatchTagged();
extern int PushPop84TripleCall();
extern int Wrapper_CmpDualPatchScaledRangeJmp_004e4850();
extern int GuardedDirtyDispatch();
extern int CallPauseDirtyConstJmp();
extern int Wrapper_CmpDualPatchScaledRangeJmp_004e4950();
extern int Wrapper_CmpDualPatchScaledRangeJmp_004e4990();
extern int SetJmp_StateDispatchYield_00438f50();
extern int SetJmp_StateDispatchYield_00438f60();
extern int SetJmp_StateDispatchYield_00438f70();
extern int PackedAdvanceCallTailJmp();
extern int Wrapper_ScaledIndexCondCopy();
extern int IncStoreCallIATDec();
extern int Cmp2CallDirtyCall();
extern int WeightedSumClampHelper();
extern int Thunk_GuardedSeq();
extern int CmpDualPatchScaledRangeJmp();
extern int Thunk_SetJmp();
extern int SetJmp_HitReactionDispatcher();
extern int Thunk_InstallSelfChainSet2011();
extern int Thunk_InstallSelfChainSetB333v2();
extern int CopyJmp_QuadFieldEarlyJmpThenInstall_g_currentNodeIdx();
extern int QuadFieldEarlyJmpThenInstall();
extern int Wrapper_PackedAdvanceCallTailJmp_004e4a58();
extern int Wrapper_PackedAdvanceCallTailJmp_004e4a70();
extern int SetJmp_AudioBridgeMStackChainCopy_00440710();
extern int SetJmp_AudioBridgeMStackChainCopy_00440720();
extern int ScaledInit_TwoStageSetupTripleCopy_g_walkCallback_00441e10();
extern int ScaledInit_TwoStageSetupTripleCopy_g_walkCallback_00441e30();
extern int ScaledInitOrSelfPtr_DualSeqLoopDispatch();
extern int CopyJmp_GuardedSixFieldCopy_g_cj_0054205c_00445ec0();
extern int CopyJmp_GuardedSixFieldCopy_g_cj_0054205c_00446180();
extern int GuardedSixFieldCopy();
extern int GuardedSeq_ScaledLoadTwoCallDualConst_then_GuardedSeq_0044ba10();
extern int ScaledLoadTwoCallDualConst_MStackPush2RunCountdown_then_MStackBracket7_DispatchAndChain_0044ba30();
extern int GuardedSeq_PendingMatch_then_GuardedSeq();
extern int Add0fJmp();
extern int GuardedChainDualAdd();
extern int MStackCall_PushPopScaled1cDoubleCall();
extern int InstallSelfIndexWalk();
extern int ScaledInit_TripleBlockChainScaledInits_g_walkCallback_00450ed0();
extern int ScaledInit_TripleBlockChainScaledInits_g_walkCallback_00450ef0();
extern int GuardedSeq_ChainDirtyBitWalker_then_DualScaledLoadStoreJmp();
extern int SetJmp_SetJmp_00451ad0_00451aa0();
extern int SetJmp_SetJmp_00451ad0_00451ab0();
extern int SetJmp_SetJmp_00451ad0_00451ac0();
extern int SetJmp_GuardedSeq_00473f10_00451ad0();
extern int SetJmp_SetJmp_00451b10_00451ae0();
extern int SetJmp_SetJmp_00451b10_00451af0();
extern int SetJmp_SetJmp_00451b10_00451b00();
extern int SetJmp_GuardedSeq_00473f10_00451b10();
extern int SetJmp_SetJmp_00451b50_00451b20();
extern int SetJmp_SetJmp_00451b50_00451b30();
extern int SetJmp_SetJmp_00451b50_00451b40();
extern int SetJmp_GuardedSeq_00473f10_00451b50();
extern int SetJmp_JuggleFsmCluster_00451b60();
extern int SetJmp_JuggleFsmCluster_00451b70();
extern int SetJmp_JuggleFsmCluster_00451b80();
extern int JuggleFsmCluster();
extern int DualScaledStore();
extern int GuardedSeq_MStackPushTwoEntryChainCall_then_PoseCopyIdleCluster();
extern int SetJmp_CharSelectFsmCluster_004561c0();
extern int SetJmp_CharSelectFsmCluster_004561d0();
extern int SetJmp_CharSelectFsmCluster_004561e0();
extern int ArgSarStoreJmp();
extern int FightFrameStep();
extern int FightFrameStep_Inner();
extern int DispatchEventQueue();
extern int EventQueueDrainLoop();
extern int DispatchEventQueue_Commit();
extern int Thunk_StateInstall_0045ca00();
extern int Thunk_StateInstall_0045ca60();
extern int Thunk_StateInstall_0045ca80();
extern int Thunk_StateInstall_0045caa0();
extern int Thunk_StateInstall_0045cac0();
extern int Thunk_StateInstall_0045cb40();
extern int Thunk_StateInstall_0045cbe0();
extern int Thunk_StateInstall_0045cc90();
extern int Thunk_StateInstall_0045cd00();
extern int Thunk_StateInstall_0045cda0();
extern int Thunk_StateInstall_0045cdb0();
extern int Thunk_StateInstall_0045ce40();
extern int Thunk_StateInstall_0045ced0();
extern int Thunk_StateInstall_0045cf30();
extern int Thunk_StateInstall_0045cf50();
extern int Thunk_StateInstall_0045cf70();
extern int Thunk_StateInstall_0045cf90();
extern int Thunk_StateInstall_0045d010();
extern int Thunk_StateInstall_0045d0b0();
extern int Thunk_StateInstall_0045d450();
extern int Thunk_StateInstall_0045d4c0();
extern int Thunk_StateInstall_0045d560();
extern int Thunk_Thunk();
extern int Thunk_Thunk_0049cbc0_0045e0f0();
extern int SetJmp_SixSubdispatchSpan_0045ebf0();
extern int SetJmp_SixSubdispatchSpan_0045ec00();
extern int Thunk_GuardedDoubleCallSetJmp();
extern int GuardedDoubleCallSetJmp();
extern int GuardedSeq_MStackNegAwareMul10Pair_then_ChainTableWalkStore();
extern int SetJmp_AlarmCountdownInstall_004609c0();
extern int SetJmp_AlarmCountdownInstall_004609d0();
extern int AlarmCountdownInstall();
extern int StateSnapshotDispatch();
extern int NotShrCmp1Store();
extern int GuardedScaledChainJmpIndirect();
extern int CallPauseScaledStoreCopyJmp();
extern int NineEntryFlagDispatch();
extern int Thunk_StackPopDispatchTagged_004647f0();
extern int AppInit_Misc7();
extern int ScaledAddrInit_IntroComboFsmCluster_004677c0();
extern int ScaledAddrInit_IntroComboFsmCluster_004677e0();
extern int IntroComboFsmCluster();
extern int GuardedSeq_ScaledLoadTwoCallDualConst_then_GuardedSeq_00467c10();
extern int ScaledLoadTwoCallDualConst_MStackPush2RunCountdown_then_MStackBracket7_DispatchAndChain_00467c30();
extern int GuardedSeq_GuardedTripleCallSetTail_then_GuardedSeq();
extern int GuardedTripleCallSetTail();
extern int CallJmp();
extern int Wrapper_ArgSarStoreJmp_004eba28();
extern int GuardedSeq_MStackCall_then_CallSetPause_00471670();
extern int GuardedSeq_DualPushCmp12Dispatch68_then_ByteWordTableTaggedDispatch();
extern int GuardedSeq_DualPushCmp12Dispatch_then_ByteWordTableTaggedDispatch();
extern int GuardedSeq_DualSetShiftCall_then_DoubleStackPushAndJmp7b();
extern int GuardedSeq_DualSetShiftCall_then_DoubleStackPushAndJmp7d();
extern int GuardedSeq_DualSetShiftCall_then_DoubleStackPushAndJmp();
extern int GuardedSeq_DualSetShiftCall_then_DualPushSet7dCallPop();
extern int GuardedSeq_DualSetShiftCall_then_MStackPush2CjMul10Triple();
extern int DoubleStackPushAndJmp();
extern int DoubleStackPushAndJmp7d();
extern int DoubleStackPushAndJmp7b();
extern int DualPushSet7dCallPop();
extern int ScaledInitOrSelfPtr_NetEntityScanAndPunish();
extern int NetEntityScanAndPunish();
extern int SetJmp_InstallSelfChainEsi();
extern int InstallSelfChainEsi();
extern int DualScaledLoadStoreJmp();
extern int MStackBracket3PackedSlotInit();
extern int GuardedSeq_DirtyDoubleDeref_then_ScaledOr4Jmp();
extern int ScaledOr4Jmp();
extern int CondInstallDispatch_00476e20();
extern int CondInstallDispatch_00476ed0();
extern int GuardedSeq_DirtyDoubleDeref_then_ChainSlotSetupInstallSelf();
extern int GuardedSeq_DirtyDoubleDeref_then_ScaledAndFBJmp();
extern int ScaledAndFBJmp();
extern int CondInstallDispatch_00477000();
extern int Wrapper_ArgSarStoreJmp_004ed440();
extern int GuardedSeq_MStackPushSet0004_then_MoveSelectorCluster();
extern int Wrapper_ArgSarStoreJmp_004ed660();
extern int ScaledLitLoadCall_ScaledChainCallPauseSetJmp_then_Wrapper_IterLoad_0048fd30_00480fe0();
extern int ScaledLitLoadCall_ScaledChainCallPauseSetJmp_then_Wrapper_IterLoad_0048fd30_00481020();
extern int Wrapper_IterLoad_0048fd30_004ed980();
extern int CmpP1DualInitStore_00482ab0();
extern int SetJmp_MStackPush4IndirectCall();
extern int SetJmp_InstallSelfTwoTailJmp();
extern int Wrapper_ArgSarStoreJmp_004ee850();
extern int Wrapper_ArgSarStoreJmp_004ee958();
extern int GuardedSeq_ScaledZeroFour_then_GuardedSeq();
extern int SetJmp_DualLoadDualStoreJmp();
extern int DualLoadDualStoreJmp();
extern int Mul10Tail5xInterp();
extern int Wrapper_ArgSarStoreJmp_004eeeb0();
extern int GuardedSeq_CmpJmpTwoBranch_then_Wrapper_ScaledChainPushCall();
extern int CmpJmpTwoBranch();
extern int SetJmp_InstallSelfMStackIndirect();
extern int GuardedSeq_CjTableThresholdDispatch_then_RoundTextMenuEventCluster();
extern int Wrapper_Cascade5StageInit_004ef1e8();
extern int GuardedSeq_ScaledXorStore_then_LiteralPushCallEntZero();
extern int LiteralPushCallEntZero();
extern int Wrapper_Cascade5StageInit_004ef208();
extern int SetJmp_ScaledLitLoadCall();
extern int ScaledInitOrSelfPtr_func_0041f780_z();
extern int Helper_PerPlayerTick();
extern int GeoTransformDispatchAndApply();
extern int DualInstallCallSwap_SqDistThresholdRevertAdvance_then_SqDistThresholdRevertAdvance();
extern int ScaledStateNegCallPauseLoad();
extern int ScaledChainPushCall();
extern int Push16Call();
extern int Wrapper_ScaledChainPushCall_004ef980();
extern int Wrapper_ScaledChainPushCall_004ef828();
extern int Wrapper_ScaledChainPushCall_004ef948();
extern int Wrapper_ScaledChainPushCall_004ef810();
extern int Wrapper_ScaledChainPushCall_004ef898();
extern int Wrapper_ScaledChainPushCall_004ef910();
extern int Wrapper_ScaledChainPushCall_004ef900();
extern int Wrapper_ScaledChainPushCall_004ef878();
extern int Wrapper_ScaledChainPushCall_004ef8c8();
extern int Wrapper_ScaledChainPushCall_004ef858();
extern int Wrapper_ScaledChainPushCall_004ef868();
extern int Wrapper_ScaledChainPushCall_004ef920();
extern int Wrapper_ScaledChainPushCall_004ef8e0();
extern int Wrapper_ScaledChainPushCall_004ef8f0();
extern int Wrapper_ScaledChainPushCall_004ef8b0();
extern int Wrapper_ScaledChainPushCall_004ef888();
extern int Wrapper_ScaledChainPushCall_004ef838();
extern int SetJmp_Phase3InstallTableCheck();
extern int Helper_DownloadDebugPrint();
extern int ScaledInit_MStackChainInstallDispatch_g_scaledInit_0048d430();
extern int ScaledInit_MStackChainInstallDispatch_g_scaledInit_0048d450();
extern int ScaledInit_MStackChainInstallDispatch_g_scaledInit_0048d470();
extern int ScaledInit_MStackChainInstallDispatch_g_scaledInit_0048d490();
extern int LeaPlus22StoreSelf();
extern int ScaledIndexCondCopy();
extern int IterLoad_g_scaledInit_00542048_then_Thunk_Thunk_0049cbc0();
extern int StateInstallOrForward_0048e6b0();
extern int StateInstallOrForward_0048e6e0();
extern int ArgSarAddDerefJmp();
extern int ScaledChain3c74Jmp();
extern int Wrapper_IterLoad_0048fd30_004f12a0();
extern int CopyJmp_ScaledSubStore_g_currentNodeIdx();
extern int ScaledSubStore();
extern int CopyJmp_SlotCmp3way_g_currentNodeIdx();
extern int GuardedDirtyXformFromTable();
extern int ScaledInit_GuardedDirtyXformFromTable_g_scaledInit();
extern int ScaledChainCallPauseSetJmp();
extern int Wrapper_IterLoad_0048fd30_004f12a8();
extern int IterLoad_g_scaledInit_00542044_then_MStackPush4IndirectCall();
extern int Wrapper_IterLoad_0048fd30_004f12ac();
extern int ScaledXorStore_004900f0();
extern int ClearBit2x34();
extern int MStackPushSet0200();
extern int MStackPushSet0080();
extern int MStackPushSet0008();
extern int MStackPushSet0020();
extern int MStackPushSet0040();
extern int MStackPushSet0004();
extern int MStackPushSet0001();
extern int OrStoreDecStackPop();
extern int ScaledXorStore_004903b0();
extern int ScaledZeroFour();
extern int ZeroThreeSlots_00490780();
extern int DualCallPauseDirtyJmp_00490c30();
extern int GuardedSeq_DualCallPauseDirtyJmp_then_ScaledXorStore();
extern int DualInstallCallSwap_CjChainResetThreshold_then_CjChainResetThreshold();
extern int IterLoad_g_scaledInit_00542048_then_DualScaledStoreZero();
extern int DualScaledStoreZero();
extern int ScaledInit_GameModeHandlerCluster_g_scaledInit_00495590();
extern int ScaledInit_GameModeHandlerCluster_g_scaledInit_004955b0();
extern int GuardedSeq_MStackCall_then_CallSetPause_00497450();
extern int GuardedSeq_MStackCall_then_CallSetPause_0049a650();
extern int GuardedSeq_MStackCall_then_CallSetPause_0049c340();
extern int ScaledIndirectJmp_0049c850();
extern int AllocNode();
extern int Thunk_NodeChainMaskMatch();
extern int Thunk_LoadShlDerefCallSkip();
extern int SetJmp_Thunk_LinkedListBitMaskSearch();
extern int Thunk_LinkedListBitMaskSearch();
extern int Thunk_Thunk_0049cbc0_0049cbb0();
extern int Thunk_ScaledNeg1SetPause();
extern int Thunk_ChainNodeInit();
extern int Helper_TickFrame_PostFight();
extern int Thunk_ZeroLargeBlock();
extern int Thunk_StructArrayWalkCondCall();
extern int Wrapper_SaveCallRestore();
extern int SetJmp_Push16Call_004a1ac0();
extern int SetJmp_Push16Call_004a1ad0();
extern int Helper_TickFrame_Misc();
extern int Helper_AudioStub_2960();
extern int Helper_AudioStub_4140();
extern int DebugStub_NoOp_B();
extern int Helper_AudioStub_4160();
extern int DebugStub_NoOp_A();
extern int FixedDiv16();
extern int FpuSqrtMul();
extern int LinkedListInsert();
extern int DualAddSar();
extern int StorePauseImulShr16();
extern int AudioMixerStep();
extern int ZeroThreeSlots_004ac010();
extern int Helper_AuxAudio_PostInit();
extern int Audio_TimerTeardown();
extern int AuxAudio_Teardown();
extern int Renderer2_EndScene_D3D();
extern int Renderer2_FlushBatch_D3D();
extern int Renderer2_PresentFrame();
extern int R2_Init10();
extern int ComRelease_g_comptr_0058c7b8();
extern int ComReleaseCapture_004aeee0();
extern int ComRelease_g_comptr_0058c7bc();
extern int ComRelease_g_comptr_0058c7c0();
extern int ComReleasePair_004af440();
extern int Renderer3_PresentFrame();
extern int Renderer3_EndScene_SW_FS();
extern int DDraw3_Cleanup();
extern int DDraw3_GetSurface();
extern int ComRelease_g_comptr_0058c870();
extern int ComReleaseCapture_004afb50();
extern int ComReleasePair_004afcd0();
extern int Renderer5_PresentFrame();
extern int Renderer5_EndScene_SW_FS_Hi();
extern int DDraw5_Cleanup();
extern int DDraw5_GetSurface();
extern int ComRelease_g_comptr_0058c8f0();
extern int ComReleaseCapture_004b0380();
extern int ComReleasePair_004b0500();
extern int IncCallVtablePushCall();
extern int ECM_DecodeFrame_Raw();
extern int ECM_DecodeFrameDispatch();
extern int ECM_ParseFrameHeader();
extern int ECM_DecodeFrame();
extern int AppInit_PreInstall();
extern int TestCallZero();
extern int FSYS_fopen();
extern int FSYS_NormalizePath();
extern int FSYS_HashName();
extern int FSYS_fclose();
extern int FSYS_fread();
extern int FSYS_fseek();
extern int FSYS_ftell();
extern int FSYS_fsize();
extern int FSYS_fload();
extern int Helper_AppStub_21C0();
extern int Helper_DrawMenuText();
extern int AppShutdown();
extern int GameLogicStep();
extern int MainLoopStep();
extern int Renderer4_PresentFrame();
extern int Helper_AppStub_2890();
extern int Renderer4_EndScene_SW_Win();
extern int RendererTeardownSW();
extern int AppInit_Misc3();
extern int Helper_AppStub_2AE0();
extern int ProjectTwoVertices();
extern int Helper_EmitLine();
extern int ProjectVertex();
extern int AdvanceTriStripRing();
extern int Color15BitPacker();
extern int PackColor();
extern int Vec3NormalizeScaleStore();
extern int MatVec2Multiply();
extern int TransformVertex();
extern int Vec3ColorShiftClamp();
extern int Mat3x3VecMul6Bit();
extern int BuildRotMatrix_OrderC();
extern int BuildRotMatrix_OrderA();
extern int BuildRotMatrix_OrderB();
extern int Transform9Words();
extern int Word9Reorder();
extern int MatrixTransform3x3Q12();
extern int MinOfThree();
extern int MaxOfThree();
extern int Renderer_GetMode();
extern int Helper_GetMenuExtents();
extern int PresentFrame();
extern int Helper_GSM_PlayMusic();
extern int BeginFrame();
extern int DrawScene();
extern int Helper_GfxCleanup();
extern int Renderer1_BeginFrame_Glide();
extern int Renderer1_EndScene_Glide();
extern int Renderer1_PresentFrame();
extern int Helper_GeoStub_5370();
extern int Helper_TitleAudioReset();
extern int Helper_GeoStub_5A70();
extern int AppInit_Misc2();
extern int Thunk_AppInit_Misc2();
extern int Helper_MemMalloc_Post();
extern int SetHi6();
extern int StoreAtMinus8();
extern int Mem_Free();
extern int Mem_Malloc();
extern int PackedListVisitor();
extern int Helper_MenuStub_62B0();
extern int Menu_FindPrevSelectable();
extern int Menu_FindNextSelectable();
extern int GameStateMachine();
extern int DrawMenu();
extern int Helper_DrawMenu_PostRender();
extern int Menu_PollNavInput();
extern int Helper_GSM_HandleEvent();
extern int Menu_HelpScreen();
extern int Menu_GlideUnavailableDialog();
extern int Menu_Direct3DUnavailableDialog();
extern int Menu_DirectDrawUnavailableDialog();
extern int Menu_PauseMenu();
extern int Menu_ColorDepthErrorDialog();
extern int Menu_InsertCDDialog();
extern int Helper_MenuStub_8EB0();
extern int Helper_TickInit();
extern int DispatchScaledLEA();
extern int VibrationFrameUpdate();
extern int Helper_PreTick();
extern int AltCamMatrixProject();
extern int CameraSetupAndCullFan();
extern int TickAllEntities();
extern int VtableDispatchSetDirty();
extern int Helper_TickInner();
extern int RenderSceneGraphIterate();
extern int ZBucketClampStore();
extern int DirtyBitTripleWriteOrCall();
extern int DirtyTestScaledCopy();
extern int RenderSceneNode();
extern int Helper_TickAlt();
extern int BillboardChainRender();
extern int DrawMeshBlock();
extern int TristripBatchEmit3Cap();
extern int TristripBatchEmit2();
extern int TristripBatchEmit();
extern int VertexQuadBuilder();
extern int BboxProjectAndStash();
extern int GamepadSeqRecord();
extern int MovesPanelEmit();
extern int SunbeamSpriteEmit();
extern int ChainWalkCleanup();
extern int LeaScaledCall();
extern int CleanupCallTwice();
extern int Helper_GeoLoadPre();
extern int TestCallPush4Zero();
extern int LoadGeoAsset_Default();
extern int Thunk_LoadGeoAsset_Default();
extern int Tex_DecodeRLE16();
extern int Helper_GeoLoadPost();
extern int LoadGeoAsset_Textures();
extern int Thunk_Helper_GeoLoadPre();
extern int AppInit_Misc4();
extern int XformChainAdvance();
extern int ChainStreamMatMulVecAdd();
extern int WtSnapshotPushCall();
extern int Push2GlobalsCall();
extern int InitOrAllZeroLoopback();
extern int NodeApplyTransform_A();
extern int NodeApplyTransform_A_Direct();
extern int DispatchProbeOrTransformB();
extern int NodeApplyTransform_B();
extern int NodeApplyTransform_B_Direct();
extern int DispatchProbeOrTransformC();
extern int TransformAccumulate();
extern int NodeApplyTransform_C();
extern int NodeApplyTransform_C_Direct();
extern int NodeApplyTransform_C_Inverse();
extern int NodeApplyMatrix();
extern int NodeApplyTransform_B_Swapped();
extern int ScaledNegThreeWords();
extern int Helper_TitleAudioCleanup();
extern int Thunk_FlushDrawQueue();
extern int SetViewport();
extern int Helper_TexUpload();
extern int FlushDrawQueue();
extern int ScanlineTexBlitPaletted();
extern int BlitBlend16bpp();
extern int ScanlineTexBlit();
extern int ScanlineTexBlitAlpha();
extern int ScanlineTexBlitAdditive();
extern int ScanlineTexBlitInterlaced();
extern int TexturedTriRasterize();
extern int TexturedTriRasterizeAlphaPal();
extern int TexturedTriRasterizeDithered();
extern int TexturedTriRasterizeShaded();
extern int Helper_DrawCursor();
extern int DSound_GetContext();
extern int TestCallIat();
extern int ExitGame();
extern int Thunk_ExitGame();
extern int Win32_GetHInstance();
extern int FreeImpl();
extern int Helper_FClose();
extern int Crt_srand();
extern int Crt_rand();
extern int TableLookupIatCall();

static const struct { unsigned va; void *fn; } g_codePtrTable[] = {
    {0x401340u, (void*)OnceCall},
    {0x4049c0u, (void*)MStackPackedInit},
    {0x4049d0u, (void*)SaveCallRestore},
    {0x404af0u, (void*)Mul10Tail},
    {0x4051e0u, (void*)Helper_TickFrameTail},
    {0x405400u, (void*)FrameFinalize},
    {0x405420u, (void*)SetJmp_ZeroAndDirty4},
    {0x405430u, (void*)ZeroAndDirty4},
    {0x4055b0u, (void*)DirtyPushCallPop},
    {0x4059a0u, (void*)PushPopScaled18},
    {0x405a00u, (void*)ScaledAndMaskInitJmp},
    {0x405ac0u, (void*)Thunk_MStackPush2ChainPrepend},
    {0x405ad0u, (void*)PushPopScaled14},
    {0x405b30u, (void*)MStackPushCallCallPop_func_00405b30},
    {0x405dd0u, (void*)MStackPushCallCallPop_func_00405dd0},
    {0x405e20u, (void*)MStackPushCallCallPop_func_00405e20},
    {0x406250u, (void*)MStackCall_MStackPush2ChainInsert_00406250},
    {0x4062a0u, (void*)MStackCall_MStackPush2ChainInsert_004062a0},
    {0x4062f0u, (void*)MStackCall_MStackPush2ChainPrepend_004062f0},
    {0x406340u, (void*)MStackCall_MStackPush2ChainPrepend_00406340},
    {0x406390u, (void*)MStackCall_MStackPush2ChainPrepend_00406390},
    {0x4063e0u, (void*)MStackCall_MStackPush2ChainPrepend_004063e0},
    {0x4065b0u, (void*)MStackCall_MStackPush2ChainInsert_004065b0},
    {0x406600u, (void*)MStackCall_MStackPush2ChainPrepend_00406600},
    {0x4066d0u, (void*)ScaledLoadGuardedJmp},
    {0x4066f0u, (void*)MStackPushZeroCallPop},
    {0x406740u, (void*)MStackCall_MStackPush2ChainLLInsert},
    {0x406790u, (void*)MStackPush2ChainLLInsert},
    {0x406b20u, (void*)ScaledLoadOrSetJmp},
    {0x406b50u, (void*)MStackCall_MStackPush2ChainInsert_00406b50},
    {0x406ba0u, (void*)CopyJmp_GuardedChainPushSetCallPop_g_currentNodeIdx},
    {0x406bb0u, (void*)GuardedChainPushSetCallPop},
    {0x406ce0u, (void*)ScaledStoreIdx24},
    {0x407140u, (void*)PushSetXfmMaskCallPop},
    {0x4077b0u, (void*)BootChainPushAddSignFlag},
    {0x4078e0u, (void*)SetJmp_CallPauseScaledStoreAdd},
    {0x4078f0u, (void*)CallPauseScaledStoreAdd},
    {0x407d00u, (void*)MStackPushZeroCallPop_PendingMatch},
    {0x408510u, (void*)PushPopScaled1cDoubleCall},
    {0x408d20u, (void*)SetJmp_BootStateTriple},
    {0x409870u, (void*)MStackPush2ChainInsert},
    {0x409aa0u, (void*)MStackBracket5_LinkedListUnlink},
    {0x417e20u, (void*)ScaledInit_Phase4SevenPackedDispatch_g_eventQueueTotal},
    {0x41aad0u, (void*)GuardedSeq_BootStateInitLongChain_then_StackPopDispatchTagged},
    {0x41f270u, (void*)ZeroLargeBlock},
    {0x41f290u, (void*)AllocateNode},
    {0x41f570u, (void*)BootScheduledNodeTimerWalk},
    {0x41f710u, (void*)NodeUnlink},
    {0x41f780u, (void*)StackPopDispatchTagged},
    {0x41f810u, (void*)LoadShlDerefCallSkip},
    {0x41f830u, (void*)CallSetPause},
    {0x41f840u, (void*)ScaledNeg1SetPause},
    {0x41f870u, (void*)NodeChainMaskMatch},
    {0x41fc50u, (void*)StructArrayWalkCondCall},
    {0x41fcc0u, (void*)OrListLoop},
    {0x41fcf0u, (void*)Wrapper_OrListLoop_004de3f8},
    {0x41fd00u, (void*)Wrapper_OrListLoop_004d8e80},
    {0x41fd10u, (void*)Set2FiveCallPauseJmp},
    {0x41fd70u, (void*)GameTick},
    {0x4200b0u, (void*)GuardedSeq_ZeroTriple_then_PendingMatch},
    {0x421c20u, (void*)ZeroTriple},
    {0x421f00u, (void*)ScaledInitOrSelfPtr_InstallSelfStackReset},
    {0x421f40u, (void*)InstallSelfStackReset},
    {0x4227b0u, (void*)Helper_PostPlayerTick},
    {0x422810u, (void*)CountdownClampWalk},
    {0x425db0u, (void*)PvsMergeDriver},
    {0x425f90u, (void*)PvsMerge_MatchEnd_00425f90},
    {0x425fd0u, (void*)PvsMerge_MatchNode_00425fd0},
    {0x427460u, (void*)Thunk_BootMod6487eClampAndChainMul10},
    {0x428330u, (void*)ScaledArrStore_GuardedSeq_CopyJmp_then_MStackPushDualJmp},
    {0x428350u, (void*)GuardedSeq_CopyJmp_then_MStackPushDualJmp},
    {0x428370u, (void*)MStackPushDualJmp},
    {0x428480u, (void*)GuardedSeq_CopyJmp_then_GuardedLoopWithCallback},
    {0x4284a0u, (void*)GuardedLoopWithCallback},
    {0x4285c0u, (void*)ScaledArrStore_CallDualStoreXorBit},
    {0x4285e0u, (void*)CallDualStoreXorBit},
    {0x428950u, (void*)ScaledInitOrSelfPtr_CallPauseDirty1JmpDirty4StackPush},
    {0x428cf0u, (void*)SetJmp_EsiInstallDecCallChain},
    {0x428e70u, (void*)ScaledArrStore_EsiInstallBitCallChain_00428e70},
    {0x429230u, (void*)SetJmp_EsiInstallBitCallChain},
    {0x4293b0u, (void*)ScaledArrStore_EsiInstallBitCallChain_004293b0},
    {0x4293d0u, (void*)EsiInstallDecCallChain_StackPopDispatchTagged_004293d0},
    {0x429450u, (void*)ScaledArrStore_ScaledChainJmp_00429450},
    {0x429470u, (void*)ScaledChainJmp_00429470},
    {0x4294a0u, (void*)EsiInstallDecCallChain_StackPopDispatchTagged_004294a0},
    {0x429530u, (void*)EsiInstallBitCallChain_CopyJmp_GuardedChainPushSetCallPop_g_currentNodeIdx_00429530},
    {0x4295a0u, (void*)EsiInstallBitCallChain_CopyJmp_GuardedChainPushSetCallPop_g_currentNodeIdx_004295a0},
    {0x429610u, (void*)EsiInstallBitCallChain_CopyJmp_GuardedChainPushSetCallPop_g_currentNodeIdx_00429610},
    {0x429680u, (void*)ScaledInitOrSelfPtr_StackPopDispatchTagged},
    {0x4296c0u, (void*)DirtyOrJmp},
    {0x4296e0u, (void*)Thunk_StackPopDispatchTagged_004296e0},
    {0x4296f0u, (void*)ScaledStoreCurDirtyClear},
    {0x429710u, (void*)ScaledLoadDecJmp},
    {0x429730u, (void*)ScaledStoreCurDirtyOr1},
    {0x429750u, (void*)CallPauseScaledDecJmp},
    {0x4297b0u, (void*)GuardedSeq_GuardedChainCmpDualBitXor_then_ScaledIncCmpJmp},
    {0x4297d0u, (void*)ScaledIncCmpJmp},
    {0x429860u, (void*)GuardedDoubleIncCmpJmp},
    {0x4298c0u, (void*)ScaledArrStore_ScaledChainJmp_004298c0},
    {0x4298e0u, (void*)ScaledChainJmp_004298e0},
    {0x429910u, (void*)ScaledArrStore_ScaledArrStore},
    {0x429930u, (void*)ScaledArrStore_SetJmp_ScaledArrStore},
    {0x429950u, (void*)SetJmp_ScaledArrStore},
    {0x429960u, (void*)ScaledArrStore_GuardedChainCmpDualBitXor_00429960},
    {0x429980u, (void*)ScaledArrStore_GuardedChainCmpDualBitXor_00429980},
    {0x42d070u, (void*)SetJmp_Distance3DMul10Chain_0042d070},
    {0x42d080u, (void*)SetJmp_Distance3DMul10Chain_0042d080},
    {0x42d090u, (void*)Distance3DMul10Chain},
    {0x42fb80u, (void*)GuardedSeq_DualMulScaleStore_then_PhaseInstall2DInterpDispatch_0042fb80},
    {0x42fba0u, (void*)GuardedSeq_DualMulScaleStore_then_PhaseInstall2DInterpDispatch_0042fba0},
    {0x42ffa0u, (void*)DualMulScaleStore},
    {0x4335d0u, (void*)GuardedSeq_BitmapBlitRunLength_then_FiveTableInitChainBracketed},
    {0x433940u, (void*)Wrapper_PackedAdvanceCallTailJmp_004e44f0},
    {0x433950u, (void*)Thunk_ScaledLoadInstallOrCall},
    {0x433960u, (void*)ScaledLoadInstallOrCall_00433960},
    {0x433990u, (void*)ScaledLoadInstallOrCall_00433990},
    {0x433bb0u, (void*)GuardedSeq_PackedSelectLoad6_then_GuardedSeq},
    {0x433bd0u, (void*)GuardedSeq_CmpP1DualInitStore_then_ScaledIndirectJmp},
    {0x433bf0u, (void*)ScaledIndirectJmp_00433bf0},
    {0x433c60u, (void*)PackedSelectLoad6},
    {0x433d30u, (void*)CmpP1DualInitStore_00433d30},
    {0x4344a0u, (void*)Thunk_InstallSelfChainSetB333},
    {0x434c00u, (void*)Thunk_PrefixThunkInstallSelf3State},
    {0x434eb0u, (void*)Thunk_InstallSelfThreeStateDispatch},
    {0x435330u, (void*)Thunk_InstallSelfPacked0x2005},
    {0x435de0u, (void*)Thunk_Wrapper_00438ee0_00435de0},
    {0x435f20u, (void*)DualCallPauseDirtyJmp_00435f20},
    {0x436490u, (void*)Wrapper_PackedAdvanceCallTailJmp_004e46d0},
    {0x436760u, (void*)Wrapper_PackedAdvanceCallTailJmp_004e4708},
    {0x436770u, (void*)Wrapper_PackedAdvanceCallTailJmp_004e4718},
    {0x4368d0u, (void*)Thunk_Wrapper_00438ee0_004368d0},
    {0x4368e0u, (void*)Thunk_ScaledAddrInit},
    {0x4368f0u, (void*)ScaledAddrInit_InstallSelfMStackPushDispatch},
    {0x436910u, (void*)InstallSelfMStackPushDispatch},
    {0x4377c0u, (void*)Wrapper_CmpDualPatchScaledRangeJmp_004e4810},
    {0x437a90u, (void*)InstallSelfPacked0x2005},
    {0x437f00u, (void*)InstallSelfChainSetB333v2},
    {0x438630u, (void*)GuardedSeq_ScaledZeroFour_then_StackPopDispatchTagged},
    {0x438b90u, (void*)PushPop84TripleCall},
    {0x438c40u, (void*)Wrapper_CmpDualPatchScaledRangeJmp_004e4850},
    {0x438c50u, (void*)GuardedDirtyDispatch},
    {0x438ca0u, (void*)CallPauseDirtyConstJmp},
    {0x438ed0u, (void*)Wrapper_CmpDualPatchScaledRangeJmp_004e4950},
    {0x438ee0u, (void*)Wrapper_CmpDualPatchScaledRangeJmp_004e4990},
    {0x438f50u, (void*)SetJmp_StateDispatchYield_00438f50},
    {0x438f60u, (void*)SetJmp_StateDispatchYield_00438f60},
    {0x438f70u, (void*)SetJmp_StateDispatchYield_00438f70},
    {0x4392c0u, (void*)PackedAdvanceCallTailJmp},
    {0x439310u, (void*)Wrapper_ScaledIndexCondCopy},
    {0x439520u, (void*)IncStoreCallIATDec},
    {0x4398b0u, (void*)Cmp2CallDirtyCall},
    {0x439920u, (void*)WeightedSumClampHelper},
    {0x4399b0u, (void*)Thunk_GuardedSeq},
    {0x4399c0u, (void*)CmpDualPatchScaledRangeJmp},
    {0x439c20u, (void*)Thunk_SetJmp},
    {0x439c30u, (void*)SetJmp_HitReactionDispatcher},
    {0x439e30u, (void*)Thunk_InstallSelfChainSet2011},
    {0x43a540u, (void*)Thunk_InstallSelfChainSetB333v2},
    {0x43a620u, (void*)CopyJmp_QuadFieldEarlyJmpThenInstall_g_currentNodeIdx},
    {0x43a670u, (void*)QuadFieldEarlyJmpThenInstall},
    {0x43abf0u, (void*)Wrapper_PackedAdvanceCallTailJmp_004e4a58},
    {0x43ac00u, (void*)Wrapper_PackedAdvanceCallTailJmp_004e4a70},
    {0x440710u, (void*)SetJmp_AudioBridgeMStackChainCopy_00440710},
    {0x440720u, (void*)SetJmp_AudioBridgeMStackChainCopy_00440720},
    {0x441e10u, (void*)ScaledInit_TwoStageSetupTripleCopy_g_walkCallback_00441e10},
    {0x441e30u, (void*)ScaledInit_TwoStageSetupTripleCopy_g_walkCallback_00441e30},
    {0x442d90u, (void*)ScaledInitOrSelfPtr_DualSeqLoopDispatch},
    {0x445ec0u, (void*)CopyJmp_GuardedSixFieldCopy_g_cj_0054205c_00445ec0},
    {0x446180u, (void*)CopyJmp_GuardedSixFieldCopy_g_cj_0054205c_00446180},
    {0x446190u, (void*)GuardedSixFieldCopy},
    {0x44ba10u, (void*)GuardedSeq_ScaledLoadTwoCallDualConst_then_GuardedSeq_0044ba10},
    {0x44ba30u, (void*)ScaledLoadTwoCallDualConst_MStackPush2RunCountdown_then_MStackBracket7_DispatchAndChain_0044ba30},
    {0x44ba80u, (void*)GuardedSeq_PendingMatch_then_GuardedSeq},
    {0x44ccd0u, (void*)Add0fJmp},
    {0x44ccf0u, (void*)GuardedChainDualAdd},
    {0x44d230u, (void*)MStackCall_PushPopScaled1cDoubleCall},
    {0x450de0u, (void*)InstallSelfIndexWalk},
    {0x450ed0u, (void*)ScaledInit_TripleBlockChainScaledInits_g_walkCallback_00450ed0},
    {0x450ef0u, (void*)ScaledInit_TripleBlockChainScaledInits_g_walkCallback_00450ef0},
    {0x4515a0u, (void*)GuardedSeq_ChainDirtyBitWalker_then_DualScaledLoadStoreJmp},
    {0x451aa0u, (void*)SetJmp_SetJmp_00451ad0_00451aa0},
    {0x451ab0u, (void*)SetJmp_SetJmp_00451ad0_00451ab0},
    {0x451ac0u, (void*)SetJmp_SetJmp_00451ad0_00451ac0},
    {0x451ad0u, (void*)SetJmp_GuardedSeq_00473f10_00451ad0},
    {0x451ae0u, (void*)SetJmp_SetJmp_00451b10_00451ae0},
    {0x451af0u, (void*)SetJmp_SetJmp_00451b10_00451af0},
    {0x451b00u, (void*)SetJmp_SetJmp_00451b10_00451b00},
    {0x451b10u, (void*)SetJmp_GuardedSeq_00473f10_00451b10},
    {0x451b20u, (void*)SetJmp_SetJmp_00451b50_00451b20},
    {0x451b30u, (void*)SetJmp_SetJmp_00451b50_00451b30},
    {0x451b40u, (void*)SetJmp_SetJmp_00451b50_00451b40},
    {0x451b50u, (void*)SetJmp_GuardedSeq_00473f10_00451b50},
    {0x451b60u, (void*)SetJmp_JuggleFsmCluster_00451b60},
    {0x451b70u, (void*)SetJmp_JuggleFsmCluster_00451b70},
    {0x451b80u, (void*)SetJmp_JuggleFsmCluster_00451b80},
    {0x451b90u, (void*)JuggleFsmCluster},
    {0x452740u, (void*)DualScaledStore},
    {0x453780u, (void*)GuardedSeq_MStackPushTwoEntryChainCall_then_PoseCopyIdleCluster},
    {0x4561c0u, (void*)SetJmp_CharSelectFsmCluster_004561c0},
    {0x4561d0u, (void*)SetJmp_CharSelectFsmCluster_004561d0},
    {0x4561e0u, (void*)SetJmp_CharSelectFsmCluster_004561e0},
    {0x4594f0u, (void*)ArgSarStoreJmp},
    {0x45c5c0u, (void*)FightFrameStep},
    {0x45c6c0u, (void*)FightFrameStep_Inner},
    {0x45c820u, (void*)DispatchEventQueue},
    {0x45c840u, (void*)EventQueueDrainLoop},
    {0x45c8d0u, (void*)DispatchEventQueue_Commit},
    {0x45ca00u, (void*)Thunk_StateInstall_0045ca00},
    {0x45ca60u, (void*)Thunk_StateInstall_0045ca60},
    {0x45ca80u, (void*)Thunk_StateInstall_0045ca80},
    {0x45caa0u, (void*)Thunk_StateInstall_0045caa0},
    {0x45cac0u, (void*)Thunk_StateInstall_0045cac0},
    {0x45cb40u, (void*)Thunk_StateInstall_0045cb40},
    {0x45cbe0u, (void*)Thunk_StateInstall_0045cbe0},
    {0x45cc90u, (void*)Thunk_StateInstall_0045cc90},
    {0x45cd00u, (void*)Thunk_StateInstall_0045cd00},
    {0x45cda0u, (void*)Thunk_StateInstall_0045cda0},
    {0x45cdb0u, (void*)Thunk_StateInstall_0045cdb0},
    {0x45ce40u, (void*)Thunk_StateInstall_0045ce40},
    {0x45ced0u, (void*)Thunk_StateInstall_0045ced0},
    {0x45cf30u, (void*)Thunk_StateInstall_0045cf30},
    {0x45cf50u, (void*)Thunk_StateInstall_0045cf50},
    {0x45cf70u, (void*)Thunk_StateInstall_0045cf70},
    {0x45cf90u, (void*)Thunk_StateInstall_0045cf90},
    {0x45d010u, (void*)Thunk_StateInstall_0045d010},
    {0x45d0b0u, (void*)Thunk_StateInstall_0045d0b0},
    {0x45d450u, (void*)Thunk_StateInstall_0045d450},
    {0x45d4c0u, (void*)Thunk_StateInstall_0045d4c0},
    {0x45d560u, (void*)Thunk_StateInstall_0045d560},
    {0x45dae0u, (void*)Thunk_Thunk},
    {0x45e0f0u, (void*)Thunk_Thunk_0049cbc0_0045e0f0},
    {0x45ebf0u, (void*)SetJmp_SixSubdispatchSpan_0045ebf0},
    {0x45ec00u, (void*)SetJmp_SixSubdispatchSpan_0045ec00},
    {0x460250u, (void*)Thunk_GuardedDoubleCallSetJmp},
    {0x460260u, (void*)GuardedDoubleCallSetJmp},
    {0x4605b0u, (void*)GuardedSeq_MStackNegAwareMul10Pair_then_ChainTableWalkStore},
    {0x4609c0u, (void*)SetJmp_AlarmCountdownInstall_004609c0},
    {0x4609d0u, (void*)SetJmp_AlarmCountdownInstall_004609d0},
    {0x4609e0u, (void*)AlarmCountdownInstall},
    {0x460b60u, (void*)StateSnapshotDispatch},
    {0x460d80u, (void*)NotShrCmp1Store},
    {0x460e40u, (void*)GuardedScaledChainJmpIndirect},
    {0x461220u, (void*)CallPauseScaledStoreCopyJmp},
    {0x461260u, (void*)NineEntryFlagDispatch},
    {0x4647f0u, (void*)Thunk_StackPopDispatchTagged_004647f0},
    {0x464830u, (void*)AppInit_Misc7},
    {0x4677c0u, (void*)ScaledAddrInit_IntroComboFsmCluster_004677c0},
    {0x4677e0u, (void*)ScaledAddrInit_IntroComboFsmCluster_004677e0},
    {0x467800u, (void*)IntroComboFsmCluster},
    {0x467c10u, (void*)GuardedSeq_ScaledLoadTwoCallDualConst_then_GuardedSeq_00467c10},
    {0x467c30u, (void*)ScaledLoadTwoCallDualConst_MStackPush2RunCountdown_then_MStackBracket7_DispatchAndChain_00467c30},
    {0x467c80u, (void*)GuardedSeq_GuardedTripleCallSetTail_then_GuardedSeq},
    {0x467ca0u, (void*)GuardedTripleCallSetTail},
    {0x467d30u, (void*)CallJmp},
    {0x471340u, (void*)Wrapper_ArgSarStoreJmp_004eba28},
    {0x471670u, (void*)GuardedSeq_MStackCall_then_CallSetPause_00471670},
    {0x472820u, (void*)GuardedSeq_DualPushCmp12Dispatch68_then_ByteWordTableTaggedDispatch},
    {0x472840u, (void*)GuardedSeq_DualPushCmp12Dispatch_then_ByteWordTableTaggedDispatch},
    {0x473ef0u, (void*)GuardedSeq_DualSetShiftCall_then_DoubleStackPushAndJmp7b},
    {0x473f10u, (void*)GuardedSeq_DualSetShiftCall_then_DoubleStackPushAndJmp7d},
    {0x473f30u, (void*)GuardedSeq_DualSetShiftCall_then_DoubleStackPushAndJmp},
    {0x473f50u, (void*)GuardedSeq_DualSetShiftCall_then_DualPushSet7dCallPop},
    {0x473f70u, (void*)GuardedSeq_DualSetShiftCall_then_MStackPush2CjMul10Triple},
    {0x474010u, (void*)DoubleStackPushAndJmp},
    {0x474050u, (void*)DoubleStackPushAndJmp7d},
    {0x474090u, (void*)DoubleStackPushAndJmp7b},
    {0x474290u, (void*)DualPushSet7dCallPop},
    {0x474b10u, (void*)ScaledInitOrSelfPtr_NetEntityScanAndPunish},
    {0x474b50u, (void*)NetEntityScanAndPunish},
    {0x4753a0u, (void*)SetJmp_InstallSelfChainEsi},
    {0x4753b0u, (void*)InstallSelfChainEsi},
    {0x475790u, (void*)DualScaledLoadStoreJmp},
    {0x4757c0u, (void*)MStackBracket3PackedSlotInit},
    {0x476de0u, (void*)GuardedSeq_DirtyDoubleDeref_then_ScaledOr4Jmp},
    {0x476e00u, (void*)ScaledOr4Jmp},
    {0x476e20u, (void*)CondInstallDispatch_00476e20},
    {0x476ed0u, (void*)CondInstallDispatch_00476ed0},
    {0x476f10u, (void*)GuardedSeq_DirtyDoubleDeref_then_ChainSlotSetupInstallSelf},
    {0x476fc0u, (void*)GuardedSeq_DirtyDoubleDeref_then_ScaledAndFBJmp},
    {0x476fe0u, (void*)ScaledAndFBJmp},
    {0x477000u, (void*)CondInstallDispatch_00477000},
    {0x47d6d0u, (void*)Wrapper_ArgSarStoreJmp_004ed440},
    {0x47d980u, (void*)GuardedSeq_MStackPushSet0004_then_MoveSelectorCluster},
    {0x47ed80u, (void*)Wrapper_ArgSarStoreJmp_004ed660},
    {0x480fe0u, (void*)ScaledLitLoadCall_ScaledChainCallPauseSetJmp_then_Wrapper_IterLoad_0048fd30_00480fe0},
    {0x481020u, (void*)ScaledLitLoadCall_ScaledChainCallPauseSetJmp_then_Wrapper_IterLoad_0048fd30_00481020},
    {0x481060u, (void*)Wrapper_IterLoad_0048fd30_004ed980},
    {0x482ab0u, (void*)CmpP1DualInitStore_00482ab0},
    {0x483b40u, (void*)SetJmp_MStackPush4IndirectCall},
    {0x483f20u, (void*)SetJmp_InstallSelfTwoTailJmp},
    {0x484470u, (void*)Wrapper_ArgSarStoreJmp_004ee850},
    {0x484d90u, (void*)Wrapper_ArgSarStoreJmp_004ee958},
    {0x485ca0u, (void*)GuardedSeq_ScaledZeroFour_then_GuardedSeq},
    {0x485d60u, (void*)SetJmp_DualLoadDualStoreJmp},
    {0x485d70u, (void*)DualLoadDualStoreJmp},
    {0x485d90u, (void*)Mul10Tail5xInterp},
    {0x487140u, (void*)Wrapper_ArgSarStoreJmp_004eeeb0},
    {0x4871b0u, (void*)GuardedSeq_CmpJmpTwoBranch_then_Wrapper_ScaledChainPushCall},
    {0x4871d0u, (void*)CmpJmpTwoBranch},
    {0x487910u, (void*)SetJmp_InstallSelfMStackIndirect},
    {0x488890u, (void*)GuardedSeq_CjTableThresholdDispatch_then_RoundTextMenuEventCluster},
    {0x488bd0u, (void*)Wrapper_Cascade5StageInit_004ef1e8},
    {0x488be0u, (void*)GuardedSeq_ScaledXorStore_then_LiteralPushCallEntZero},
    {0x488c00u, (void*)LiteralPushCallEntZero},
    {0x488c60u, (void*)Wrapper_Cascade5StageInit_004ef208},
    {0x489020u, (void*)SetJmp_ScaledLitLoadCall},
    {0x489130u, (void*)ScaledInitOrSelfPtr_func_0041f780_z},
    {0x489240u, (void*)Helper_PerPlayerTick},
    {0x489840u, (void*)GeoTransformDispatchAndApply},
    {0x489cd0u, (void*)DualInstallCallSwap_SqDistThresholdRevertAdvance_then_SqDistThresholdRevertAdvance},
    {0x489e90u, (void*)ScaledStateNegCallPauseLoad},
    {0x489ee0u, (void*)ScaledChainPushCall},
    {0x489f50u, (void*)Push16Call},
    {0x48a250u, (void*)Wrapper_ScaledChainPushCall_004ef980},
    {0x48a260u, (void*)Wrapper_ScaledChainPushCall_004ef828},
    {0x48a270u, (void*)Wrapper_ScaledChainPushCall_004ef948},
    {0x48a280u, (void*)Wrapper_ScaledChainPushCall_004ef810},
    {0x48a300u, (void*)Wrapper_ScaledChainPushCall_004ef898},
    {0x48a310u, (void*)Wrapper_ScaledChainPushCall_004ef910},
    {0x48a320u, (void*)Wrapper_ScaledChainPushCall_004ef900},
    {0x48a330u, (void*)Wrapper_ScaledChainPushCall_004ef878},
    {0x48a340u, (void*)Wrapper_ScaledChainPushCall_004ef8c8},
    {0x48a350u, (void*)Wrapper_ScaledChainPushCall_004ef858},
    {0x48a360u, (void*)Wrapper_ScaledChainPushCall_004ef868},
    {0x48a370u, (void*)Wrapper_ScaledChainPushCall_004ef920},
    {0x48a380u, (void*)Wrapper_ScaledChainPushCall_004ef8e0},
    {0x48a390u, (void*)Wrapper_ScaledChainPushCall_004ef8f0},
    {0x48a3a0u, (void*)Wrapper_ScaledChainPushCall_004ef8b0},
    {0x48a3b0u, (void*)Wrapper_ScaledChainPushCall_004ef888},
    {0x48a3c0u, (void*)Wrapper_ScaledChainPushCall_004ef838},
    {0x48acc0u, (void*)SetJmp_Phase3InstallTableCheck},
    {0x48bfe0u, (void*)Helper_DownloadDebugPrint},
    {0x48d430u, (void*)ScaledInit_MStackChainInstallDispatch_g_scaledInit_0048d430},
    {0x48d450u, (void*)ScaledInit_MStackChainInstallDispatch_g_scaledInit_0048d450},
    {0x48d470u, (void*)ScaledInit_MStackChainInstallDispatch_g_scaledInit_0048d470},
    {0x48d490u, (void*)ScaledInit_MStackChainInstallDispatch_g_scaledInit_0048d490},
    {0x48e4d0u, (void*)LeaPlus22StoreSelf},
    {0x48e590u, (void*)ScaledIndexCondCopy},
    {0x48e680u, (void*)IterLoad_g_scaledInit_00542048_then_Thunk_Thunk_0049cbc0},
    {0x48e6b0u, (void*)StateInstallOrForward_0048e6b0},
    {0x48e6e0u, (void*)StateInstallOrForward_0048e6e0},
    {0x48e710u, (void*)ArgSarAddDerefJmp},
    {0x48e780u, (void*)ScaledChain3c74Jmp},
    {0x48ec20u, (void*)Wrapper_IterLoad_0048fd30_004f12a0},
    {0x48ee80u, (void*)CopyJmp_ScaledSubStore_g_currentNodeIdx},
    {0x48ee90u, (void*)ScaledSubStore},
    {0x48ef90u, (void*)CopyJmp_SlotCmp3way_g_currentNodeIdx},
    {0x48f6d0u, (void*)GuardedDirtyXformFromTable},
    {0x48f720u, (void*)ScaledInit_GuardedDirtyXformFromTable_g_scaledInit},
    {0x48f8e0u, (void*)ScaledChainCallPauseSetJmp},
    {0x48fbc0u, (void*)Wrapper_IterLoad_0048fd30_004f12a8},
    {0x48fd30u, (void*)IterLoad_g_scaledInit_00542044_then_MStackPush4IndirectCall},
    {0x48ff30u, (void*)Wrapper_IterLoad_0048fd30_004f12ac},
    {0x4900f0u, (void*)ScaledXorStore_004900f0},
    {0x490130u, (void*)ClearBit2x34},
    {0x490140u, (void*)MStackPushSet0200},
    {0x490170u, (void*)MStackPushSet0080},
    {0x4901a0u, (void*)MStackPushSet0008},
    {0x4901d0u, (void*)MStackPushSet0020},
    {0x490200u, (void*)MStackPushSet0040},
    {0x490230u, (void*)MStackPushSet0004},
    {0x490260u, (void*)MStackPushSet0001},
    {0x490290u, (void*)OrStoreDecStackPop},
    {0x4903b0u, (void*)ScaledXorStore_004903b0},
    {0x490740u, (void*)ScaledZeroFour},
    {0x490780u, (void*)ZeroThreeSlots_00490780},
    {0x490c30u, (void*)DualCallPauseDirtyJmp_00490c30},
    {0x490c60u, (void*)GuardedSeq_DualCallPauseDirtyJmp_then_ScaledXorStore},
    {0x490c80u, (void*)DualInstallCallSwap_CjChainResetThreshold_then_CjChainResetThreshold},
    {0x491050u, (void*)IterLoad_g_scaledInit_00542048_then_DualScaledStoreZero},
    {0x491080u, (void*)DualScaledStoreZero},
    {0x495590u, (void*)ScaledInit_GameModeHandlerCluster_g_scaledInit_00495590},
    {0x4955b0u, (void*)ScaledInit_GameModeHandlerCluster_g_scaledInit_004955b0},
    {0x497450u, (void*)GuardedSeq_MStackCall_then_CallSetPause_00497450},
    {0x49a650u, (void*)GuardedSeq_MStackCall_then_CallSetPause_0049a650},
    {0x49c340u, (void*)GuardedSeq_MStackCall_then_CallSetPause_0049c340},
    {0x49c850u, (void*)ScaledIndirectJmp_0049c850},
    {0x49cb60u, (void*)AllocNode},
    {0x49cb70u, (void*)Thunk_NodeChainMaskMatch},
    {0x49cb80u, (void*)Thunk_LoadShlDerefCallSkip},
    {0x49cb90u, (void*)SetJmp_Thunk_LinkedListBitMaskSearch},
    {0x49cba0u, (void*)Thunk_LinkedListBitMaskSearch},
    {0x49cbb0u, (void*)Thunk_Thunk_0049cbc0_0049cbb0},
    {0x49cbc0u, (void*)Thunk_ScaledNeg1SetPause},
    {0x49cbd0u, (void*)Thunk_ChainNodeInit},
    {0x49cbe0u, (void*)Helper_TickFrame_PostFight},
    {0x49cbf0u, (void*)Thunk_ZeroLargeBlock},
    {0x49cc00u, (void*)Thunk_StructArrayWalkCondCall},
    {0x49eb10u, (void*)Wrapper_SaveCallRestore},
    {0x4a1ac0u, (void*)SetJmp_Push16Call_004a1ac0},
    {0x4a1ad0u, (void*)SetJmp_Push16Call_004a1ad0},
    {0x4a1d50u, (void*)Helper_TickFrame_Misc},
    {0x4a2960u, (void*)Helper_AudioStub_2960},
    {0x4a4140u, (void*)Helper_AudioStub_4140},
    {0x4a4150u, (void*)DebugStub_NoOp_B},
    {0x4a4160u, (void*)Helper_AudioStub_4160},
    {0x4a4170u, (void*)DebugStub_NoOp_A},
    {0x4ab2a0u, (void*)FixedDiv16},
    {0x4ab350u, (void*)FpuSqrtMul},
    {0x4ab440u, (void*)LinkedListInsert},
    {0x4ab600u, (void*)DualAddSar},
    {0x4ab630u, (void*)StorePauseImulShr16},
    {0x4ab700u, (void*)AudioMixerStep},
    {0x4ac010u, (void*)ZeroThreeSlots_004ac010},
    {0x4ac320u, (void*)Helper_AuxAudio_PostInit},
    {0x4ac5f0u, (void*)Audio_TimerTeardown},
    {0x4ac9b0u, (void*)AuxAudio_Teardown},
    {0x4adc20u, (void*)Renderer2_EndScene_D3D},
    {0x4adc60u, (void*)Renderer2_FlushBatch_D3D},
    {0x4ae950u, (void*)Renderer2_PresentFrame},
    {0x4aedb0u, (void*)R2_Init10},
    {0x4aedc0u, (void*)ComRelease_g_comptr_0058c7b8},
    {0x4aeee0u, (void*)ComReleaseCapture_004aeee0},
    {0x4aef30u, (void*)ComRelease_g_comptr_0058c7bc},
    {0x4af000u, (void*)ComRelease_g_comptr_0058c7c0},
    {0x4af440u, (void*)ComReleasePair_004af440},
    {0x4af690u, (void*)Renderer3_PresentFrame},
    {0x4af880u, (void*)Renderer3_EndScene_SW_FS},
    {0x4afa10u, (void*)DDraw3_Cleanup},
    {0x4afb00u, (void*)DDraw3_GetSurface},
    {0x4afb10u, (void*)ComRelease_g_comptr_0058c870},
    {0x4afb50u, (void*)ComReleaseCapture_004afb50},
    {0x4afcd0u, (void*)ComReleasePair_004afcd0},
    {0x4afec0u, (void*)Renderer5_PresentFrame},
    {0x4b00b0u, (void*)Renderer5_EndScene_SW_FS_Hi},
    {0x4b0240u, (void*)DDraw5_Cleanup},
    {0x4b0330u, (void*)DDraw5_GetSurface},
    {0x4b0340u, (void*)ComRelease_g_comptr_0058c8f0},
    {0x4b0380u, (void*)ComReleaseCapture_004b0380},
    {0x4b0500u, (void*)ComReleasePair_004b0500},
    {0x4b0d80u, (void*)IncCallVtablePushCall},
    {0x4b1220u, (void*)ECM_DecodeFrame_Raw},
    {0x4b1bf0u, (void*)ECM_DecodeFrameDispatch},
    {0x4b1c30u, (void*)ECM_ParseFrameHeader},
    {0x4b1c90u, (void*)ECM_DecodeFrame},
    {0x4b1cf0u, (void*)AppInit_PreInstall},
    {0x4b1de0u, (void*)TestCallZero},
    {0x4b1e00u, (void*)FSYS_fopen},
    {0x4b1ec0u, (void*)FSYS_NormalizePath},
    {0x4b1f50u, (void*)FSYS_HashName},
    {0x4b1f90u, (void*)FSYS_fclose},
    {0x4b1fb0u, (void*)FSYS_fread},
    {0x4b2070u, (void*)FSYS_fseek},
    {0x4b2100u, (void*)FSYS_ftell},
    {0x4b2120u, (void*)FSYS_fsize},
    {0x4b2160u, (void*)FSYS_fload},
    {0x4b21c0u, (void*)Helper_AppStub_21C0},
    {0x4b21d0u, (void*)Helper_DrawMenuText},
    {0x4b2690u, (void*)AppShutdown},
    {0x4b26d0u, (void*)GameLogicStep},
    {0x4b2750u, (void*)MainLoopStep},
    {0x4b2840u, (void*)Renderer4_PresentFrame},
    {0x4b2890u, (void*)Helper_AppStub_2890},
    {0x4b2930u, (void*)Renderer4_EndScene_SW_Win},
    {0x4b2a40u, (void*)RendererTeardownSW},
    {0x4b2ac0u, (void*)AppInit_Misc3},
    {0x4b2ae0u, (void*)Helper_AppStub_2AE0},
    {0x4b2af0u, (void*)ProjectTwoVertices},
    {0x4b2d20u, (void*)Helper_EmitLine},
    {0x4b2e80u, (void*)ProjectVertex},
    {0x4b2fa0u, (void*)AdvanceTriStripRing},
    {0x4b3030u, (void*)Color15BitPacker},
    {0x4b30c0u, (void*)PackColor},
    {0x4b3130u, (void*)Vec3NormalizeScaleStore},
    {0x4b31e0u, (void*)MatVec2Multiply},
    {0x4b3310u, (void*)TransformVertex},
    {0x4b3490u, (void*)Vec3ColorShiftClamp},
    {0x4b3590u, (void*)Mat3x3VecMul6Bit},
    {0x4b36c0u, (void*)BuildRotMatrix_OrderC},
    {0x4b3800u, (void*)BuildRotMatrix_OrderA},
    {0x4b3940u, (void*)BuildRotMatrix_OrderB},
    {0x4b3a90u, (void*)Transform9Words},
    {0x4b3b30u, (void*)Word9Reorder},
    {0x4b3b80u, (void*)MatrixTransform3x3Q12},
    {0x4b3d70u, (void*)MinOfThree},
    {0x4b3d90u, (void*)MaxOfThree},
    {0x4b3db0u, (void*)Renderer_GetMode},
    {0x4b3dc0u, (void*)Helper_GetMenuExtents},
    {0x4b3e90u, (void*)PresentFrame},
    {0x4b40a0u, (void*)Helper_GSM_PlayMusic},
    {0x4b4200u, (void*)BeginFrame},
    {0x4b42e0u, (void*)DrawScene},
    {0x4b4410u, (void*)Helper_GfxCleanup},
    {0x4b4650u, (void*)Renderer1_BeginFrame_Glide},
    {0x4b46a0u, (void*)Renderer1_EndScene_Glide},
    {0x4b46d0u, (void*)Renderer1_PresentFrame},
    {0x4b5370u, (void*)Helper_GeoStub_5370},
    {0x4b5840u, (void*)Helper_TitleAudioReset},
    {0x4b5a70u, (void*)Helper_GeoStub_5A70},
    {0x4b5a80u, (void*)AppInit_Misc2},
    {0x4b5ac0u, (void*)Thunk_AppInit_Misc2},
    {0x4b5ad0u, (void*)Helper_MemMalloc_Post},
    {0x4b5ae0u, (void*)SetHi6},
    {0x4b5b00u, (void*)StoreAtMinus8},
    {0x4b5b10u, (void*)Mem_Free},
    {0x4b5bc0u, (void*)Mem_Malloc},
    {0x4b5c90u, (void*)PackedListVisitor},
    {0x4b62b0u, (void*)Helper_MenuStub_62B0},
    {0x4b62c0u, (void*)Menu_FindPrevSelectable},
    {0x4b6300u, (void*)Menu_FindNextSelectable},
    {0x4b6340u, (void*)GameStateMachine},
    {0x4b65c0u, (void*)DrawMenu},
    {0x4b6880u, (void*)Helper_DrawMenu_PostRender},
    {0x4b7020u, (void*)Menu_PollNavInput},
    {0x4b84d0u, (void*)Helper_GSM_HandleEvent},
    {0x4b8630u, (void*)Menu_HelpScreen},
    {0x4b8730u, (void*)Menu_GlideUnavailableDialog},
    {0x4b8830u, (void*)Menu_Direct3DUnavailableDialog},
    {0x4b8930u, (void*)Menu_DirectDrawUnavailableDialog},
    {0x4b8a30u, (void*)Menu_PauseMenu},
    {0x4b8bd0u, (void*)Menu_ColorDepthErrorDialog},
    {0x4b8d70u, (void*)Menu_InsertCDDialog},
    {0x4b8eb0u, (void*)Helper_MenuStub_8EB0},
    {0x4b8ec0u, (void*)Helper_TickInit},
    {0x4b8f50u, (void*)DispatchScaledLEA},
    {0x4b9640u, (void*)VibrationFrameUpdate},
    {0x4b9770u, (void*)Helper_PreTick},
    {0x4b9840u, (void*)AltCamMatrixProject},
    {0x4b99b0u, (void*)CameraSetupAndCullFan},
    {0x4b9e50u, (void*)TickAllEntities},
    {0x4ba040u, (void*)VtableDispatchSetDirty},
    {0x4ba130u, (void*)Helper_TickInner},
    {0x4ba1c0u, (void*)RenderSceneGraphIterate},
    {0x4ba5d0u, (void*)ZBucketClampStore},
    {0x4ba630u, (void*)DirtyBitTripleWriteOrCall},
    {0x4ba6c0u, (void*)DirtyTestScaledCopy},
    {0x4ba720u, (void*)RenderSceneNode},
    {0x4bae90u, (void*)Helper_TickAlt},
    {0x4bb030u, (void*)BillboardChainRender},
    {0x4bb250u, (void*)DrawMeshBlock},
    {0x4bb680u, (void*)TristripBatchEmit3Cap},
    {0x4bb930u, (void*)TristripBatchEmit2},
    {0x4bbb80u, (void*)TristripBatchEmit},
    {0x4bc470u, (void*)VertexQuadBuilder},
    {0x4bc5a0u, (void*)BboxProjectAndStash},
    {0x4bcc70u, (void*)GamepadSeqRecord},
    {0x4bcf60u, (void*)MovesPanelEmit},
    {0x4bd270u, (void*)SunbeamSpriteEmit},
    {0x4bd4a0u, (void*)ChainWalkCleanup},
    {0x4bd510u, (void*)LeaScaledCall},
    {0x4bd530u, (void*)CleanupCallTwice},
    {0x4bd570u, (void*)Helper_GeoLoadPre},
    {0x4bd590u, (void*)TestCallPush4Zero},
    {0x4bd5b0u, (void*)LoadGeoAsset_Default},
    {0x4bd5c0u, (void*)Thunk_LoadGeoAsset_Default},
    {0x4bd5f0u, (void*)Tex_DecodeRLE16},
    {0x4bd6d0u, (void*)Helper_GeoLoadPost},
    {0x4bd6e0u, (void*)LoadGeoAsset_Textures},
    {0x4bd8d0u, (void*)Thunk_Helper_GeoLoadPre},
    {0x4bd960u, (void*)AppInit_Misc4},
    {0x4bd990u, (void*)XformChainAdvance},
    {0x4bd9a0u, (void*)ChainStreamMatMulVecAdd},
    {0x4bda70u, (void*)WtSnapshotPushCall},
    {0x4bdae0u, (void*)Push2GlobalsCall},
    {0x4bdb00u, (void*)InitOrAllZeroLoopback},
    {0x4bdb50u, (void*)NodeApplyTransform_A},
    {0x4bdc00u, (void*)NodeApplyTransform_A_Direct},
    {0x4bdc70u, (void*)DispatchProbeOrTransformB},
    {0x4bdca0u, (void*)NodeApplyTransform_B},
    {0x4bdd50u, (void*)NodeApplyTransform_B_Direct},
    {0x4bddc0u, (void*)DispatchProbeOrTransformC},
    {0x4bddf0u, (void*)TransformAccumulate},
    {0x4bde90u, (void*)NodeApplyTransform_C},
    {0x4bdf40u, (void*)NodeApplyTransform_C_Direct},
    {0x4bdfb0u, (void*)NodeApplyTransform_C_Inverse},
    {0x4be050u, (void*)NodeApplyMatrix},
    {0x4be130u, (void*)NodeApplyTransform_B_Swapped},
    {0x4be210u, (void*)ScaledNegThreeWords},
    {0x4bea40u, (void*)Helper_TitleAudioCleanup},
    {0x4bf320u, (void*)Thunk_FlushDrawQueue},
    {0x4bf330u, (void*)SetViewport},
    {0x4bf370u, (void*)Helper_TexUpload},
    {0x4bf460u, (void*)FlushDrawQueue},
    {0x4c0360u, (void*)ScanlineTexBlitPaletted},
    {0x4c05e0u, (void*)BlitBlend16bpp},
    {0x4c0920u, (void*)ScanlineTexBlit},
    {0x4c0b70u, (void*)ScanlineTexBlitAlpha},
    {0x4c0e10u, (void*)ScanlineTexBlitAdditive},
    {0x4c1130u, (void*)ScanlineTexBlitInterlaced},
    {0x4c13f0u, (void*)TexturedTriRasterize},
    {0x4c1fe0u, (void*)TexturedTriRasterizeAlphaPal},
    {0x4c2650u, (void*)TexturedTriRasterizeDithered},
    {0x4c2cb0u, (void*)TexturedTriRasterizeShaded},
    {0x4c3360u, (void*)Helper_DrawCursor},
    {0x4c37e0u, (void*)DSound_GetContext},
    {0x4c44f0u, (void*)TestCallIat},
    {0x4c4870u, (void*)ExitGame},
    {0x4c48b0u, (void*)Thunk_ExitGame},
    {0x4c49a0u, (void*)Win32_GetHInstance},
    {0x4c55f0u, (void*)FreeImpl},
    {0x4c5800u, (void*)Helper_FClose},
    {0x4c6500u, (void*)Crt_srand},
    {0x4c6510u, (void*)Crt_rand},
    {0x4c6fd0u, (void*)TableLookupIatCall},
};
enum { MK4_CODEPTR_N = sizeof(g_codePtrTable)/sizeof(g_codePtrTable[0]) };

static void MK4_CodeMissing(void) { }

void *MK4_ResolveCode(unsigned va) {
    int lo = 0, hi = MK4_CODEPTR_N - 1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        unsigned m = g_codePtrTable[mid].va;
        if (m == va) return g_codePtrTable[mid].fn;
        if (m < va) lo = mid + 1; else hi = mid - 1;
    }
    /* Unknown VA. Passing it through means the caller JUMPS to a raw
     * VA - unmapped here, so the process dies with no indication of which
     * target was missing. Report it once and hand back a no-op instead, so
     * one unconverted callback does not hide the rest of the frame. */
    { static unsigned seen[32]; static int n; int i;
      for (i = 0; i < n; i++) if (seen[i] == va) return (void*)MK4_CodeMissing;
      if (n < 32) { seen[n++] = va;
        SDL_Log("unresolved code VA 0x%08x - target not linked natively", va); } }
    return (void*)MK4_CodeMissing;
}

void MK4_CodePtrSelfTest(void) {
    int i, ok = 0;
    for (i = 0; i < MK4_CODEPTR_N; i++)
        if (MK4_ResolveCode(g_codePtrTable[i].va) == g_codePtrTable[i].fn) ok++;
    SDL_Log("codeptr trampoline: %d/%d VAs resolve to native fns", ok, MK4_CODEPTR_N);
}
#endif /* MK4_NATIVE_FULL */
