__imp__BeginPaint: 5054972
__imp__CloseHandle: 5054592
__imp__CreateDIBSection: 5054508
__imp__CreateFileA: 5054660
__imp__CreateFileMappingA: 5054548
__imp__CreateThread: 5054576
__imp__CreateWindowExA: 5054952
__imp__DefWindowProcA: 5054964
__imp__DeleteCriticalSection: 5054832
__imp__DeleteObject: 5054512
__imp__DirectDrawCreate: 5054488
__imp__DirectDrawEnumerateA: 5054492
__imp__DirectSoundCreate: 5054500
__imp__DispatchMessageA: 5054928
__imp__EndPaint: 5054976
__imp__EnterCriticalSection: 5054784
__imp__ExitProcess: 5054804
__imp__FillRect: 5054900
__imp__FlushFileBuffers: 5054704
__imp__FreeEnvironmentStringsA: 5054696
__imp__FreeEnvironmentStringsW: 5054700
__imp__FreeLibrary: 5054556
__imp__GdiFlush: 5054528
__imp__GetACP: 5054736
__imp__GetActiveWindow: 5054988
__imp__GetAsyncKeyState: 5054912
__imp__GetCPInfo: 5054740
__imp__GetClientRect: 5054956
__imp__GetCommandLineA: 5054816
__imp__GetCurrentProcess: 5054560
__imp__GetCurrentThread: 5054564
__imp__GetCurrentThreadId: 5054724
__imp__GetCursorPos: 5054892
__imp__GetDC: 5054904
__imp__GetDeviceCaps: 5054524
__imp__GetDriveTypeA: 5054584
__imp__GetEnvironmentStrings: 5054684
__imp__GetEnvironmentStringsW: 5054680
__imp__GetFileAttributesA: 5054800
__imp__GetFileType: 5054752
__imp__GetLastError: 5054620
__imp__GetLocaleInfoA: 5054772
__imp__GetLocaleInfoW: 5054768
__imp__GetLogicalDrives: 5054540
__imp__GetMenu: 5054856
__imp__GetMessageA: 5054920
__imp__GetModuleFileNameA: 5054624
__imp__GetModuleHandleA: 5054764
__imp__GetOEMCP: 5054744
__imp__GetPriorityClass: 5054568
__imp__GetProcAddress: 5054552
__imp__GetStartupInfoA: 5054776
__imp__GetStdHandle: 5054792
__imp__GetStockObject: 5054520
__imp__GetStringTypeA: 5054652
__imp__GetStringTypeW: 5054648
__imp__GetSystemMetrics: 5054896
__imp__GetThreadPriority: 5054572
__imp__GetVersion: 5054820
__imp__GetWindowLongA: 5054844
__imp__GetWindowPlacement: 5054872
__imp__GetWindowRect: 5054860
__imp__HeapAlloc: 5054644
__imp__HeapCreate: 5054828
__imp__HeapDestroy: 5054808
__imp__HeapFree: 5054796
__imp__InitializeCriticalSection: 5054812
__imp__InterlockedDecrement: 5054672
__imp__InterlockedIncrement: 5054668
__imp__InvalidateRect: 5054992
__imp__LCMapStringA: 5054656
__imp__LCMapStringW: 5054664
__imp__LeaveCriticalSection: 5054780
__imp__LoadCursorA: 5054932
__imp__LoadIconA: 5054940
__imp__LoadLibraryA: 5054544
__imp__MapVirtualKeyA: 5054916
__imp__MessageBeep: 5054968
__imp__MessageBoxA: 5054996
__imp__MultiByteToWideChar: 5054692
__imp__PeekMessageA: 5054852
__imp__PostQuitMessage: 5054960
__imp__QueryPerformanceCounter: 5054536
__imp__QueryPerformanceFrequency: 5054616
__imp__RaiseException: 5054636
__imp__ReadFile: 5054756
__imp__RegCloseKey: 5054468
__imp__RegCreateKeyExA: 5054464
__imp__RegOpenKeyExA: 5054476
__imp__RegQueryValueExA: 5054472
__imp__RegSetValueExA: 5054480
__imp__RegisterClassA: 5054948
__imp__ReleaseDC: 5054888
__imp__ResumeThread: 5054596
__imp__RtlUnwind: 5054632
__imp__SendNotifyMessageA: 5054848
__imp__SetCurrentDirectoryA: 5054588
__imp__SetCursor: 5054984
__imp__SetCursorPos: 5054884
__imp__SetDIBitsToDevice: 5054516
__imp__SetEndOfFile: 5054640
__imp__SetFilePointer: 5054748
__imp__SetHandleCount: 5054760
__imp__SetLastError: 5054720
__imp__SetMenu: 5054840
__imp__SetPriorityClass: 5054604
__imp__SetStdHandle: 5054676
__imp__SetThreadPriority: 5054612
__imp__SetWindowLongA: 5054880
__imp__SetWindowPos: 5054864
__imp__SetWindowTextA: 5054908
__imp__ShowCursor: 5054876
__imp__ShowWindow: 5054868
__imp__Sleep: 5054580
__imp__SuspendThread: 5054608
__imp__SystemParametersInfoA: 5054980
__imp__TerminateProcess: 5054628
__imp__TerminateThread: 5054600
__imp__TlsAlloc: 5054716
__imp__TlsGetValue: 5054708
__imp__TlsSetValue: 5054732
__imp__TranslateMessage: 5054924
__imp__UnhandledExceptionFilter: 5054712
__imp__UpdateWindow: 5054944
__imp__VirtualAlloc: 5054788
__imp__VirtualFree: 5054824
__imp__WaitMessage: 5054936
__imp__WideCharToMultiByte: 5054688
__imp__WriteFile: 5054728
__imp__auxGetDevCapsA: 5055032
__imp__auxGetNumDevs: 5055028
__imp__auxGetVolume: 5055036
__imp__auxSetVolume: 5055024
__imp__joyGetDevCapsA: 5055004
__imp__joyGetPos: 5055020
__imp__joyGetPosEx: 5055016
__imp__mciSendCommandA: 5055044
__imp__timeBeginPeriod: 5055012
__imp__timeEndPeriod: 5055008
__imp__timeGetTime: 5055040
