"""Generate an analysis report for every PendingMatch_* function.

For each function:
  - Direct calls (e8 + REL32)
  - Indirect calls via IAT (ff 15 + DIR32)
  - DIR32 global accesses (a1 / a3 / 89 r/m32 / 8b r/m32)
  - Conditional jmps (count)
  - Traits: rep movsb/stosd, fs: prefix (SEH), x87 FPU opcodes
  - Detection of switch/jump-table dispatch (ff 24 85 + DIR32)

Output: analysis/notes/pending_match_inventory.md, sorted by size.
The goal isn't to auto-rename - it's to give contributors a structured
jumping-off point for the manual semantic-naming work.
"""
import struct, yaml, re, os, sys
from collections import Counter
from pathlib import Path


def fileoff(va): return va - 0x401000 + 0x400


def load_globals_from_headers():
    """Map VA -> semantic global name from header annotations."""
    GLOBALS = {}
    for path, _, files in os.walk('include'):
        for fn in files:
            if not fn.endswith('.h'): continue
            with open(os.path.join(path, fn)) as f:
                txt = f.read()
            for m in re.finditer(
                r'\bextern\s+[^\n]+?\b([A-Za-z_]\w*)(?:\[[^\]]*\])?\s*;\s*/\*\s*'
                r'(?:0x([0-9a-fA-F]+)|DAT_([0-9a-fA-F]+))', txt):
                name = m.group(1)
                addr = int(m.group(2) or m.group(3), 16)
                if addr not in GLOBALS:
                    GLOBALS[addr] = name
    return GLOBALS


def analyze(orig, addr, sz, addr_to_name, GLOBALS):
    fo = fileoff(addr)
    data = orig[fo:fo+sz]
    calls = []
    iat_calls = []
    dir32_globals = []
    n_cond_jmps = 0
    has_seh = False
    has_fpu = False
    has_switch = False
    rep_movsb = False
    rep_stosd = False

    i = 0
    while i < sz:
        op = data[i]
        if op == 0xe8 and i + 5 <= sz:
            rel = struct.unpack_from('<i', data, i+1)[0]
            calls.append(addr + i + 5 + rel)
            i += 5; continue
        if op == 0x0f and i + 6 <= sz and 0x80 <= data[i+1] <= 0x8f:
            n_cond_jmps += 1
            i += 6; continue
        if op == 0xff and i + 6 <= sz and data[i+1] == 0x15:
            iat_calls.append(struct.unpack_from('<I', data, i+2)[0])
            i += 6; continue
        if op == 0xff and i + 7 <= sz and data[i+1] == 0x24 and data[i+2] == 0x85:
            has_switch = True
            i += 7; continue
        if op in (0xa1, 0xa3) and i + 5 <= sz:
            ptr = struct.unpack_from('<I', data, i+1)[0]
            if 0x400000 < ptr < 0xfa0ef4:
                dir32_globals.append(ptr)
            i += 5; continue
        if op == 0xf3 and i + 2 <= sz:
            if data[i+1] == 0xa4: rep_movsb = True
            if data[i+1] == 0xab: rep_stosd = True
            i += 2; continue
        if op == 0x64: has_seh = True
        if 0xd8 <= op <= 0xdf: has_fpu = True
        i += 1

    callee_names = []
    for t in calls:
        callee_names.append(addr_to_name.get(t, f'extern_{t:#x}'))
    global_names = []
    for g in dir32_globals:
        global_names.append(GLOBALS.get(g, f'{g:#x}'))

    return {
        'callees': Counter(callee_names),
        'globals': Counter(global_names),
        'iat_count': len(iat_calls),
        'n_cond_jmps': n_cond_jmps,
        'has_seh': has_seh,
        'has_fpu': has_fpu,
        'has_switch': has_switch,
        'rep_movsb': rep_movsb,
        'rep_stosd': rep_stosd,
    }


def main():
    with open('game/MK4.EXE','rb') as f: orig = f.read()
    with open('config/symbols.yaml') as f: ydat = yaml.safe_load(f)
    addr_to_name = {e['addr']: e['name'] for e in ydat['functions']}
    GLOBALS = load_globals_from_headers()
    pending = [e for e in ydat['functions'] if 'PendingMatch' in e['name']]
    pending.sort(key=lambda e: e['size'])

    out = ['# PendingMatch_* function inventory',
           '',
           f'Auto-generated by `tools/decomp/analyze_pending.py`.',
           f'Lists every PendingMatch_NNNNNNNN function in symbols.yaml with a',
           f'static breakdown: top callees, globals touched, structural traits',
           f'(switch/SEH/FPU/rep), and pointer to the source location. Intended',
           f'as a working list for contributors who want to give these functions',
           f'real semantic names.',
           '',
           f'Total: {len(pending)} functions, sorted by size.',
           '',
           '']
    for e in pending:
        info = analyze(orig, e['addr'], e['size'], addr_to_name, GLOBALS)
        out.append(f'## {e["name"]} @ {e["addr"]:#x} ({e["size"]}b)')
        out.append('')
        out.append(f'- file: `{e.get("file","?")}`')
        traits = []
        if info['has_switch']: traits.append('switch-via-jumptable')
        if info['has_seh']: traits.append('SEH (fs:[0])')
        if info['has_fpu']: traits.append('x87 FPU')
        if info['rep_movsb']: traits.append('rep movsb')
        if info['rep_stosd']: traits.append('rep stosd')
        if info['iat_count']: traits.append(f'IAT calls: {info["iat_count"]}')
        if info['n_cond_jmps']: traits.append(f'cond jmps: {info["n_cond_jmps"]}')
        out.append(f'- traits: {", ".join(traits) if traits else "(plain)"}')
        if info['callees']:
            top = info['callees'].most_common(8)
            out.append(f'- top callees: ' + ', '.join(
                f'`{n}`' + (f'×{c}' if c > 1 else '') for n, c in top))
        if info['globals']:
            top = info['globals'].most_common(8)
            out.append(f'- top globals: ' + ', '.join(
                f'`{n}`' + (f'×{c}' if c > 1 else '') for n, c in top))
        out.append('')

    Path('analysis/notes').mkdir(parents=True, exist_ok=True)
    with open('analysis/notes/pending_match_inventory.md', 'w') as f:
        f.write('\n'.join(out))
    print(f'Wrote analysis/notes/pending_match_inventory.md ({len(pending)} entries)')


if __name__ == '__main__':
    main()
