#!/usr/bin/env python3
"""
Derive each fixed-VA global's real ACCESS WIDTH from the original binary.

Everything downstream types a global `unsigned int` by default:
native_globals.h (generated), alias_globals.py's arena aliases, and
verify_coexec's gdef. For a genuinely 32-bit global that is fine. For a byte or
halfword field it is a corruption bug, because the engine packs those hard -
g_dispatchSave1613..1616 are four CONSECUTIVE BYTES, so one 32-bit store to the
first wipes the other three, and the damage lands in whatever the neighbours
were for.

The binary settles it. Every absolute-VA memory operand carries its width in
the encoding (`mov byte ptr [imm32]`, `mov word ptr [imm32]`, ...), so scanning
every function for operands with no base and no index gives the set of widths
each address is ever touched at. A global that is NEVER touched wider than two
bytes is narrow, and the smallest width seen is its field size.

Signedness matters as much as size. A field the original loads with `movsx` is
SIGNED - the geometry path depends on it, and typing such a field
`unsigned short` reads the same two bytes but sign-extends them wrong.

Conservative on purpose: one 4-byte access anywhere and the global stays
32-bit, because a wider access means the field really is that wide somewhere.

  build/venv/bin/python tools/decomp/audit_widths.py          # report
  build/venv/bin/python tools/decomp/audit_widths.py --write  # config/global_widths.yaml
"""
import collections
import sys
from pathlib import Path

import capstone
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import closure as C

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'config' / 'global_widths.yaml'

CTYPE = {(1, False): 'unsigned char', (1, True): 'signed char',
         (2, False): 'unsigned short', (2, True): 'short'}


def widths():
    """global name -> field size in bytes, for everything narrower than 4."""
    cfg = yaml.safe_load((ROOT / 'config' / 'symbols.yaml').read_text())
    data, secs = C.load_image()
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
    md.detail = True

    seen = collections.defaultdict(set)
    signed = set()
    for f in cfg['functions']:
        if not f.get('size'):
            continue
        code = C.read_va(data, secs, f['addr'], f['size'])
        if not code:
            continue
        for ins in md.disasm(code, f['addr']):
            for op in ins.operands:
                if op.type != capstone.x86.X86_OP_MEM:
                    continue
                m = op.mem
                if m.base == 0 and m.index == 0 and 0x400000 <= m.disp < 0x1000000:
                    seen[m.disp].add(op.size)
                    if ins.mnemonic in ('movsx', 'movsxd'):
                        signed.add(m.disp)

    extras = yaml.safe_load((ROOT / 'config' / 'extras_map.yaml').read_text())
    by_va = {}
    for k, v in extras.items():
        if isinstance(v, int):
            by_va.setdefault(v, []).append(k)

    out = {}
    for va, sizes in seen.items():
        if not sizes or max(sizes) > 2 or va not in by_va:
            continue
        for name in by_va[va]:
            out[name] = (min(sizes), va in signed)
    return out


def main():
    w = widths()
    if '--write' in sys.argv:
        OUT.write_text(
            '# GENERATED by tools/decomp/audit_widths.py - do not edit.\n'
            '# The C type of every fixed-VA global the original only ever\n'
            '# touches 1 or 2 bytes wide. Anything absent is 32-bit. A field\n'
            '# loaded with movsx is signed.\n'
            + yaml.safe_dump({k: CTYPE[v] for k, v in sorted(w.items())},
                             default_flow_style=False))
        print('wrote %s (%d narrow globals)' % (OUT, len(w)))
        return 0
    n1 = sum(1 for v in w.values() if v[0] == 1)
    ns = sum(1 for v in w.values() if v[1])
    print('narrow globals: %d (%d byte, %d halfword, %d signed)'
          % (len(w), n1, len(w) - n1, ns))
    for k in sorted(w):
        print('  %-34s %s' % (k, CTYPE[w[k]]))
    return 0


if __name__ == '__main__':
    sys.exit(main())
