#!/usr/bin/env python3
"""Generate a self-contained wasm32 C bundle of the verified SW render pipeline.

The portable-C render twins (FlushDrawQueue + the rasterizers) are faithful
32-bit code: they keep framebuffer/texture/record pointers in `unsigned int`
globals. That is exactly right for a wasm32 target, where `malloc` returns a
32-bit address and `long`/pointers are 32-bit, so the uint-pointer model is
lossless (it is NOT on macOS arm64 - see the pointer-width-fork memory note).

This collects the twin function BODIES (not the files - so the inline `extern`
decls and the matching `#else` naked bodies are skipped), emits each referenced
global as an lvalue aliased into a single linear arena via MK4_VA (so the vertex
arrays the triangle twins index as (&g_dispatchSave1378)[i] are contiguous by
construction), and writes one .c with a driver `main` that loads the original
data image, seeds a draw queue, runs FlushDrawQueue, and dumps the framebuffer.

  build/venv/bin/python tools/decomp/gen_wasm_render.py > build/wasm/mk4_render.c
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import verify_twin as vt
import verify_coexec as vc

BASE = vc.BASE                    # 0x400000 = MK4_ORIG_IMAGE_BASE
# Scratch regions placed ABOVE the data image so MK4_VA offsets stay positive.
FB_VA = 0x01000000
TEX_VA = 0x01100000
W, H = 320, 240                   # a real-ish frame
RENDER_MODE_VA = 0x4f4b3c
REC = 0xf71310                    # draw-queue record start (sort key at +0x12)


def collect(seed, fn_va):
    """Closure of twin bodies reachable from `seed` via direct calls."""
    bodies, order, need_stub = {}, [], set()
    work = list(seed)
    while work:
        name = work.pop(0)
        if name in bodies:
            continue
        t = vc.extract_twin_any(name)
        if t is None:
            need_stub.add(name)
            continue
        body = t[0]
        bodies[name] = body
        order.append(name)
        for callee in sorted(set(re.findall(r'\b([A-Za-z_]\w*)\b', body))):
            if callee != name and callee in fn_va and callee not in bodies:
                work.append(callee)
    return bodies, order, need_stub


def gdef_arena(g, va, alltext):
    """Body-usage-aware lvalue alias into the arena (mirrors verify_coexec.gdef
    but resolves to MK4_VA(...) instead of an absolute VA)."""
    if re.search(r'\(\s*\*\s*%s\s*\)\s*\(' % g, alltext) or \
       re.search(r'\b%s\s*\(' % g, alltext):
        return '#define %s (*(unsigned int (**)())MK4_VA(unsigned int, 0x%xu))\n' % (g, va)
    if re.search(r'\b%s\s*\[' % g, alltext):
        return '#define %s ((unsigned int *)MK4_VA(unsigned int, 0x%xu))\n' % (g, va)
    deref = False
    for m in re.finditer(r'\*\s*%s\b' % g, alltext):
        j = m.start() - 1
        while j >= 0 and alltext[j] in ' \t':
            j -= 1
        if j < 0 or (alltext[j] not in '_)]' and not alltext[j].isalnum()):
            deref = True
    if deref:
        return '#define %s (*(unsigned int **)MK4_VA(unsigned int, 0x%xu))\n' % (g, va)
    return '#define %s (*(unsigned int *)MK4_VA(unsigned int, 0x%xu))\n' % (g, va)


def main():
    fn_va, gl_va = vt.load_maps()
    seed = ['FlushDrawQueue']
    bodies, order, need_stub = collect(seed, fn_va)
    # Renderer_GetMode is the only SW-path callee we satisfy ourselves.
    need_stub.discard('FlushDrawQueue')
    alltext = '\n'.join(bodies.values())
    globs = sorted(set(re.findall(r'\bg_\w+', alltext)))
    missing = [g for g in globs if g not in gl_va]

    out = []
    P = out.append
    P('/* GENERATED by tools/decomp/gen_wasm_render.py - do not edit. */')
    P('/* Self-contained wasm32 bundle of the verified SW render pipeline. */')
    P('#define NON_MATCHING 1')
    P('#define MK4_ARENA 1')
    P('#include <stdio.h>')
    P('#include <stdlib.h>')
    P('#include <string.h>')
    P('#include "portable/ghidra_types.h"')
    P('#include "portable/mem_model.h"')
    P('')
    P('unsigned char *g_mk4Arena = 0;       /* arena base (32-bit in wasm32) */')
    P('unsigned int   g_mk4ArenaSize = 0;')
    P('')
    P('/* --- global aliases into the linear arena (contiguous by construction) --- */')
    for g in globs:
        if g in gl_va:
            P(gdef_arena(g, gl_va[g], alltext).rstrip())
    P('')
    P('/* --- forward declarations --- */')
    for n in order:
        P('void %s(void);' % n)
    P('static int Renderer_GetMode(void);')
    P('')
    P('/* --- render twin bodies (verified portable C) --- */')
    for n in order:
        P(bodies[n])
        P('')
    P('static int Renderer_GetMode(void) {')
    P('    return *(int *)MK4_VA(int, 0x%xu);' % RENDER_MODE_VA)
    P('}')
    P('')
    # ---- driver ----
    P(DRIVER % dict(fb_va=FB_VA, tex_va=TEX_VA, w=W, h=H,
                    mode_va=RENDER_MODE_VA, rec=REC))
    sys.stdout.write('\n'.join(out) + '\n')
    sys.stderr.write('twins=%d  stubs_needed=%s  missing_globals=%s\n'
                     % (len(order), sorted(need_stub) or 'none', missing or 'none'))


DRIVER = r'''
/* ---------------- driver ---------------- */
#define FB_VA   0x%(fb_va)xu
#define TEX_VA  0x%(tex_va)xu
#define W       %(w)d
#define H       %(h)d
#define PITCH   (W * 2)
#define REC     0x%(rec)xu

static void setw(unsigned int va, unsigned short v) {
    *(unsigned short *)MK4_VA(unsigned short, va) = v;
}
static void setb(unsigned int va, unsigned char v) {
    *(unsigned char *)MK4_VA(unsigned char, va) = v;
}
static void setdw(unsigned int va, unsigned int v) {
    *(unsigned int *)MK4_VA(unsigned int, va) = v;
}

/* one 0x1c-byte primitive record (mirrors verify_flush.rect_record) */
static void rec_prim(int idx, int x0, int y0, int x1, int y1,
                     int u0, int v0, int u1, int v1, int color, int typ) {
    unsigned int r = REC + (unsigned)idx * 0x1c;
    setw(r + 0, x0);   setw(r + 2, y0);
    setw(r + 4, x1);   setw(r + 6, y0);     /* V1 */
    setw(r + 8, x1);   setw(r + 0xa, y1);
    setb(r + 0xc, u0); setb(r + 0xd, v0);
    setb(r + 0xe, u1); setb(r + 0xf, v1);
    setb(r + 0x10, u1); setb(r + 0x11, v1);
    setw(r + 0x12, x0);                      /* sort key */
    setw(r + 0x14, color);
    setw(r + 0x16, 0); setw(r + 0x18, 0);
    setw(r + 0x1a, typ);
}

int main(int argc, char **argv) {
    const char *img = (argc > 1) ? argv[1] : "build/arena.bin";
    const char *outp = (argc > 2) ? argv[2] : "build/wasm/frame.ppm";
    FILE *f = fopen(img, "rb");
    long n;
    unsigned int i;
    if (!f) { fprintf(stderr, "cannot open %%s\n", img); return 2; }
    fseek(f, 0, SEEK_END); n = ftell(f); fseek(f, 0, SEEK_SET);
    g_mk4ArenaSize = 0x1400000;               /* 20 MB: covers image + FB + TEX */
    g_mk4Arena = (unsigned char *)calloc(1, g_mk4ArenaSize);
    if (!g_mk4Arena) { fprintf(stderr, "calloc failed\n"); return 2; }
    if (fread(g_mk4Arena, 1, (size_t)n, f) != (size_t)n) { fprintf(stderr,"short read\n"); return 2; }
    fclose(f);

    /* a simple texture: distinct non-zero RGB565 texels */
    for (i = 0; i < 0x100000; i += 2)
        *(unsigned short *)MK4_VA(unsigned short, TEX_VA + i) =
            (unsigned short)((((i >> 1) %% 255) + 1));

    /* renderer state + viewport (framebuffer + texture as raw 32-bit ptrs) */
    setdw(0x%(mode_va)xu, 5);                              /* SW mode */
    g_drawQueueSize = 7;
    g_viewportX = (unsigned int)(unsigned long)MK4_VA(void, FB_VA);
    g_viewportY = PITCH;
    g_viewportW = W;
    g_viewportH = H;
    g_dispatchSave1400 = (unsigned int)(unsigned long)MK4_VA(void, TEX_VA);

    /* a small scene exercising the full dispatch (rects + triangles) */
    rec_prim(0,  20,  20, 160, 120, 0, 0, 60, 40, 0xffff, 0x20);        /* ScanlineTexBlit  */
    rec_prim(1,  60,  40, 220, 160, 4, 2, 80, 50, 0x1000, 0x20);        /* Paletted         */
    rec_prim(2, 100,  60, 280, 200, 1, 1, 70, 45, 0xffff, 0x20|0x80);   /* Interlaced       */
    rec_prim(3,  40, 100, 200, 220, 2, 0, 64, 36, 0xffff, 0x20|0x40);   /* BlitBlend16bpp   */
    rec_prim(4, 130,  30, 300, 210, 0, 0, 90, 60, 0xffff, 0x00);        /* TexturedTri      */
    rec_prim(5,  10, 140, 150, 235, 3, 1, 55, 40, 0x1000, 0x00);        /* Shaded           */
    rec_prim(6,  80,  80, 260, 180, 5, 3, 88, 52, 0xffff, 0x180);       /* Dithered (tri)   */

    FlushDrawQueue();

    {
        FILE *o = fopen(outp, "wb");
        unsigned short *fb = (unsigned short *)MK4_VA(unsigned short, FB_VA);
        int x, y, nz = 0;
        if (!o) { fprintf(stderr, "cannot write %%s\n", outp); return 2; }
        fprintf(o, "P6\n%%d %%d\n255\n", W, H);
        for (y = 0; y < H; y++) for (x = 0; x < W; x++) {
            unsigned short px = fb[y * W + x];
            unsigned char rgb[3];
            if (px) nz++;
            rgb[0] = (unsigned char)(((px >> 11) & 0x1f) << 3);
            rgb[1] = (unsigned char)(((px >> 5)  & 0x3f) << 2);
            rgb[2] = (unsigned char)(( px        & 0x1f) << 3);
            fwrite(rgb, 1, 3, o);
        }
        fclose(o);
        fprintf(stderr, "wrote %%s (%%dx%%d, %%d non-zero px)\n", outp, W, H, nz);
    }
    return 0;
}
'''

if __name__ == '__main__':
    main()
