#!/usr/bin/env python3
"""Step 4 foundation: VA -> native-fn-ptr trampoline table for native-full.

Stored function pointers in the engine hold ORIGINAL code VAs (0x4xxxxx); under
the arena those are not native code. This generates a sorted {orig_VA -> native
fn} table over the functions actually compiled into native-full, plus
MK4_ResolveCode(va) (binary search) that maps a stored VA to the native function
(or a reporting no-op if the target is not linked natively). Call sites become
  ((fn)MK4_ResolveCode(stored_va))(...)
A startup self-test asserts a few known VAs resolve to their native &fn.
Gated MK4_NATIVE_FULL.
"""
import re, yaml
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
sy = yaml.safe_load((ROOT/'config'/'symbols.yaml').read_text())
addr = {f['name']: f['addr'] for f in sy['functions'] if isinstance(f.get('addr'), int)}
defpat = re.compile(r'^(?:__declspec\(naked\)\s*)?(?:static\s+)?(?:unsigned |signed )?'
                    r'[A-Za-z_][\w \*]*?\b([A-Za-z_]\w*)\s*\([^;{]*\)\s*\{', re.M)
fns = {}
for line in (ROOT/'tools'/'decomp'/'native_full_srcs.txt').read_text().split():
    s = (ROOT/line).read_text(errors='ignore')
    for m in defpat.finditer(s):
        n = m.group(1)
        if n in addr and n not in ('if','for','while','switch'):
            fns[n] = addr[n]
# Callback targets with no symbols.yaml entry - handlers packed inside a larger
# blob entry - are registered here instead, so the matching build stays untouched.
extra_path = ROOT/'config'/'codeptr_extras.yaml'
extra = 0
if extra_path.exists():
    ex = yaml.safe_load(extra_path.read_text()) or {}
    defined = set()
    for line in (ROOT/'tools'/'decomp'/'native_full_srcs.txt').read_text().split():
        defined |= set(defpat.findall((ROOT/line).read_text(errors='ignore')))
    for va, name in (ex.get('entries') or {}).items():
        va = va if isinstance(va, int) else int(str(va), 16)
        if name not in defined:
            raise SystemExit('codeptr_extras: %s (0x%x) is not defined in any '
                             'native_full_srcs.txt TU' % (name, va))
        if name in fns and fns[name] != va:
            raise SystemExit('codeptr_extras: %s already maps to 0x%x' % (name, fns[name]))
        fns[name] = va
        extra += 1

items = sorted(fns.items(), key=lambda kv: kv[1])

L = ['/* GENERATED by tools/decomp/gen_codeptr_table.py - VA->native-fn trampoline. */',
     '#ifdef MK4_NATIVE_FULL', '#include <SDL2/SDL.h>', '']
L += ['extern int %s();' % n for n, _ in items]
L += ['', 'static const struct { unsigned va; void *fn; } g_codePtrTable[] = {']
L += ['    {0x%xu, (void*)%s},' % (va, n) for n, va in items]
L += ['};', 'enum { MK4_CODEPTR_N = sizeof(g_codePtrTable)/sizeof(g_codePtrTable[0]) };', '',
      'static void MK4_CodeMissing(void) { }',
      '',
      'void *MK4_ResolveCode(unsigned va) {',
      '    int lo = 0, hi = MK4_CODEPTR_N - 1;',
      '    while (lo <= hi) {',
      '        int mid = (lo + hi) >> 1;',
      '        unsigned m = g_codePtrTable[mid].va;',
      '        if (m == va) return g_codePtrTable[mid].fn;',
      '        if (m < va) lo = mid + 1; else hi = mid - 1;',
      '    }',
      '    /* Unknown VA. Passing it through means the caller JUMPS to a raw',
      '     * VA - unmapped here, so the process dies with no indication of which',
      '     * target was missing. Report it once and hand back a no-op instead, so',
      '     * one unconverted callback does not hide the rest of the frame. */',
      '    { static unsigned seen[32]; static int n; int i;',
      '      for (i = 0; i < n; i++) if (seen[i] == va) return (void*)MK4_CodeMissing;',
      '      if (n < 32) { seen[n++] = va;',
      '        SDL_Log("unresolved code VA 0x%08x - target not linked natively", va); } }',
      '    return (void*)MK4_CodeMissing;',
      '}', '',
      'void MK4_CodePtrSelfTest(void) {',
      '    int i, ok = 0;',
      '    for (i = 0; i < MK4_CODEPTR_N; i++)',
      '        if (MK4_ResolveCode(g_codePtrTable[i].va) == g_codePtrTable[i].fn) ok++;',
      '    SDL_Log("codeptr trampoline: %d/%d VAs resolve to native fns", ok, MK4_CODEPTR_N);',
      '}', '#endif /* MK4_NATIVE_FULL */']
(ROOT/'src'/'platform'/'sdl'/'native_codeptr_table.c').write_text('\n'.join(L)+'\n')
print('wrote native_codeptr_table.c: %d entries (%d from codeptr_extras.yaml)'
      % (len(items), extra))
