#!/usr/bin/env python3
"""Generate include/portable/arena_globals.h: route named fixed-VA globals
through the memory-model seam for the relocated (MK4_ARENA) build.

Named globals (g_dualC, g_cj_*, ...) are not individual C variables in this
decomp - they are offsets into the .data/.rdata blobs, pinned at their VAs by
the linker for the matching build, and referenced by symbol. The matching
build never needs a C declaration for them; the portable/native build does.

Under MK4_ARENA the arena already holds those .data/.rdata bytes at their VAs
(loaded by MK4_ArenaInitFromFile), so the cleanest, most consistent thing is
to `#define` each such global as its arena accessor - reads/writes land at the
original VA with the original initial value, no separate C storage, no init
step. (This is exactly how verify_coexec models globals.)

Only globals NOT already declared `extern` in a header are emitted (those keep
their ordinary-C-variable treatment). Emission is typed by how the corpus uses
each name: indexed/dereferenced -> pointer form, else scalar lvalue form.

The header is inert under MK4_COEXEC_GATE (the co-exec verifier defines its own
globals) and outside MK4_ARENA.

Run:  build/venv/bin/python tools/decomp/gen_arena_globals.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'include' / 'portable' / 'arena_globals.h'


def main():
    import yaml
    extras = yaml.safe_load((ROOT / 'config' / 'extras_map.yaml').read_text())
    gl = {n: int(a) for n, a in extras.items()
          if n.startswith('g_') and isinstance(a, int)}

    # Globals already declared extern in a header keep their C-variable form.
    declared = set()
    for h in (ROOT / 'include').rglob('*.h'):
        for m in re.finditer(r'\bextern\b[^;]*?\b(g_[A-Za-z0-9_]+)',
                             h.read_text(errors='ignore')):
            declared.add(m.group(1))

    # One pass over the corpus: which names are indexed (g[]) or dereferenced
    # (*g unary / g->) -> need the pointer form so those expressions type-check.
    arr = set()
    ptr = set()
    arr_re = re.compile(r'\b(g_[A-Za-z0-9_]+)\s*\[')
    # unary deref: a '*' whose preceding non-space char is not an operand
    deref_re = re.compile(r'(?<![\w\)\]])\*\s*(g_[A-Za-z0-9_]+)\b')
    arrow_re = re.compile(r'\b(g_[A-Za-z0-9_]+)\s*->')
    for c in (ROOT / 'src').rglob('*.c'):
        s = c.read_text(errors='ignore')
        arr.update(arr_re.findall(s))
        ptr.update(deref_re.findall(s))
        ptr.update(arrow_re.findall(s))

    names = sorted(n for n in gl if n not in declared)
    lines = []
    for n in names:
        va = gl[n]
        if n in arr or n in ptr:
            lines.append('#define %s ((unsigned int *)MK4_VA(unsigned int, 0x%xu))'
                         % (n, va))
        else:
            lines.append('#define %s (*MK4_VA(unsigned int, 0x%xu))' % (n, va))

    hdr = '''/**
 * GENERATED by tools/decomp/gen_arena_globals.py - do not edit by hand.
 *
 * Routes named fixed-VA globals through the memory-model seam for the
 * relocated (MK4_ARENA) build. See the generator's docstring. Inert under the
 * matching build (no MK4_ARENA), and under the co-exec verifier gate
 * (MK4_COEXEC_GATE) which supplies its own global definitions.
 */
#ifndef MK4_PORTABLE_ARENA_GLOBALS_H
#define MK4_PORTABLE_ARENA_GLOBALS_H

#if defined(MK4_ARENA) && !defined(MK4_COEXEC_GATE)
/* MK4_VA comes from mem_model.h, which includes this file. */
%s
#endif

#endif /* MK4_PORTABLE_ARENA_GLOBALS_H */
''' % '\n'.join(lines)
    OUT.write_text(hdr)
    print('wrote %s: %d globals (%d arr/ptr, %d scalar; %d skipped as header-declared)'
          % (OUT.relative_to(ROOT), len(names),
             sum(1 for n in names if n in arr or n in ptr),
             sum(1 for n in names if n not in arr and n not in ptr),
             len(gl) - len(names)))


if __name__ == '__main__':
    main()
