#!/usr/bin/env python3
"""
Generate include/portable/code_va.h - the VA of every function, by name.

A twin that installs a callback writes its own address into a node field:

    *(unsigned int *)(base + 8) = (unsigned int)&InstallSelfPairedGate;

The slot is THIRTY-TWO BITS. Under the identity model that cast yields the
function's VA and everything works; under the arena it truncates a 64-bit host
pointer and the engine later calls a VA that is not one. 59 sites do this.

MK4_CODE_VA(f) is the seam. Under MK4_ARENA it expands to the function's VA
from config/symbols.yaml, which is what the slot must hold for MK4_ResolveCode
to turn it back into the native function. Everywhere else - the matching build
and the co-exec harness - it expands to the ORIGINAL expression, so the bytes
and every existing verification are untouched by construction.

  build/venv/bin/python tools/decomp/gen_code_va.py
"""
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'include' / 'portable' / 'code_va.h'

cfg = yaml.safe_load((ROOT / 'config' / 'symbols.yaml').read_text())
fns = sorted({f['name']: f['addr'] for f in cfg['functions']
              if isinstance(f.get('addr'), int)}.items())

L = ['/* GENERATED by tools/decomp/gen_code_va.py - do not edit. */',
     '#ifndef MK4_PORTABLE_CODE_VA_H',
     '#define MK4_PORTABLE_CODE_VA_H',
     '',
     '/* MK4_CODE_VA(f): the value a 32-bit callback slot must hold for f.',
     ' *',
     ' * Under the relocated model that is f\'s original VA - a host function',
     ' * pointer does not fit in the slot, and MK4_ResolveCode turns the VA back',
     ' * into the native function at the call. Everywhere else it is the original',
     ' * `(unsigned int)&f`, so the matching build and the co-exec harness see',
     ' * exactly the expression they saw before. */',
     '#if defined(MK4_ARENA)',
     '#define MK4_CODE_VA(f)  MK4_CODE_VA_##f',
     '']
L += ['#define MK4_CODE_VA_%-52s 0x%08xu' % (n, a) for n, a in fns]
L += ['',
      '#else',
      '#define MK4_CODE_VA(f)  ((unsigned int)&f)',
      '#endif',
      '',
      '#endif /* MK4_PORTABLE_CODE_VA_H */']
OUT.write_text('\n'.join(L) + '\n')
print('wrote %s: %d functions' % (OUT.relative_to(ROOT), len(fns)))
