#!/usr/bin/env python3
"""Consolidate fixed-VA global declarations for the native build.

Many converted twins reference fixed-VA globals (g_dualC, g_cj_*, ...) that are
declared `extern` only LOCALLY in one file, so other twins that use them fail to
compile natively ("use of undeclared identifier"). This scans every existing
`extern <type> g_name;` decl in the corpus, keeps the names with a single
consistent type, and emits:
  - include/portable/native_globals.h : the extern decls (gated NON_MATCHING),
    included from ghidra_types.h so every twin sees them. Duplicate-but-identical
    externs are legal C, so files with their own local decl are unaffected.
  - src/platform/sdl/native_globals.c : weak definitions (gated MK4_NATIVE_FULL)
    so native-full links. Weak => a real/arena def overrides later.
Only emits globals NOT already declared in a header (those are already shared).
"""
import re
from collections import defaultdict
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
decl = re.compile(r'^\s*extern\s+((?:unsigned\s+|signed\s+)?(?:int|char|short|long|u8|u16|u32|s8|s16|s32))\s+(g_[A-Za-z0-9_]+)\s*;', re.M)
# Map project typedefs to primitives so the generated headers need no typedef
# header and stay type-compatible (u32 IS unsigned int, etc.).
PRIM = {'u8': 'unsigned char', 'u16': 'unsigned short', 'u32': 'unsigned int',
        's8': 'signed char', 's16': 'short', 's32': 'int'}

# names already shared via a header -> skip (don't redeclare). Exclude our own
# generated header, else it self-poisons (everything looks already-declared).
hdr_names = set()
for h in (ROOT/'include').rglob('*.h'):
    if h.name == 'native_globals.h':
        continue
    for m in decl.finditer(h.read_text(errors='ignore')):
        hdr_names.add(m.group(2))

types = defaultdict(set)
for c in (ROOT/'src').rglob('*.c'):
    for m in decl.finditer(c.read_text(errors='ignore')):
        types[m.group(2)].add(m.group(1).strip())

emit = {n: PRIM.get(list(ts)[0], list(ts)[0]) for n, ts in sorted(types.items())
        if len(ts) == 1 and n not in hdr_names}

hdr = ['/* GENERATED by tools/decomp/gen_native_globals.py - do not edit. */',
       '#ifndef MK4_PORTABLE_NATIVE_GLOBALS_H', '#define MK4_PORTABLE_NATIVE_GLOBALS_H',
       '#if defined(NON_MATCHING)', '']
hdr += ['extern %s %s;' % (t, n) for n, t in emit.items()]
hdr += ['', '#endif', '#endif']
(ROOT/'include'/'portable'/'native_globals.h').write_text('\n'.join(hdr)+'\n')

src = ['/* GENERATED by tools/decomp/gen_native_globals.py - weak defs for native-full. */',
       '#if defined(MK4_NATIVE_FULL)', '']
src += ['__attribute__((weak)) %s %s;' % (t, n) for n, t in emit.items()]
src += ['', '#endif']
(ROOT/'src'/'platform'/'sdl'/'native_globals.c').write_text('\n'.join(src)+'\n')
print('emitted %d consolidated globals (%d already in headers, skipped)' % (len(emit), len(hdr_names)))
