#!/usr/bin/env bash
#
# Bootstraps a Whisky bottle ready to host MSVC 5.0 for the matching
# build. Doesn't actually install MSVC (you provide your own legally-
# obtained copy) — it sets up the bottle, the directory layout, and
# the Win98 compat that MSVC's installer + IDE expect.
#
# After this script: copy MSVC 5.0's CL.EXE / LINK.EXE / .lib / headers
# into $WINEPREFIX/drive_c/MSVC5/{Bin,Lib,Include} (see the section
# "Layout expected" printed at the end).
#
# Usage:  ./tools/decomp/setup-msvc50.sh

set -euo pipefail

BOTTLE_NAME="${MSVC50_BOTTLE_NAME:-MK4DECOMP}"

# ----- locate Whisky -------------------------------------------------------

if ! command -v whisky >/dev/null 2>&1; then
    echo "ERROR: whisky CLI not found. Install via:"
    echo "       brew install --cask whisky"
    exit 1
fi

# ----- create or reuse the bottle ------------------------------------------

if whisky list 2>/dev/null | awk 'NR>3 {print $2}' | grep -qx "$BOTTLE_NAME"; then
    echo "==> Bottle '$BOTTLE_NAME' already exists; reusing."
else
    echo "==> Creating bottle '$BOTTLE_NAME'..."
    whisky create "$BOTTLE_NAME" >/dev/null
fi

eval "$(whisky shellenv "$BOTTLE_NAME")"

echo "==> Bottle prefix: $WINEPREFIX"

# ----- Win98 compat for CL / LINK ------------------------------------------

echo "==> Setting Win98 compat for CL.EXE, LINK.EXE, NMAKE.EXE..."
for exe in CL.EXE LINK.EXE NMAKE.EXE C1.EXE C2.EXE C1XX.EXE; do
    wine64 reg add "HKCU\\Software\\Wine\\AppDefaults\\$exe" \
        /v Version /d win98 /f >/dev/null 2>&1
done

# ----- create the MSVC5 layout under drive_c -------------------------------

MSVC5_ROOT="$WINEPREFIX/drive_c/MSVC5"
mkdir -p "$MSVC5_ROOT/"{Bin,Lib,Include}

cat > "$MSVC5_ROOT/README.txt" <<EOF
MSVC 5.0 layout for MK4 matching decomp.

Place the following files from your MSVC 5.0 installation here:

Bin/
    CL.EXE         C compiler driver
    C1.EXE         C front-end
    C2.EXE         C back-end / optimizer
    LINK.EXE       linker
    ML.EXE         assembler (optional, for inline asm support)
    MSPDB50.DLL    debug DB helper (link.exe needs it on PATH)
    MSPDB50.RC

Lib/
    LIBC.LIB       single-threaded CRT
    LIBCMT.LIB     /MT static-multithreaded CRT  <-- MK4 uses this one
    OLDNAMES.LIB
    KERNEL32.LIB
    USER32.LIB
    GDI32.LIB
    ADVAPI32.LIB
    WINMM.LIB
    DDRAW.LIB      <-- DirectDraw 5/6
    DSOUND.LIB
    UUID.LIB

Include/
    (the C and Win32 SDK headers from MSVC 5.0)

Recommended SP: SP3 (final SP for MSVC 5.0).
EOF

# ----- export a small env-vars file used by cl/link wrappers ---------------

ENV_FILE="$WINEPREFIX/drive_c/MSVC5/env.txt"
cat > "$ENV_FILE" <<EOF
INCLUDE=C:\\MSVC5\\Include
LIB=C:\\MSVC5\\Lib
PATH=C:\\MSVC5\\Bin;C:\\windows\\system32
EOF

# ----- write a config file the Makefile reads -----------------------------

CONFIG_DIR="$(cd "$(dirname "$0")/../.." && pwd)/config"
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_DIR/msvc50.env" <<EOF
# Generated by tools/decomp/setup-msvc50.sh — do not edit by hand.
# Source this file (or read via Make) to get the bottle path.
MSVC50_BOTTLE="$BOTTLE_NAME"
MSVC50_PREFIX="$WINEPREFIX"
MSVC50_ROOT="$MSVC5_ROOT"
EOF

# ----- print summary -------------------------------------------------------

echo
echo "============================================================"
echo "Bottle ready: $BOTTLE_NAME"
echo "Prefix:       $WINEPREFIX"
echo "MSVC5 root:   $MSVC5_ROOT"
echo "Config:       $CONFIG_DIR/msvc50.env"
echo "============================================================"
echo
echo "Next steps:"
echo "  1. Place MSVC 5.0 binaries + libs + headers under"
echo "     $MSVC5_ROOT/{Bin,Lib,Include}"
echo "     (see $MSVC5_ROOT/README.txt for the file list)"
echo
echo "  2. Verify the toolchain:"
echo "       ./tools/decomp/test-toolchain.sh"
echo
echo "  3. Run a build:"
echo "       make matching"
