"""Verify the PE structure synthesizer for .rdata is scaffold-independent.

Zeroes the IAT / Import Directory / ILT / hint-name / DLL-name regions
in a copy of orig MK4.EXE, then replays the synth steps from
config/imports.yaml. If the regenerated bytes match orig, the synth is
proven to derive these regions entirely from the declarative manifest -
no scaffold dependency for PE structure.

Usage: python3 tools/decomp/verify_imports.py
"""
import struct, sys, yaml
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from synthesize import parse_pe_sections


def main():
    with open('game/MK4.EXE','rb') as f: orig = f.read()
    ib, secs = parse_pe_sections(orig)
    rdata = next(s for s in secs if s['name'] == '.rdata')

    scaffold = bytearray(orig)
    rdata_raddr = rdata['raddr']
    def rva_to_off(rva): return rva - 0xd2000 + rdata_raddr

    # Wipe the regions we claim to synthesize so any reliance on orig content
    # within them will show up as a diff.
    def wipe(va_start, va_end):
        fo = rva_to_off(va_start - 0x400000)
        scaffold[fo:fo + (va_end - va_start)] = b'\xee' * (va_end - va_start)
    wipe(0x4d2000, 0x4d224c)  # IAT
    wipe(0x4d3890, 0x4d454c)  # Import Dir + ILT + hint/name + DLL names

    with open('config/imports.yaml') as f: imp = yaml.safe_load(f)
    def rva_to_file(rva): return rva - 0xd2000 + rdata['raddr']

    # IAT + ILT (same content per DLL: list of hint-name RVAs + null terminator)
    for dll in imp['dlls']:
        for tbl_rva in (dll['oft_rva'], dll['ft_rva']):
            fo = rva_to_file(tbl_rva)
            for k, ent in enumerate(dll['imports']):
                slot = (0x80000000 | ent['ordinal']) if 'ordinal' in ent else ent['hint_name_rva']
                struct.pack_into('<I', scaffold, fo + k*4, slot)
            struct.pack_into('<I', scaffold, fo + len(dll['imports'])*4, 0)

    # Hint/name entries + DLL names: linker laid them out in RVA order with
    # 0x00 padding to keep subsequent entries 2-byte aligned.
    all_entries = []
    for dll in imp['dlls']:
        for ent in dll['imports']:
            if 'ordinal' in ent: continue
            all_entries.append((ent['hint_name_rva'], ent['hint'], ent['name']))
        all_entries.append((dll['name_rva'], None, dll['name']))
    all_entries.sort()
    for idx, (rva, hint, name) in enumerate(all_entries):
        fo = rva_to_file(rva)
        base = 0
        if hint is not None:
            struct.pack_into('<H', scaffold, fo, hint); base = 2
        name_bytes = name.encode('ascii') + b'\x00'
        scaffold[fo+base:fo+base+len(name_bytes)] = name_bytes
        written = base + len(name_bytes)
        if idx + 1 < len(all_entries):
            next_rva = all_entries[idx+1][0]
        else:
            next_rva = (rdata['vaddr'] - ib) + rdata['vsize']
        footprint = next_rva - rva
        if footprint > written:
            scaffold[fo+written:fo+footprint] = b'\x00' * (footprint - written)

    # Import Directory
    imp_dir_off = rva_to_file(imp['import_directory_rva'])
    for i, dll in enumerate(imp['dlls']):
        struct.pack_into('<IIIII', scaffold, imp_dir_off + i*20,
                         dll['oft_rva'], 0, 0, dll['name_rva'], dll['ft_rva'])
    struct.pack_into('<IIIII', scaffold, imp_dir_off + len(imp['dlls'])*20,
                     0, 0, 0, 0, 0)

    diff = sum(1 for a, b in zip(orig, scaffold) if a != b)
    if diff == 0:
        print('*** PE STRUCTURE SCAFFOLD-INDEPENDENT ***')
        print('IAT + Import Directory + ILT + hint-name + DLL-name fully derived from')
        print('config/imports.yaml; no orig MK4.EXE content needed for these regions.')
        return 0
    else:
        print(f'FAILED: {diff} bytes differ from orig after synth-from-zero.')
        return 1


if __name__ == '__main__':
    sys.exit(main())
